#코스피 네이버 금융 크롤링

In [ ]:
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
# from openpyxl import Workbook

list_1 = []
jongmok = []
for i in range(1,36):
    url = "https://finance.naver.com/sise/sise_market_sum.naver?&page={}".format(i)
    res = requests.get(url)
    soup = BeautifulSoup(res.text, 'lxml')
    Kospi_200 = soup.find("table", attrs={"class": "type_2"}).find("tbody").find_all("a", attrs={"class": "tltle"})

    for index, stock in enumerate(Kospi_200):
        jongmok.append(stock.text)
        link = "https://finance.naver.com/"+stock["href"]     # a tag 내에서 "href" 속성값을 가져온다.
        sub_res = requests.get(link)                                 # 링크를 통해 우리가 원하는 기업별 데이터 페이지 데이터 크롤링
        sub_soup = BeautifulSoup(sub_res.text, 'lxml')
    
        ParamList = ['매출액', '영업이익', '당기순이익','ROE(지배주주)','EPS(원)','BPS(원)']
        
        Stock_contents = []
        for idx, pText in enumerate(ParamList):
            try:
                param = " ".join(sub_soup.find('strong', text=pText).parent['class'])
                sub_tbody = sub_soup.find("table", attrs={"class": "tb_type1 tb_num tb_type1_ifrs"}).find("tbody")
                sub_title = sub_tbody.find("th", attrs={"class": param}).get_text().strip()
    
                #param 에 매핑되는 row 검색 => 상위 이동 => 해당 row의 모든 td 컬럼 가져오기
                dataOfParam = sub_tbody.find("th", attrs = {"class":param}).parent.find_all("td")

                for i in dataOfParam:
                    Stock_contents.append(i.get_text().strip())
                    #print(sub_title, " : ",value_param)
            except:
                continue
        
        list_1.append(Stock_contents)

KeyboardInterrupt: ignored

In [ ]:
columns = ['sales_Y_3', 'sales_Y_2', 'sales_Y_1', 'E_sales', 'sales_Q_5', 'sales_Q_4', 'sales_Q_3', 'sales_Q_2', 'sales_Q_1', 'E_sales_Q', 'OProfit_Y_3', 'OProfit_Y_2','OProfit_Y_1','E_OProfit_Y','OProfit_Q_5','OProfit_Q_4','OProfit_Q_3','OProfit_Q_2','OProfit_Q_1','E_OProfit_Q','Net_Income_Y_3,','Net_Income_Y_2,','Net_Income_Y_1','E_Net_Income_Y','Net_Income_Q_5','Net_Income_Q_4,','Net_Income_Q_3','Net_Income_Q_2','Net_Income_Q_1','E_Net_Income_Q','Y_3_ROE','Y_2_ROE','Y_1_ROE','Y_E_ROE','Q_5_ROE','Q_4_ROE','Q_3_ROE','Q_2_ROE','Q_1_ROE','Q_E_ROE','Y_3_EPS','Y_2_EPS','Y_1_EPS','Y_E_EPS','Q_5_EPS','Q_4_EPS','Q_3_EPS','Q_2_EPS','Q_1_EPS','Q_E_EPS','Y_3_BPS','Y_2_BPS','Y_1_BPS','Y_E_BPS','Q_5_BPS','Q_4_BPS','Q_3_BPS','Q_2_BPS','Q_1_BPS','Q_E_BPS']
df1 = pd.DataFrame(list_1,columns=columns)
df1.to_csv('코스피자료.csv')

In [ ]:
df1 = pd.read_csv('코스피자료.csv',index_col=0)
df1['종목명'] = jongmok

In [ ]:
df1.columns

In [ ]:
df1 = df1[['종목명','sales_Y_3', 'sales_Y_2', 'sales_Y_1', 'E_sales', 'sales_Q_5',
       'sales_Q_4', 'sales_Q_3', 'sales_Q_2', 'sales_Q_1', 'E_sales_Q',
       'OProfit_Y_3', 'OProfit_Y_2', 'OProfit_Y_1', 'E_OProfit_Y',
       'OProfit_Q_5', 'OProfit_Q_4', 'OProfit_Q_3', 'OProfit_Q_2',
       'OProfit_Q_1', 'E_OProfit_Q', 'Net_Income_Y_3,', 'Net_Income_Y_2,',
       'Net_Income_Y_1', 'E_Net_Income_Y', 'Net_Income_Q_5', 'Net_Income_Q_4,',
       'Net_Income_Q_3', 'Net_Income_Q_2', 'Net_Income_Q_1', 'E_Net_Income_Q',
       'Y_3_ROE', 'Y_2_ROE', 'Y_1_ROE', 'Y_E_ROE', 'Q_5_ROE', 'Q_4_ROE',
       'Q_3_ROE', 'Q_2_ROE', 'Q_1_ROE', 'Q_E_ROE', 'Y_3_EPS', 'Y_2_EPS',
       'Y_1_EPS', 'Y_E_EPS', 'Q_5_EPS', 'Q_4_EPS', 'Q_3_EPS', 'Q_2_EPS',
       'Q_1_EPS', 'Q_E_EPS', 'Y_3_BPS', 'Y_2_BPS', 'Y_1_BPS', 'Y_E_BPS',
       'Q_5_BPS', 'Q_4_BPS', 'Q_3_BPS', 'Q_2_BPS', 'Q_1_BPS', 'Q_E_BPS']]

In [ ]:
df1.to_csv('코스피자료.csv')

In [ ]:
!cp 코스피자료.csv ../gdrive/MyDrive/practice/

In [ ]:
ls -al ../gdrive/MyDrive/practice/

# 코스닥

In [ ]:
https://finance.naver.com/item/main.naver?code=030190

In [ ]:
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
# from openpyxl import Workbook

list_1 = []
jongmok = []
for i in range(1,32):
    url = "https://finance.naver.com/sise/sise_market_sum.naver?sosok=1&page={}".format(i)
    res = requests.get(url)
    soup = BeautifulSoup(res.text, 'lxml')
    Kospi_200 = soup.find("table", attrs={"class": "type_2"}).find("tbody").find_all("a", attrs={"class": "tltle"})

    for index, stock in enumerate(Kospi_200):
        jongmok.append(stock.text)
        link = "https://finance.naver.com/"+stock["href"]     # a tag 내에서 "href" 속성값을 가져온다.
        sub_res = requests.get(link)                                 # 링크를 통해 우리가 원하는 기업별 데이터 페이지 데이터 크롤링
        sub_soup = BeautifulSoup(sub_res.text, 'lxml')
    
        ParamList = ['매출액', '영업이익', '당기순이익','ROE(지배주주)','EPS(원)','BPS(원)']
        
        Stock_contents = []
        for idx, pText in enumerate(ParamList):
            try:
                param = " ".join(sub_soup.find('strong', text=pText).parent['class'])
                sub_tbody = sub_soup.find("table", attrs={"class": "tb_type1 tb_num tb_type1_ifrs"}).find("tbody")
                sub_title = sub_tbody.find("th", attrs={"class": param}).get_text().strip()
    
                #param 에 매핑되는 row 검색 => 상위 이동 => 해당 row의 모든 td 컬럼 가져오기
                dataOfParam = sub_tbody.find("th", attrs = {"class":param}).parent.find_all("td")

                for i in dataOfParam:
                    Stock_contents.append(i.get_text().strip())
                    #print(sub_title, " : ",value_param)
            except:
                continue
        
        list_1.append(Stock_contents)

In [ ]:
columns = ['sales_Y_3', 'sales_Y_2', 'sales_Y_1', 'E_sales', 'sales_Q_5', 'sales_Q_4', 'sales_Q_3', 'sales_Q_2', 'sales_Q_1', 'E_sales_Q', 'OProfit_Y_3', 'OProfit_Y_2','OProfit_Y_1','E_OProfit_Y','OProfit_Q_5','OProfit_Q_4','OProfit_Q_3','OProfit_Q_2','OProfit_Q_1','E_OProfit_Q','Net_Income_Y_3,','Net_Income_Y_2,','Net_Income_Y_1','E_Net_Income_Y','Net_Income_Q_5','Net_Income_Q_4,','Net_Income_Q_3','Net_Income_Q_2','Net_Income_Q_1','E_Net_Income_Q','Y_3_ROE','Y_2_ROE','Y_1_ROE','Y_E_ROE','Q_5_ROE','Q_4_ROE','Q_3_ROE','Q_2_ROE','Q_1_ROE','Q_E_ROE','Y_3_EPS','Y_2_EPS','Y_1_EPS','Y_E_EPS','Q_5_EPS','Q_4_EPS','Q_3_EPS','Q_2_EPS','Q_1_EPS','Q_E_EPS','Y_3_BPS','Y_2_BPS','Y_1_BPS','Y_E_BPS','Q_5_BPS','Q_4_BPS','Q_3_BPS','Q_2_BPS','Q_1_BPS','Q_E_BPS']
df1 = pd.DataFrame(list_1,columns=columns)
df1.to_csv('kospi_200_profit.csv')

In [ ]:
df1 = pd.read_csv('kospi_200_profit.csv')
df1['종목명'] = jongmok

In [ ]:
df1

In [ ]:
df1 = df1[['종목명','sales_Y_3', 'sales_Y_2', 'sales_Y_1', 'E_sales',
       'sales_Q_5', 'sales_Q_4', 'sales_Q_3', 'sales_Q_2', 'sales_Q_1',
       'E_sales_Q', 'OProfit_Y_3', 'OProfit_Y_2', 'OProfit_Y_1', 'E_OProfit_Y',
       'OProfit_Q_5', 'OProfit_Q_4', 'OProfit_Q_3', 'OProfit_Q_2',
       'OProfit_Q_1', 'E_OProfit_Q', 'Net_Income_Y_3,', 'Net_Income_Y_2,',
       'Net_Income_Y_1', 'E_Net_Income_Y', 'Net_Income_Q_5', 'Net_Income_Q_4,',
       'Net_Income_Q_3', 'Net_Income_Q_2', 'Net_Income_Q_1', 'E_Net_Income_Q',
       'Y_3_ROE', 'Y_2_ROE', 'Y_1_ROE', 'Y_E_ROE', 'Q_5_ROE', 'Q_4_ROE',
       'Q_3_ROE', 'Q_2_ROE', 'Q_1_ROE', 'Q_E_ROE', 'Y_3_EPS', 'Y_2_EPS',
       'Y_1_EPS', 'Y_E_EPS', 'Q_5_EPS', 'Q_4_EPS', 'Q_3_EPS', 'Q_2_EPS',
       'Q_1_EPS', 'Q_E_EPS', 'Y_3_BPS', 'Y_2_BPS', 'Y_1_BPS', 'Y_E_BPS',
       'Q_5_BPS', 'Q_4_BPS', 'Q_3_BPS', 'Q_2_BPS', 'Q_1_BPS', 'Q_E_BPS']]

In [ ]:
df1.T

,0,1,2,3,4,5,6,7,8,9,...,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549
종목명,셀트리온헬스케어,에코프로비엠,펄어비스,엘앤에프,카카오게임즈,위메이드,셀트리온제약,HLB,천보,리노공업,...,이베스트스팩5호,에스케이증권7호스팩,신영스팩5호,IBKS제16호스팩,에스디시스템,하나금융20호스팩,IBKS제12호스팩,유진스팩6호,케이프이에스제4호,대호특수강우
sales_Y_3,"7,135","5,892","4,048","5,057","4,208","1,271","1,735",362,"1,201","1,504",...,NaN,NaN,-,NaN,456,NaN,NaN,NaN,NaN,"2,099"
sales_Y_2,"11,009","6,161","5,359","3,133","3,910","1,136","2,336",384,"1,353","1,703",...,NaN,NaN,-,NaN,381,NaN,-,NaN,NaN,"2,042"
sales_Y_1,"16,276","8,547","4,888","3,561","4,955","1,262","3,987",562,"1,555","2,013",...,-,NaN,-,NaN,228,-,-,NaN,-,"1,417"
E_sales,"17,930","14,166","3,928","10,060","11,335","3,475",NaN,NaN,"2,629","2,772",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q_4_BPS,"12,373","21,170","10,583","7,629","13,551","7,631","8,064","4,539","22,830","22,224",...,"1,977",NaN,"1,970",NaN,646,NaN,"1,909",NaN,"1,810",666
Q_3_BPS,"12,613","21,399","10,971","7,304","13,871","8,020","8,437","4,494","23,485","22,335",...,"1,976",NaN,"1,968",NaN,655,NaN,"1,903",NaN,"1,811",679
Q_2_BPS,"12,859","21,985","11,073","7,225","17,249","8,413","8,688","4,235","24,145","24,268",...,"1,974",NaN,"1,966",NaN,782,NaN,"1,902","1,915","1,808",608
Q_1_BPS,"12,960","23,486","11,705","22,564","19,028","8,938","8,836","4,563","27,233","26,168",...,"1,973",NaN,"1,976","1,918",814,"1,941","1,901","1,915","1,809",616
Q_E_BPS,"13,423","31,929","11,618","14,254","17,583",NaN,NaN,NaN,"26,855","27,172",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df1.to_csv('코스닥자료.csv')

In [ ]:
!cp 코스닥자료.csv ../gdrive/MyDrive/practice/

In [ ]:
ls -al ../gdrive/MyDrive/practice/

total 406690
-rw------- 1 root root     24129 Mar  8 06:25 20220308_stat_v2.csv
-rw------- 1 root root       764 Jan 26 02:19 AirPassenger.zip
-rw------- 1 root root    491386 Apr 18  2020 Amazon.csv
-rw------- 1 root root    547789 Apr 18  2020 Apple.csv
-rw------- 1 root root    193828 Feb  5 08:45 bike-sharing-demand.zip
-rw------- 1 root root 150828752 Sep 19  2019 creditcard.csv
-rw------- 1 root root  69155672 Jan 24 00:12 creditcardfraud.zip
-rw------- 1 root root    403381 Mar 11 04:45 코스닥자료.csv
-rw------- 1 root root     12536 Feb 15 00:50 finterstellar.whl
-rw------- 1 root root    203809 Feb  7 00:17 house-prices-regression.zip
-rw------- 1 root root 123658202 Mar  2 09:00 kospi_stock_price.csv
-rw------- 1 root root     93065 Mar  2 06:16 kospi.xlsx
-rw------- 1 root root      9128 Jan 17 03:13 pima_indian_diabetes.zip
-rw------- 1 root root     66445 Mar  2 03:56 samba.csv
-rw------- 1 root root    437995 Feb 11 15:41 samsung.csv
-rw------- 1 root root   8646304 Jan 19 15:06 santander-customer-satisfaction.zip
-rw------- 1 root root    494614 Feb 10 00:47 TA_Lib-0.4.19-cp36-cp36m-win_amd64.whl
-rw------- 1 root root     28629 Feb 17 06:20 titanic_test.csv
-rw------- 1 root root     61194 Feb 17 06:20 titanic_train.csv
-rw------- 1 root root     88784 Jan 26 12:14 TSLA.csv
-rw------- 1 root root  60999314 Jan 18 04:37 UCI_HAR_Dataset.zip

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [ ]:
ls -al ../gdrive/MyDrive/practice/

total 407429
-rw------- 1 root root     24129 Mar  8 06:25 20220308_stat_v2.csv
-rw------- 1 root root    105225 Mar 14 03:57 종목_시가총액_20220314.csv
-rw------- 1 root root       764 Jan 26 02:19 AirPassenger.zip
-rw------- 1 root root    491386 Apr 18  2020 Amazon.csv
-rw------- 1 root root    547789 Apr 18  2020 Apple.csv
-rw------- 1 root root    193828 Feb  5 08:45 bike-sharing-demand.zip
-rw------- 1 root root 150828752 Sep 19  2019 creditcard.csv
-rw------- 1 root root  69155672 Jan 24 00:12 creditcardfraud.zip
-rw------- 1 root root    386872 Mar 14 03:17 코스피자료.csv
-rw------- 1 root root    403381 Mar 11 04:45 코스닥자료.csv
-rw------- 1 root root     12536 Feb 15 00:50 finterstellar.whl
-rw------- 1 root root    203809 Feb  7 00:17 house-prices-regression.zip
-rw------- 1 root root     70469 Mar 14 01:14 jongmok_upjong_20220314.csv
-rw------- 1 root root    102868 Mar 14 00:36 kospi_20220314.csv
-rw------- 1 root root      3188 Mar 14 01:00 kospi_average_per_pbr_20220314.csv
-rw------- 1 root root     76771 Mar 14 01:02 kospi_per_pbr_20220314.csv
-rw------- 1 root root 123658202 Mar  2 09:00 kospi_stock_price.csv
-rw------- 1 root root     93065 Mar  2 06:16 kospi.xlsx
-rw------- 1 root root     10073 Mar 22 01:40 momentum.py
-rw------- 1 root root      9128 Jan 17 03:13 pima_indian_diabetes.zip
-rw------- 1 root root     66445 Mar  2 03:56 samba.csv
-rw------- 1 root root    437995 Feb 11 15:41 samsung.csv
-rw------- 1 root root   8646304 Jan 19 15:06 santander-customer-satisfaction.zip
-rw------- 1 root root    494614 Feb 10 00:47 TA_Lib-0.4.19-cp36-cp36m-win_amd64.whl
-rw------- 1 root root     28629 Feb 17 06:20 titanic_test.csv
-rw------- 1 root root     61194 Feb 17 06:20 titanic_train.csv
-rw------- 1 root root     88784 Jan 26 12:14 TSLA.csv
-rw------- 1 root root  60999314 Jan 18 04:37 UCI_HAR_Dataset.zip

In [ ]:
PATH = '../gdrive/MyDrive/practice/'

In [ ]:
df = pd.read_csv(os.path.join(PATH,'코스닥자료.csv'),index_col=0)

In [ ]:
df.columns

Index(['종목명', 'sales_Y_3', 'sales_Y_2', 'sales_Y_1', 'E_sales', 'sales_Q_5',
       'sales_Q_4', 'sales_Q_3', 'sales_Q_2', 'sales_Q_1', 'E_sales_Q',
       'OProfit_Y_3', 'OProfit_Y_2', 'OProfit_Y_1', 'E_OProfit_Y',
       'OProfit_Q_5', 'OProfit_Q_4', 'OProfit_Q_3', 'OProfit_Q_2',
       'OProfit_Q_1', 'E_OProfit_Q', 'Net_Income_Y_3,', 'Net_Income_Y_2,',
       'Net_Income_Y_1', 'E_Net_Income_Y', 'Net_Income_Q_5', 'Net_Income_Q_4,',
       'Net_Income_Q_3', 'Net_Income_Q_2', 'Net_Income_Q_1', 'E_Net_Income_Q',
       'Y_3_ROE', 'Y_2_ROE', 'Y_1_ROE', 'Y_E_ROE', 'Q_5_ROE', 'Q_4_ROE',
       'Q_3_ROE', 'Q_2_ROE', 'Q_1_ROE', 'Q_E_ROE', 'Y_3_EPS', 'Y_2_EPS',
       'Y_1_EPS', 'Y_E_EPS', 'Q_5_EPS', 'Q_4_EPS', 'Q_3_EPS', 'Q_2_EPS',
       'Q_1_EPS', 'Q_E_EPS', 'Y_3_BPS', 'Y_2_BPS', 'Y_1_BPS', 'Y_E_BPS',
       'Q_5_BPS', 'Q_4_BPS', 'Q_3_BPS', 'Q_2_BPS', 'Q_1_BPS', 'Q_E_BPS'],
      dtype='object')

In [ ]:
upjong_avg = pd.read_csv(os.path.join(PATH,'kospi_average_per_pbr_20220314.csv'),encoding='cp949')

In [ ]:
data = pd.read_csv(os.path.join(PATH,'kospi_per_pbr_20220314.csv'),encoding='cp949')[['종목코드','종목명','종가','EPS','PER','BPS','PBR','배당수익률']]

In [ ]:
data

       종목코드       종목명      종가     EPS    PER      BPS   PBR  배당수익률
0    095570   AJ네트웍스     5700     NaN    NaN   6089.0  0.94   3.68
1    006840    AK홀딩스    21300     NaN    NaN  50471.0  0.42   1.88
2    027410      BGF     5220   285.0  18.32  15781.0  0.33   2.11
3    282330   BGF리테일   178000  7103.0  25.06  40317.0  4.42   1.35
4    138930  BNK금융지주     7600  1498.0   5.07  26781.0  0.28   4.21
..      ...       ...     ...     ...    ...      ...   ...    ...
908  069260      휴켐스    21550  1292.0  16.68  16351.0  1.32   4.64
909  000540     흥국화재     3780   268.0  14.10  11107.0  0.34   0.00
910  000547  흥국화재2우B    28400     NaN    NaN      NaN   NaN   0.00
911  000545    흥국화재우     7920     NaN    NaN      NaN   NaN   0.00
912  003280     흥아해운     3230     NaN    NaN      NaN   NaN   0.00

[913 rows x 8 columns]

In [ ]:
jongmok_upjong = pd.read_csv(os.path.join(PATH,'jongmok_upjong_20220314.csv'),encoding='cp949')[['종목코드','종목명','업종명']]

In [ ]:
jongmok_upjong

       종목코드      종목명    업종명
0    095570   AJ네트웍스   서비스업
1    006840    AK홀딩스   기타금융
2    027410      BGF   기타금융
3    282330   BGF리테일    유통업
4    138930  BNK금융지주   기타금융
..      ...      ...    ...
935  069260      휴켐스     화학
936  000540     흥국화재     보험
937  000547  흥국화재2우B     보험
938  000545    흥국화재우     보험
939  003280     흥아해운  운수창고업

[940 rows x 3 columns]

In [ ]:
df_join = pd.merge(left = jongmok_upjong, right=data, on='종목코드',how='left')

In [ ]:
df_join = df_join.drop(columns =['종목명_y'])

In [ ]:
df_join = df_join.rename(columns={'종목명_x':'종목명'})

In [ ]:
upjong_avg = upjong_avg.rename(columns = {'지수명':'업종명'})

In [ ]:
upjong_avg

                  업종명        종가      대비   등락률    PER  선행 PER   PBR  배당수익률
0                 코스피   2661.28  -19.04 -0.71  12.15    0.00  1.08   1.91
1             코스피 200    355.31   -2.70 -0.75  10.82    9.61  1.07   2.26
2             코스피 100   2672.56  -25.34 -0.94  10.81    9.88  1.09   2.33
3              코스피 50   2433.07  -28.67 -1.16  10.48   10.40  1.08   2.37
4        코스피 200 중소형주   1297.73   17.88  1.40  10.76    0.00  0.93   1.28
5    코스피 200 초대형제외 지수    260.42   -0.92 -0.35   9.96    0.00  0.97   1.40
6      코스피200제외 코스피지수   3539.81   27.34  0.78  11.63    0.00  0.85   1.38
7   코스피 200 커뮤니케이션서비스   2589.55    9.63  0.37   9.29    0.00  1.54   1.30
8          코스피 200 건설    306.93    4.97  1.65  13.44    0.00  1.06   1.12
9         코스피 200 중공업    306.46   10.90  3.69   0.00    0.00  1.21   0.66
10      코스피 200 철강/소재    902.07    5.34  0.60   5.72    0.00  0.57   1.78
11     코스피 200 에너지/화학   1608.79  -15.22 -0.94  10.29    0.00  0.99   1.26
12       코스피 200 정보기술   3234.08  -59.73 -1.81  12.65    0.00  1.44   1.59
13         코스피 200 금융    672.41    2.74  0.41   5.13    0.00  0.47   3.34
14      코스피 200 생활소비재    971.54   -1.45 -0.15  14.50    0.00  0.68   2.45
15      코스피 200 경기소비재   1508.71   -8.32 -0.55  10.16    0.00  0.73   1.43
16        코스피 200 산업재    626.23    0.51  0.08  15.81    0.00  1.45   0.78
17       코스피 200 헬스케어   1981.90  -12.18 -0.61  57.71    0.00  4.79   0.20
18               음식료품   3668.87   -5.33 -0.15  14.58    0.00  0.92   1.39
19               섬유의복    461.34   -2.10 -0.45  29.74    0.00  1.49   0.60
20               종이목재    399.94    2.82  0.71  13.32    0.00  0.68   1.50
21                 화학   5413.11  -93.05 -1.69  11.94    0.00  1.10   1.26
22                의약품  15043.18  -88.49 -0.58  76.20    0.00  5.19   0.14
23              비금속광물   2397.13   -1.11 -0.05  22.28    0.00  1.44   2.02
24               철강금속   4754.53   -6.00 -0.13   5.99    0.00  0.56   2.00
25                 기계   1127.97   45.08  4.16  25.26    0.00  1.71   0.76
26               전기전자  25646.72 -615.32 -2.34  15.84    0.00  1.66   2.69
27               의료정밀   3039.42  -68.69 -2.21   9.55    0.00  2.01   0.83
28               운수장비   1853.77   -9.83 -0.53  19.39    0.00  0.71   1.16
29                유통업    370.82    6.43  1.76  10.88    0.00  0.72   1.63
30              전기가스업    874.55    8.19  0.95   0.00    0.00  0.28   3.93
31                건설업    126.25    4.36  3.58  10.81    0.00  0.82   1.48
32              운수창고업   2186.60   31.77  1.47  14.40    0.00  1.51   0.37
33                통신업    414.27    0.76  0.18   6.95    0.00  0.56   4.57
34                금융업    404.87    2.57  0.64   6.09    0.00  0.56   2.75
35                 은행    168.23    2.14  1.29  14.80    0.00  0.95   1.12
36                 증권   1982.27  -20.45 -1.02   4.17    0.00  0.53   3.90
37                 보험  13163.82   67.04  0.51   6.77    0.00  0.44   3.31
38               서비스업   1663.83    7.55  0.46  10.30    0.00  2.38   0.50
39                제조업   6613.47 -101.49 -1.51  15.67    0.00  1.33   1.98
40            코스피 대형주   2614.93  -30.19 -1.14  12.10    0.00  1.16   2.03
41            코스피 중형주   3127.56   40.72  1.32  11.85    0.00  0.90   1.34
42            코스피 소형주   2511.84   30.42  1.23  14.02    0.00  0.70   1.43
43   코스피 200 비중상한 30%    354.67   -2.69 -0.75  10.82    0.00  1.07   2.26
44   코스피 200 비중상한 25%    351.28   -2.52 -0.71  10.73    0.00  1.06   2.17
45   코스피 200 비중상한 20%    341.99   -2.21 -0.64  10.57    0.00  1.04   2.02
46     코스피 200 TOP 10   1277.44  -17.22 -1.33  10.81    0.00  1.52   1.08

In [ ]:
upjong_avg.rename(columns={'PER':'업종PER',
                           'PBR':'업종PBR',
                           '배당수익률':'업종배당수익률'}).columns

Index(['업종명', '종가', '대비', '등락률', '업종PER', '선행 PER', '업종PBR', '업종배당수익률'], dtype='object')

In [ ]:
upjong_avg = upjong_avg.rename(columns={'PER':'업종PER',
                           'PBR':'업종PBR',
                           '배당수익률':'업종배당수익률'})[['업종명', '종가', '업종PER', '업종PBR', '업종배당수익률']]

In [ ]:
join_final = pd.merge(df_join,upjong_avg,how='left',on='업종명')

In [ ]:
join_final.columns

Index(['종목코드', '종목명', '업종명', '종가_x', 'EPS', 'PER', 'BPS', 'PBR', '배당수익률',
       '종가_y', '업종PER', '업종PBR', '업종배당수익률'],
      dtype='object')

In [ ]:
join_final = join_final.rename(columns={'종목명_x':'종목명',
                           '종가_x':'종가',
                           '종가_y':'산업지수'})

In [ ]:
a = join_final.loc[join_final['업종PER']>join_final['PER']]
print(len(a))

191

In [ ]:
a = a.reset_index(drop=True)

In [ ]:
a

,종목코드,종목명,업종명,종가,EPS,PER,BPS,PBR,배당수익률,산업지수,업종PER,업종PBR,업종배당수익률
0,001460,BYC,섬유의복,453000.0,21904.0,20.68,538911.0,0.84,0.24,461.34,29.74,1.49,0.60
1,097950,CJ제일제당,음식료품,342500.0,42783.0,8.01,321970.0,1.06,1.17,3668.87,14.58,0.92,1.39
2,016610,DB금융투자,증권,6350.0,2327.0,2.73,18855.0,0.34,4.72,1982.27,4.17,0.53,3.90
3,005830,DB손해보험,보험,57700.0,9171.0,6.29,90596.0,0.64,3.81,13163.82,6.77,0.44,3.31
4,001880,DL건설,건설업,30100.0,7953.0,3.78,34403.0,0.87,1.83,126.25,10.81,0.82,1.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,002460,화성산업,건설업,19800.0,2742.0,7.22,31644.0,0.63,3.28,126.25,10.81,0.82,1.48
187,006060,화승인더,화학,5160.0,698.0,7.39,6374.0,0.81,3.64,5413.11,11.94,1.10,1.26
188,000850,화천기공,기계,31700.0,2053.0,15.44,134620.0,0.24,2.37,1127.97,25.26,1.71,0.76
189,016580,환인제약,의약품,17700.0,1532.0,11.55,15920.0,1.11,1.69,15043.18,76.20,5.19,0.14
190,079980,휴비스,화학,7010.0,2497.0,2.81,13659.0,0.51,4.28,5413.11,11.94,1.10,1.26

#2019년 기준+ 코스피 200

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [ ]:
ls -al ../gdrive/MyDrive/stock/

total 719
drwx------ 2 root root   4096 Mar 25 06:16 재무제표/
-rw------- 1 root root  86539 Mar 26 03:02 2021_12_30_prices.xlsx
drwx------ 2 root root   4096 Mar 30 07:23 dividend/
-rw------- 1 root root  56731 Mar 24 04:30 final_result.csv
-rw------- 1 root root  11139 Mar 15 07:22 kospi_200_20190102.csv
-rw------- 1 root root  10947 Mar 30 09:50 kospi_200_prices_201701.csv
-rw------- 1 root root  10878 Mar 30 09:35 kospi_200_prices_201801.csv
-rw------- 1 root root  11139 Mar 30 09:37 kospi_200_prices_201901.csv
-rw------- 1 root root  14025 Mar 30 06:27 kospi_200_prices_2020_01.xlsx
-rw------- 1 root root   2831 Mar 15 01:08 kospi_avg_upjong_20190102.csv
-rw------- 1 root root 175683 Mar 15 01:05 kospi_data_20190102.csv
-rw------- 1 root root  14014 Mar 31 00:42 prices_2014_01.xlsx
-rw------- 1 root root  13928 Mar 31 00:41 prices_2015_01.xlsx
-rw------- 1 root root  14005 Mar 31 00:41 prices_2016_01.xlsx
-rw------- 1 root root  13992 Mar 31 00:40 prices_2017_01.xlsx
-rw------- 1 root root  13931 Mar 30 06:15 prices_2018_01.xlsx
-rw------- 1 root root  82845 Mar 30 06:04 prices_2019_01.xlsx
-rw------- 1 root root  84053 Mar 30 05:23 prices_2020_01.xlsx
-rw------- 1 root root  11069 Mar 30 06:50 prices_2021_01.csv
-rw------- 1 root root  14106 Mar 31 01:23 prices_2021_01.xlsx
-rw------- 1 root root  80520 Mar 31 06:27 prices_2022_01.xlsx

In [ ]:
# 업종 및 업종 평균 PER, PBR 가져오기
PATH = '../gdrive/MyDrive/stock/'
df_2019_upjong = pd.read_csv(os.path.join(PATH, 'kospi_avg_upjong_20190102.csv'),encoding='cp949')
df_2019_upjong = df_2019_upjong[['지수명', 'PER', 'PBR', '배당수익률']]
df_2019_upjong = df_2019_upjong.rename(columns = {'지수명':'업종명',
                                 'PER':'업종PER',
                                 'PBR':'업종PBR',
                                 '배당수익률':'업종배당수익률'})

In [ ]:
# 종목 PER, PBR 가져오기
df_2019_jongmok = pd.read_csv(os.path.join(PATH,'kospi_data_20190102.csv'),encoding='cp949')
df_2019_jongmok = df_2019_jongmok[['종목코드', '종목명', '종가','EPS', 'PER',
       'BPS', 'PBR','배당수익률']]

In [ ]:
df_2019_upjong

                  업종명  업종PER  업종PBR  업종배당수익률
0                 코스피   9.44   0.85     1.96
1             코스피 200   8.41   0.86     2.04
2             코스피 100   8.14   0.85     2.11
3              코스피 50   7.90   0.85     2.16
4        코스피 200 중소형주  13.68   1.06     1.23
5    코스피 200 초대형제외 지수  10.15   0.83     1.98
6   코스피 200 커뮤니케이션서비스  15.21   1.41     1.72
7          코스피 200 건설   9.33   0.88     1.27
8         코스피 200 중공업   0.00   0.81     0.23
9       코스피 200 철강/소재  18.89   0.49     2.30
10     코스피 200 에너지/화학   6.78   0.92     2.91
11       코스피 200 정보기술   6.91   0.98     1.40
12         코스피 200 금융   6.64   0.54     3.60
13      코스피 200 생활소비재  19.11   0.90     1.60
14      코스피 200 경기소비재  14.30   0.64     2.26
15        코스피 200 산업재  18.77   1.13     1.46
16       코스피 200 헬스케어  61.20   3.69     0.28
17               음식료품  10.99   1.13     1.21
18               섬유의복   6.41   0.65     1.32
19               종이목재  16.11   0.61     1.53
20                 화학   9.91   1.15     2.09
21                의약품  89.40   4.62     0.19
22              비금속광물  14.10   0.94     2.46
23               철강금속  10.50   0.50     2.52
24                 기계  70.41   1.17     1.41
25               전기전자   5.49   0.98     1.93
26               의료정밀   5.22   1.11     0.78
27               운수장비  51.34   0.53     1.77
28                유통업   9.30   0.84     1.47
29              전기가스업   0.00   0.34     2.03
30                건설업  12.79   0.84     1.05
31              운수창고업  25.71   1.07     1.03
32                통신업   8.89   0.92     2.94
33                금융업   7.42   0.62     2.94
34                 은행   5.51   0.42     4.14
35                 증권   7.49   0.55     3.12
36                 보험  10.41   0.66     3.21
37               서비스업  24.80   2.10     1.25
38                제조업   8.74   0.94     1.77
39            코스피 대형주   8.78   0.86     2.07
40            코스피 중형주  11.86   0.88     1.52
41            코스피 소형주  23.60   0.67     1.45

In [ ]:
ls -al ../gdrive/MyDrive/practice/jongmok_upjong_20220314.csv

-rw------- 1 root root 70469 Mar 14 01:14 ../gdrive/MyDrive/practice/jongmok_upjong_20220314.csv

In [ ]:

upjong_upjong = pd.read_csv('../gdrive/MyDrive/practice/jongmok_upjong_20220314.csv',encoding='cp949')[['종목코드','종목명','업종명','시가총액']]
upjong_upjong

       종목코드      종목명    업종명           시가총액
0    095570   AJ네트웍스   서비스업   265482412650
1    006840    AK홀딩스   기타금융   282835427350
2    027410      BGF   기타금융   500598816930
3    282330   BGF리테일    유통업  3024683550000
4    138930  BNK금융지주   기타금융  2477107869600
..      ...      ...    ...            ...
935  069260      휴켐스     화학   885021430200
936  000540     흥국화재     보험   242194771650
937  000547  흥국화재2우B     보험     4331520000
938  000545    흥국화재우     보험     6144000000
939  003280     흥아해운  운수창고업   764551178820

[940 rows x 4 columns]

In [ ]:
kospi_200 = pd.read_csv(os.path.join(PATH,'kospi_200_20190102.csv'),encoding='cp949',converters={'종목코드':str})

In [ ]:
kospi_200 = kospi_200[['종목코드','종목명']]

In [ ]:
kospi_200.head()

     종목코드       종목명
0  005930      삼성전자
1  000660    SK하이닉스
2  068270      셀트리온
3  207940  삼성바이오로직스
4  005380       현대차

In [ ]:
df_2019_upjong.head()

            업종명  업종PER  업종PBR  업종배당수익률
0           코스피   9.44   0.85     1.96
1       코스피 200   8.41   0.86     2.04
2       코스피 100   8.14   0.85     2.11
3        코스피 50   7.90   0.85     2.16
4  코스피 200 중소형주  13.68   1.06     1.23

In [ ]:
upjong_upjong

       종목코드      종목명    업종명           시가총액
0    095570   AJ네트웍스   서비스업   265482412650
1    006840    AK홀딩스   기타금융   282835427350
2    027410      BGF   기타금융   500598816930
3    282330   BGF리테일    유통업  3024683550000
4    138930  BNK금융지주   기타금융  2477107869600
..      ...      ...    ...            ...
935  069260      휴켐스     화학   885021430200
936  000540     흥국화재     보험   242194771650
937  000547  흥국화재2우B     보험     4331520000
938  000545    흥국화재우     보험     6144000000
939  003280     흥아해운  운수창고업   764551178820

[940 rows x 4 columns]

In [ ]:
join_t1 = pd.merge(kospi_200,upjong_upjong, how='left',on='종목코드')
join_t1 = join_t1[['종목코드','종목명_x','업종명']]

In [ ]:
join_t2 = pd.merge(join_t1, df_2019_upjong, how='left', on ='업종명')
join_t2

       종목코드     종목명_x   업종명  업종PER  업종PBR  업종배당수익률
0    005930      삼성전자  전기전자   5.49   0.98     1.93
1    000660    SK하이닉스  전기전자   5.49   0.98     1.93
2    068270      셀트리온   의약품  89.40   4.62     0.19
3    207940  삼성바이오로직스   의약품  89.40   4.62     0.19
4    005380       현대차  운수장비  51.34   0.53     1.77
..      ...       ...   ...    ...    ...      ...
196  034120       SBS  서비스업  24.80   2.10     1.25
197  064960    S&T모티브  운수장비  51.34   0.53     1.77
198  033920        무학  음식료품  10.99   1.13     1.21
199  036580       팜스코  음식료품  10.99   1.13     1.21
200  097230     한진중공업   건설업  12.79   0.84     1.05

[201 rows x 6 columns]

In [ ]:
join_t3 = pd.merge(join_t2, df_2019_jongmok, how='left',on = '종목코드')
join_t3 = join_t3.drop(columns='종목명')
join_t3 = join_t3.rename(columns = {'종목명_x' : '종목명'})

In [ ]:
join_t3

,종목코드,종목명,업종명,업종PER,업종PBR,업종배당수익률,종가,EPS,PER,BPS,PBR,배당수익률
0,005930,삼성전자,전기전자,5.49,0.98,1.93,38750,5997.0,6.46,28126.0,1.38,2.19
1,000660,SK하이닉스,전기전자,5.49,0.98,1.93,60600,15073.0,4.02,46449.0,1.30,1.65
2,068270,셀트리온,의약품,89.40,4.62,0.19,214500,3150.0,68.10,19041.0,11.27,0.00
3,207940,삼성바이오로직스,의약품,89.40,4.62,0.19,374000,NaN,NaN,60099.0,6.22,0.00
4,005380,현대차,운수장비,51.34,0.53,1.77,114000,14993.0,7.60,242062.0,0.47,3.51
...,...,...,...,...,...,...,...,...,...,...,...,...
196,034120,SBS,서비스업,24.80,2.10,1.25,21100,850.0,24.82,30428.0,0.69,1.18
197,064960,S&T모티브,운수장비,51.34,0.53,1.77,27400,3888.0,7.05,49272.0,0.56,3.65
198,033920,무학,음식료품,10.99,1.13,1.21,13550,1839.0,7.37,18800.0,0.72,2.58
199,036580,팜스코,음식료품,10.99,1.13,1.21,7530,1111.0,6.78,8600.0,0.88,1.33
200,097230,한진중공업,건설업,12.79,0.84,1.05,1590,NaN,NaN,5449.0,0.29,0.00

### 업종 PER보다 낮은 종목 filtering

In [ ]:
len(join_t3.loc[join_t3['업종PER']>join_t3['PER']])

70

### 업종 PBR보다 낮은 종목 filtering

In [ ]:
join_t3.loc[join_t3['업종PBR']>join_t3['PBR']]

,종목코드,종목명,업종명,업종PER,업종PBR,업종배당수익률,종가,EPS,PER,BPS,PBR,배당수익률
4,005380,현대차,운수장비,51.34,0.53,1.77,114000,14993.0,7.60,242062.0,0.47,3.51
7,015760,한국전력,전기가스업,0.00,0.34,2.03,34050,2023.0,16.83,111660.0,0.30,2.32
8,005490,POSCO,철강금속,10.50,0.50,2.52,237000,34464.0,6.88,501600.0,0.47,3.38
16,032830,삼성생명,보험,10.41,0.66,3.21,80300,6494.0,12.37,146795.0,0.55,2.49
18,096770,SK이노베이션,화학,9.91,1.15,2.09,169000,22574.0,7.49,192989.0,0.88,4.73
...,...,...,...,...,...,...,...,...,...,...,...,...
194,014830,유니드,화학,9.91,1.15,2.09,41800,4454.0,9.38,73283.0,0.57,2.63
196,034120,SBS,서비스업,24.80,2.10,1.25,21100,850.0,24.82,30428.0,0.69,1.18
198,033920,무학,음식료품,10.99,1.13,1.21,13550,1839.0,7.37,18800.0,0.72,2.58
199,036580,팜스코,음식료품,10.99,1.13,1.21,7530,1111.0,6.78,8600.0,0.88,1.33
200,097230,한진중공업,건설업,12.79,0.84,1.05,1590,NaN,NaN,5449.0,0.29,0.00

## 업종 PER + 업종 PBR 보다 낮은 종목 filtering

In [ ]:
join_t3.loc[(join_t3['업종PER']>join_t3['PER']) & (join_t3['업종PBR']>join_t3['PBR'])]

,종목코드,종목명,업종명,업종PER,업종PBR,업종배당수익률,종가,EPS,PER,BPS,PBR,배당수익률
4,005380,현대차,운수장비,51.34,0.53,1.77,114000,14993.0,7.60,242062.0,0.47,3.51
8,005490,POSCO,철강금속,10.50,0.50,2.52,237000,34464.0,6.88,501600.0,0.47,3.38
18,096770,SK이노베이션,화학,9.91,1.15,2.09,169000,22574.0,7.49,192989.0,0.88,4.73
21,000270,기아차,운수장비,51.34,0.53,1.77,32800,2414.0,13.59,66264.0,0.49,2.44
30,011170,롯데케미칼,화학,9.91,1.15,2.09,275000,65625.0,4.19,335215.0,0.82,3.82
39,035250,강원랜드,서비스업,24.80,2.10,1.25,30900,2159.0,14.31,16365.0,1.89,3.20
40,034220,LG디스플레이,전기전자,5.49,0.98,1.93,17800,5038.0,3.53,40170.0,0.44,2.81
43,004020,현대제철,철강금속,10.50,0.50,2.52,44000,5455.0,8.07,125261.0,0.35,1.70
47,267250,현대중공업지주,화학,9.91,1.15,2.09,337500,74312.0,4.54,459750.0,0.73,0.00
50,139480,이마트,유통업,9.30,0.84,1.47,180000,21621.0,8.33,295657.0,0.61,0.97
51,161390,한국타이어,화학,9.91,1.15,2.09,40750,4837.0,8.42,51331.0,0.79,0.98
64,088350,한화생명,보험,10.41,0.66,3.21,4215,757.0,5.57,10767.0,0.39,3.32
76,009830,한화케미칼,화학,9.91,1.15,2.09,19800,5021.0,3.94,36250.0,0.55,1.77
78,241560,두산밥캣,기계,70.41,1.17,1.41,30700,2725.0,11.27,34190.0,0.90,2.61
79,003490,대한항공,운수창고업,25.71,1.07,1.03,32400,8639.0,3.75,37824.0,0.86,0.77
85,000100,유한양행,의약품,89.40,4.62,0.19,209000,9331.0,22.40,123265.0,1.70,0.96
90,028670,팬오션,운수창고업,25.71,1.07,1.03,4445,268.0,16.59,4469.0,0.99,0.00
92,000880,한화,화학,9.91,1.15,2.09,31000,5619.0,5.52,46382.0,0.67,1.94
99,069620,대웅제약,의약품,89.40,4.62,0.19,185500,3060.0,60.62,44831.0,4.14,0.32
100,069960,현대백화점,유통업,9.30,0.84,1.47,87700,11242.0,7.80,169016.0,0.52,0.91
112,006280,녹십자,의약품,89.40,4.62,0.19,136500,4665.0,29.26,89010.0,1.53,0.92
113,003240,태광산업,화학,9.91,1.15,2.09,1334000,164917.0,8.09,2430678.0,0.55,0.14
115,042670,두산인프라코어,기계,70.41,1.17,1.41,7330,627.0,11.69,7662.0,0.96,0.00
120,000670,영풍,철강금속,10.50,0.50,2.52,736000,142197.0,5.18,1610072.0,0.46,1.36
126,214320,이노션,서비스업,24.80,2.10,1.25,61900,3074.0,20.14,33615.0,1.84,1.62
131,071840,롯데하이마트,유통업,9.30,0.84,1.47,46300,6288.0,7.36,85810.0,0.54,4.00
138,185750,종근당,의약품,89.40,4.62,0.19,100000,5211.0,19.19,38884.0,2.57,0.90
143,002350,넥센타이어,화학,9.91,1.15,2.09,9000,1226.0,7.34,12821.0,0.70,1.11
144,006650,대한유화,화학,9.91,1.15,2.09,147500,34701.0,4.25,226646.0,0.65,2.71
145,010780,아이에스동서,비금속광물,14.10,0.94,2.46,29800,6355.0,4.69,34537.0,0.86,3.69
174,001430,세아베스틸,철강금속,10.50,0.50,2.52,17550,3560.0,4.93,51205.0,0.34,5.13
177,019680,대교,서비스업,24.80,2.10,1.25,6670,466.0,14.31,6440.0,1.04,3.60
184,003850,보령제약,의약품,89.40,4.62,0.19,10050,1334.0,7.53,5662.0,1.77,1.59
186,108670,LG하우시스,화학,9.91,1.15,2.09,56100,6794.0,8.26,98558.0,0.57,3.21
193,003300,한일홀딩스,비금속광물,14.10,0.94,2.46,54700,8669.0,6.31,213895.0,0.26,3.29
194,014830,유니드,화학,9.91,1.15,2.09,41800,4454.0,9.38,73283.0,0.57,2.63
198,033920,무학,음식료품,10.99,1.13,1.21,13550,1839.0,7.37,18800.0,0.72,2.58
199,036580,팜스코,음식료품,10.99,1.13,1.21,7530,1111.0,6.78,8600.0,0.88,1.33

In [ ]:
pd.set_option('display.max_row', None)

In [ ]:
join_t3['종목명']

0            삼성전자
1          SK하이닉스
2            셀트리온
3        삼성바이오로직스
4             현대차
5            LG화학
6           SK텔레콤
7            한국전력
8           POSCO
9            삼성물산
10          NAVER
11           KB금융
12           신한지주
13          현대모비스
14             SK
15         LG생활건강
16           삼성생명
17        삼성에스디에스
18        SK이노베이션
19          삼성SDI
20           KT&G
21            기아차
22           삼성화재
23             LG
24         아모레퍼시픽
25         하나금융지주
26           우리은행
27           LG전자
28          S-Oil
29          엔씨소프트
30          롯데케미칼
31            넷마블
32          현대중공업
33            카카오
34           고려아연
35             KT
36         LG유플러스
37           기업은행
38           삼성전기
39           강원랜드
40        LG디스플레이
41           현대건설
42           롯데지주
43           현대제철
44           롯데쇼핑
45          한온시스템
46           아모레G
47        현대중공업지주
48            코웨이
49           한미약품
50            이마트
51          한국타이어
52         한미사이언스
53         CJ제일제당
54         DB손해보험
55         현대글로비스
56          삼성중공업
57             GS
58            오리온
59         미래에셋대우
60         한국가스공사
61           삼성카드
62            에스원
63         CJ대한통운
64           한화생명
65         대우조선해양
66           현대해상
67         BGF리테일
68         NH투자증권
69        삼성엔지니어링
70             CJ
71           GS건설
72           대림산업
73            KCC
74         한국항공우주
75         한국금융지주
76          한화케미칼
77           쌍용양회
78           두산밥캣
79           대한항공
80          GS리테일
81         현대엘리베이
82           호텔신라
83           삼성증권
84            오뚜기
85           유한양행
86        메리츠종금증권
87           제일기획
88           금호석유
89            OCI
90            팬오션
91            신세계
92             한화
93         현대미포조선
94        BNK금융지주
95           현대로템
96           대우건설
97          포스코대우
98      HDC현대산업개발
99           대웅제약
100         현대백화점
101         LG이노텍
102            두산
103       일진머티리얼즈
104       한올바이오파마
105     한화에어로스페이스
106          영원무역
107            동서
108    한국타이어월드와이드
109            LS
110          한국콜마
111            한샘
112           녹십자
113          태광산업
114            농심
115       두산인프라코어
116         코오롱인더
117         금호타이어
118           GKL
119         한전KPS
120            영풍
121        현대그린푸드
122            만도
123           SKC
124          LS산전
125        SK네트웍스
126           이노션
127          코스맥스
128          부광약품
129         하이트진로
130        녹십자홀딩스
131        롯데하이마트
132         두산중공업
133         현대홈쇼핑
134          롯데칠성
135        오리온홀딩스
136          영진약품
137        롯데정밀화학
138           종근당
139           HDC
140         동원F&B
141           락앤락
142         SPC삼립
143         넥센타이어
144          대한유화
145        아이에스동서
146         동아에스티
147         한솔케미칼
148            한섬
149           휴켐스
150          현대위아
151        JW중외제약
152            대상
153          롯데푸드
154           BGF
155         SK케미칼
156        CJ CGV
157        LIG넥스원
158          한세실업
159         쿠쿠홀딩스
160          한전기술
161         삼양홀딩스
162      동아쏘시오홀딩스
163          동국제강
164            효성
165           빙그레
166            풍산
167         AK홀딩스
168          대덕전자
169        동원시스템즈
170            LF
171            후성
172           에스엘
173          LG상사
174         세아베스틸
175           쌍용차
176           삼양사
177            대교
178          남해화학
179          일양약품
180         DB하이텍
181            동양
182          고려제강
183         한국쉘석유
184          보령제약
185          남양유업
186        LG하우시스
187       SK디스커버리
188          한국단자
189         한라홀딩스
190         현대리바트
191         JW홀딩스
192          세방전지
193         한일홀딩스
194           유니드
195         효성중공업
196           SBS
197        S&T모티브
198            무학
199           팜스코
200         한진중공업
Name: 종목명, dtype: object

In [ ]:
result = pd.read_csv('../gdrive/MyDrive/stock/final_result.csv',index_col=0)

In [ ]:
result = result.reset_index()
result = result.rename(columns = {'index':'종목명'})

In [ ]:
result.loc[result['종목명']=='SNT모티브','종목명'] = 'S&T모티브'

In [ ]:
result.loc[result['종목명']=='포스코','종목명'] = 'POSCO'

In [ ]:
result.loc[result['종목명']=='네이버','종목명'] = 'NAVER'

In [ ]:
result.loc[result['종목명']=='삼성SDS','종목명'] = '삼성에스디에스'

In [ ]:
result.loc[result['종목명']=='한전kps','종목명'] = '한전KPS'

In [ ]:
result.loc[result['종목명']=='기아','종목명'] = '기아차'

In [ ]:
result.loc[result['종목명']=='현대엘리베이터','종목명'] = '현대엘리베이'

## 14,15,16 영업이익 증가 추세의 종목과 그 나머지 종목간 수익률 비교

In [ ]:
#17년도 주가와 18년도 주가를 비교
price_2017 = pd.read_excel('../gdrive/MyDrive/stock/prices_2017_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2017.columns = ['종목코드','종목명','종가_2017']
price_2018 = pd.read_excel('../gdrive/MyDrive/stock/prices_2018_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2018.columns = ['종목코드','종목명','종가_2018']

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
join_t4 = pd.merge(join_t3,result,how='left',on = '종목명')

In [ ]:
join_t5 = pd.merge(price_2017, join_t4,how='left',on = '종목코드')
year_3_going = join_t5[(join_t5['2014영업이익']<join_t5['2015영업이익']) & (join_t5['2015영업이익']<join_t5['2016영업이익'])]
year_3_nogoing_join = pd.merge(year_3_going, price_2018, how='left', on = '종목코드')
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2018']- year_3_nogoing_join['종가_2017'])/year_3_nogoing_join['종가_2017'])*100
year_3_nogoing_join = year_3_nogoing_join.loc[~(year_3_nogoing_join['종목명_x']=='녹십자')]
year_3_nogoing_join = year_3_nogoing_join.loc[~(year_3_nogoing_join['종목명_x']=='대웅제약')]
year_3_nogoing_join = year_3_nogoing_join[~year_3_nogoing_join['종가_2018'].isnull()]
print('14,15,16년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('14,15,16년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

14,15,16년도 매년 영업이익 증가한 기업 갯수 : 50
14,15,16년도 매년 영업이익 증가한 기업의 평균 수익률 : 17.220777449273367

In [ ]:
year_3_going = join_t5[~((join_t5['2014영업이익']<join_t5['2015영업이익']) & (join_t5['2015영업이익']<join_t5['2016영업이익']))]
year_3_nogoing_join = pd.merge(year_3_going, price_2018, how='left', on = '종목코드')
year_3_nogoing_join = year_3_nogoing_join[~year_3_nogoing_join['종가_2018'].isnull()]
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2018']- year_3_nogoing_join['종가_2017'])/year_3_nogoing_join['종가_2017'])*100
print('14,15,16년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('14,15,16년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

14,15,16년도 매년 영업이익 증가한 기업 갯수 : 135
14,15,16년도 매년 영업이익 증가한 기업의 평균 수익률 : 13.851171148348405

## 15,16,17 영업이익 증가 추세의 종목과 그 나머지 종목간 수익률 비교

In [ ]:
#17년도 주가와 18년도 주가를 비교
price_2018 = pd.read_excel('../gdrive/MyDrive/stock/prices_2018_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2018.columns = ['종목코드','종목명','종가_2018']
price_2019 = pd.read_excel('../gdrive/MyDrive/stock/prices_2019_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2019.columns = ['종목코드','종목명','종가_2019']

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
year_3_going = join_t4[(join_t4['2015영업이익']<join_t4['2016영업이익']) & (join_t4['2016영업이익']<join_t4['2017영업이익'])]
year_3_nogoing_join = pd.merge(year_3_going, price_2018, how='left', on = '종목코드')
year_3_nogoing_join = pd.merge(year_3_nogoing_join, price_2019, how='left', on = '종목코드')
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2019']- year_3_nogoing_join['종가_2018'])/year_3_nogoing_join['종가_2018'])*100
year_3_nogoing_join = year_3_nogoing_join[~year_3_nogoing_join['증가율'].isnull()]
print('15,16,17년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('15,16,17년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

15,16,17년도 매년 영업이익 증가한 기업 갯수 : 40
15,16,17년도 매년 영업이익 증가한 기업의 평균 수익률 : -19.20292622709938

In [ ]:
year_3_going = join_t4[~((join_t4['2015영업이익']<join_t4['2016영업이익']) & (join_t4['2016영업이익']<join_t4['2017영업이익']))]
year_3_nogoing_join = pd.merge(year_3_going, price_2018, how='left', on = '종목코드')
year_3_nogoing_join = pd.merge(year_3_nogoing_join, price_2019, how='left', on = '종목코드')
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2019']- year_3_nogoing_join['종가_2018'])/year_3_nogoing_join['종가_2018'])*100
year_3_nogoing_join = year_3_nogoing_join[~year_3_nogoing_join['증가율'].isnull()]
print('15,16,17년도 매년 영업이익 증가한 기업을 제외한 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('15,16,17년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : {}'.format(average_returns))

15,16,17년도 매년 영업이익 증가한 기업을 제외한 갯수 : 154
15,16,17년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : -18.920709658649297

## 16,17,18년치 영업이익 증가 추세의 종목과 그 나머지 종목간 수익률 비교

In [ ]:
#17년도 주가와 18년도 주가를 비교
price_2019 = pd.read_excel('../gdrive/MyDrive/stock/prices_2019_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2019.columns = ['종목코드','종목명','종가_2019']
price_2020 = pd.read_excel('../gdrive/MyDrive/stock/prices_2020_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2020.columns = ['종목코드','종목명','종가_2020']

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
year_3_going = join_t4[(join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, price_2019, how='left', on = '종목코드')#[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join = pd.merge(year_3_going_join, price_2020, how='left', on = '종목코드')
year_3_going_join = year_3_going_join[~((year_3_going_join['종가_2020'].isnull()) | (year_3_going_join['종가_2019'].isnull()))]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가_2019'])/year_3_going_join['종가_2019'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

16,17,18년도 매년 영업이익 증가한 기업 갯수 : 34
16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : 1.67885385264962

In [ ]:
year_3_going = join_t4[~((join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, price_2019, how='left', on = '종목코드')#[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join = pd.merge(year_3_going_join, price_2020, how='left', on = '종목코드')
year_3_going_join = year_3_going_join[~((year_3_going_join['종가_2020'].isnull()) | (year_3_going_join['종가_2019'].isnull()))] #############################
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가_2019'])/year_3_going_join['종가_2019'])*100
print('16,17,18년도 매년 영업이익 증가한 기업을 제외한 기업의 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : {}'.format(average_returns))

16,17,18년도 매년 영업이익 증가한 기업을 제외한 기업의 갯수 : 166
16,17,18년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : -5.099764979339883

## 17,18,19년치 영업이익 증가 추세의 종목과 그 나머지 종목간 수익률 비교

In [ ]:
#17년도 주가와 18년도 주가를 비교
price_2020 = pd.read_excel('../gdrive/MyDrive/stock/prices_2020_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2020.columns = ['종목코드','종목명','종가_2020']
price_2021 = pd.read_excel('../gdrive/MyDrive/stock/prices_2021_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2021.columns = ['종목코드','종목명','종가_2021']

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
year_3_going = join_t4[(join_t4['2017영업이익']<join_t4['2018영업이익']) & (join_t4['2018영업이익']<join_t4['2019영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, price_2020, how='left', on = '종목코드')#[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join = pd.merge(year_3_going_join, price_2021, how='left', on = '종목코드')
year_3_going_join = year_3_going_join[~((year_3_going_join['종가_2021'].isnull()) | (year_3_going_join['종가_2020'].isnull()))]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2021']- year_3_going_join['종가_2020'])/year_3_going_join['종가_2020'])*100
print('17,18,19년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('17,18,19년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

17,18,19년도 매년 영업이익 증가한 기업 갯수 : 34
17,18,19년도 매년 영업이익 증가한 기업의 평균 수익률 : 10.275695763724576

In [ ]:
year_3_going = join_t4[~((join_t4['2017영업이익']<join_t4['2018영업이익']) & (join_t4['2018영업이익']<join_t4['2019영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, price_2020, how='left', on = '종목코드')#[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join = pd.merge(year_3_going_join, price_2021, how='left', on = '종목코드')
year_3_going_join = year_3_going_join[~((year_3_going_join['종가_2021'].isnull()) | (year_3_going_join['종가_2020'].isnull()))]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2021']- year_3_going_join['종가_2020'])/year_3_going_join['종가_2020'])*100
print('17,18,19년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('17,18,19년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

17,18,19년도 매년 영업이익 증가한 기업 갯수 : 139
17,18,19년도 매년 영업이익 증가한 기업의 평균 수익률 : 29.149855827922796

In [ ]:
prices_2021_01 = pd.read_csv('../gdrive/MyDrive/stock/prices_2021_01.csv',encoding='cp949',converters = {'종목코드':str})[['종목코드','종목명','종가']]
prices_2021_01 = prices_2021_01.rename(columns = {'종가':"종가_2021"})
prices_2021_01.head()

     종목코드       종목명  종가_2021
0  005930      삼성전자    83000
1  000660    SK하이닉스   126000
2  051910      LG화학   889000
3  207940  삼성바이오로직스   829000
4  035420     NAVER   293000

In [ ]:
result = pd.read_csv('../gdrive/MyDrive/stock/final_result.csv',index_col=0)
result = result.reset_index()
result = result.rename(columns = {'index':'종목명'})
join_t1 = pd.merge(prices_2020_01, result,how='left',on='종목명')
year_3_going = join_t1[(join_t1['2017영업이익']<join_t1['2018영업이익']) & (join_t1['2018영업이익']<join_t1['2019영업이익'])][['종목코드','종목명','종가']]
year_3_going_join = pd.merge(year_3_going, prices_2021_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '종가', '종가_2021']]
year_3_going_join
year_3_going_join['증가율'] = ((year_3_going_join['종가_2021']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('17,18,19년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('17,18,19년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

NameError: ignored

In [ ]:
year_3_nogoing = join_t1[~((join_t1['2017영업이익']<join_t1['2018영업이익']) & (join_t1['2018영업이익']<join_t1['2019영업이익']))][['종목코드','종목명','종가']]
year_3_nogoing_join = pd.merge(year_3_nogoing, prices_2021_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '종가', '종가_2021']]
year_3_going_join
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2021']- year_3_nogoing_join['종가'])/year_3_nogoing_join['종가'])*100
year_3_nogoing_join = year_3_nogoing_join.loc[~year_3_nogoing_join['증가율'].isnull()] #종가2021이 없는 주식은 제외
print('17,18,19년도 매년 영업이익 증가한 기업을 제외한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('17,18,19년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : {}'.format(average_returns))

In [ ]:
year_3_nogoing_join

In [ ]:
year_3_going = join_t4[(join_t4['2017영업이익']<join_t4['2018영업이익']) & (join_t4['2018영업이익']<join_t4['2019영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

KeyError: ignored

In [ ]:
pd.merge(prices_2020_01, join_t4, how='left',on='종목코드')

In [ ]:
year_3_going = join_t4[(join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

KeyError: ignored

In [ ]:
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

In [ ]:
year_3_nogoing = join_t4[~((join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_nogoing_join = pd.merge(year_3_nogoing, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2020']- year_3_nogoing_join['종가'])/year_3_nogoing_join['종가'])*100
year_3_nogoing_join = year_3_nogoing_join[~year_3_nogoing_join['종가_2020'].isnull()]
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

## 18,19,20년치 영업이익 증가 추세의 종목과 그 나머지 종목간 수익률 비교

In [ ]:
#17년도 주가와 18년도 주가를 비교
price_2021 = pd.read_excel('../gdrive/MyDrive/stock/prices_2021_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2021.columns = ['종목코드','종목명','종가_2021']
price_2022 = pd.read_excel('../gdrive/MyDrive/stock/prices_2022_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2022.columns = ['종목코드','종목명','종가_2022']

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
year_3_going = join_t4[(join_t4['2018영업이익']<join_t4['2019영업이익']) & (join_t4['2019영업이익']<join_t4['2020영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, price_2021, how='left', on = '종목코드')#[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join = pd.merge(year_3_going_join, price_2022, how='left', on = '종목코드')
year_3_going_join = year_3_going_join[~((year_3_going_join['종가_2021'].isnull()) | (year_3_going_join['종가_2022'].isnull()))]
year_3_going_join.loc[year_3_going_join['종목명_x']=='카카오','종가_2021'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='카카오','종가_2021'].values/5
year_3_going_join.loc[year_3_going_join['종목명_x']=='쿠쿠홀딩스','종가_2021'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='쿠쿠홀딩스','종가_2021'].values/5
year_3_going_join['증가율'] = ((year_3_going_join['종가_2022']- year_3_going_join['종가_2021'])/year_3_going_join['종가_2021'])*100
print('18,19,20년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('18,19,20년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

18,19,20년도 매년 영업이익 증가한 기업 갯수 : 27
18,19,20년도 매년 영업이익 증가한 기업의 평균 수익률 : 9.597762441225882

In [ ]:
year_3_going = join_t4[~((join_t4['2018영업이익']<join_t4['2019영업이익']) & (join_t4['2019영업이익']<join_t4['2020영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, price_2021, how='left', on = '종목코드')#[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join = pd.merge(year_3_going_join, price_2022, how='left', on = '종목코드')
year_3_going_join = year_3_going_join[~((year_3_going_join['종가_2021'].isnull()) | (year_3_going_join['종가_2022'].isnull()))]
year_3_going_join.loc[year_3_going_join['종목명_x']=='SK텔레콤','종가_2021'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='SK텔레콤','종가_2021'].values/5
year_3_going_join.loc[year_3_going_join['종목명_x']=='현대중공업지주','종가_2021'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='현대중공업지주','종가_2021'].values/5
year_3_going_join['증가율'] = ((year_3_going_join['종가_2022']- year_3_going_join['종가_2021'])/year_3_going_join['종가_2021'])*100
print('18,19,20년도 매년 영업이익 증가한 기업을 제외한 기업의 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('18,19,20년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : {}'.format(average_returns))

18,19,20년도 매년 영업이익 증가한 기업을 제외한 기업의 갯수 : 146
18,19,20년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : 7.892411065772938

In [ ]:
year_3_going_join

,종목코드,종목명_x,업종명,종가,업종PER,업종PBR,PER,PBR,종목명_y,종가_2021,종목명,종가_2022,증가율
0,005930,삼성전자,전기전자,38750,5.49,0.98,6.46,1.38,삼성전자,83000.0,삼성전자,78600.0,-5.301205
1,000660,SK하이닉스,전기전자,60600,5.49,0.98,4.02,1.30,SK하이닉스,126000.0,SK하이닉스,128500.0,1.984127
2,005380,현대차,운수장비,114000,51.34,0.53,7.60,0.47,현대차,207500.0,현대차,210500.0,1.445783
3,051910,LG화학,화학,337000,9.91,1.15,13.28,1.63,LG화학,889000.0,LG화학,618000.0,-30.483690
4,017670,SK텔레콤,통신업,272500,8.89,0.92,7.45,1.23,SK텔레콤,47400.0,SK텔레콤,57200.0,20.675105
5,015760,한국전력,전기가스업,34050,0.00,0.34,16.83,0.30,한국전력,26900.0,한국전력,22350.0,-16.914498
6,005490,POSCO,철강금속,237000,10.50,0.50,6.88,0.47,POSCO,273000.0,POSCO,280000.0,2.564103
7,028260,삼성물산,유통업,104000,9.30,0.84,26.81,0.88,삼성물산,144000.0,삼성물산,117500.0,-18.402778
8,105560,KB금융,기타금융,45950,NaN,NaN,5.53,0.56,KB금융,42450.0,KB금융,55300.0,30.270907
9,055550,신한지주,기타금융,39400,NaN,NaN,6.44,0.57,신한지주,31550.0,신한지주,37250.0,18.066561
10,012330,현대모비스,운수장비,185000,51.34,0.53,11.17,0.61,현대모비스,287000.0,현대모비스,256500.0,-10.627178
11,034730,SK,기타금융,252000,NaN,NaN,8.40,1.31,SK,249500.0,SK,255500.0,2.404810
12,032830,삼성생명,보험,80300,10.41,0.66,12.37,0.55,삼성생명,78000.0,삼성생명,64500.0,-17.307692
13,018260,삼성에스디에스,서비스업,206000,24.80,2.10,30.05,2.87,삼성에스디에스,186000.0,삼성에스디에스,156500.0,-15.860215
14,096770,SK이노베이션,화학,169000,9.91,1.15,7.49,0.88,SK이노베이션,231000.0,SK이노베이션,248000.0,7.359307
15,006400,삼성SDI,전기전자,210500,5.49,0.98,21.43,1.32,삼성SDI,671000.0,삼성SDI,650000.0,-3.129657
16,000810,삼성화재,보험,264500,10.41,0.66,11.64,1.12,삼성화재,183000.0,삼성화재,204500.0,11.748634
17,003550,LG,기타금융,68100,NaN,NaN,5.00,0.75,LG,96900.0,LG,81000.0,-16.408669
18,090430,아모레퍼시픽,화학,193500,9.91,1.15,33.88,3.22,아모레퍼시픽,203000.0,아모레퍼시픽,168000.0,-17.241379
19,086790,하나금융지주,기타금융,36150,NaN,NaN,5.30,0.45,하나금융지주,33450.0,하나금융지주,42350.0,26.606876
21,066570,LG전자,전기전자,62800,5.49,0.98,6.56,0.86,LG전자,142000.0,LG전자,139500.0,-1.760563
22,010950,S-Oil,화학,91300,9.91,1.15,8.53,1.56,S-Oil,70300.0,S-Oil,85900.0,22.190612
23,036570,엔씨소프트,서비스업,467000,24.80,2.10,22.50,3.77,엔씨소프트,978000.0,엔씨소프트,667000.0,-31.799591
24,011170,롯데케미칼,화학,275000,9.91,1.15,4.19,0.82,롯데케미칼,279500.0,롯데케미칼,217000.0,-22.361360
25,251270,넷마블,서비스업,106000,24.80,2.10,27.12,2.08,넷마블,131000.0,넷마블,127500.0,-2.671756
26,009540,현대중공업,운수장비,125500,51.34,0.53,2.93,0.67,한국조선해양,110000.0,한국조선해양,94000.0,-14.545455
27,030200,KT,통신업,30400,8.89,0.92,15.62,0.68,KT,23800.0,KT,30350.0,27.521008
28,032640,LG유플러스,통신업,17950,8.89,0.92,14.33,1.50,LG유플러스,11850.0,LG유플러스,13650.0,15.189873
29,024110,기업은행,은행,13550,5.51,0.42,6.22,0.45,기업은행,8620.0,기업은행,10350.0,20.069606
30,009150,삼성전기,전기전자,100000,5.49,0.98,46.75,1.83,삼성전기,180000.0,삼성전기,194500.0,8.055556
31,035250,강원랜드,서비스업,30900,24.80,2.10,14.31,1.89,강원랜드,23350.0,강원랜드,24200.0,3.640257
32,034220,LG디스플레이,전기전자,17800,5.49,0.98,3.53,0.44,LG디스플레이,19050.0,LG디스플레이,24700.0,29.658793
33,000720,현대건설,건설업,53100,12.79,0.84,29.34,0.92,현대건설,38250.0,현대건설,46150.0,20.653595
34,004990,롯데지주,기타금융,49950,NaN,NaN,6.55,0.61,롯데지주,35100.0,롯데지주,29850.0,-14.957265
35,004020,현대제철,철강금속,44000,10.50,0.50,8.07,0.35,현대제철,41200.0,현대제철,41550.0,0.849515
36,023530,롯데쇼핑,유통업,202500,9.30,0.84,NaN,0.45,롯데쇼핑,101500.0,롯데쇼핑,86400.0,-14.876847
37,018880,한온시스템,기계,10500,70.41,1.17,19.41,2.83,한온시스템,16500.0,한온시스템,13450.0,-18.484848
38,002790,아모레G,화학,67900,9.91,1.15,27.92,2.01,아모레G,54000.0,아모레G,45000.0,-16.666667
39,267250,현대중공업지주,화학,337500,9.91,1.15,4.54,0.73,현대중공업지주,55300.0,현대중공업지주,53600.0,-3.074141
40,021240,코웨이,서비스업,74400,24.80,2.10,16.59,5.67,코웨이,73200.0,코웨이,73400.0,0.273224
41,128940,한미약품,의약품,450500,89.40,4.62,85.39,7.34,한미약품,357000.0,한미약품,285000.0,-20.168067
42,139480,이마트,유통업,180000,9.30,0.84,8.33,0.61,이마트,151500.0,이마트,150500.0,-0.660066
43,161390,한국타이어,화학,40750,9.91,1.15,8.42,0.79,한국타이어앤테크놀로지,37400.0,한국타이어앤테크놀로지,40950.0,9.491979
44,008930,한미사이언스,기타금융,78100,NaN,NaN,163.05,7.59,한미사이언스,76000.0,한미사이언스,55500.0,-26.973684
45,005830,DB손해보험,보험,69500,10.41,0.66,6.65,1.06,DB손해보험,42750.0,DB손해보험,54000.0,26.315789
46,086280,현대글로비스,운수창고업,125500,25.71,1.07,6.92,1.18,현대글로비스,190000.0,현대글로비스,172500.0,-9.210526
47,010140,삼성중공업,운수장비,7240,51.34,0.53,NaN,0.55,삼성중공업,7300.0,삼성중공업,5680.0,-22.191781
48,078930,GS,기타금융,48500,NaN,NaN,4.66,0.59,GS,37800.0,GS,39400.0,4.232804
49,006800,미래에셋대우,증권,6370,7.49,0.55,6.90,0.60,미래에셋대우,9500.0,미래에셋증권,8550.0,-10.000000
50,036460,한국가스공사,전기가스업,46350,0.00,0.34,NaN,0.55,한국가스공사,30800.0,한국가스공사,38350.0,24.512987
51,029780,삼성카드,기타금융,34700,NaN,NaN,9.84,0.58,삼성카드,31250.0,삼성카드,31300.0,0.160000
52,012750,에스원,서비스업,103000,24.80,2.10,24.30,3.24,에스원,85100.0,에스원,73800.0,-13.278496
53,088350,한화생명,보험,4215,10.41,0.66,5.57,0.39,한화생명,2340.0,한화생명,2920.0,24.786325
54,042660,대우조선해양,운수장비,33300,51.34,0.53,4.66,1.05,대우조선해양,27850.0,대우조선해양,22950.0,-17.594255
55,001450,현대해상,보험,39850,10.41,0.66,6.84,1.15,현대해상,22400.0,현대해상,23450.0,4.687500
56,282330,BGF리테일,유통업,205500,9.30,0.84,126.93,9.14,BGF리테일,132000.0,BGF리테일,143500.0,8.712121
57,005940,NH투자증권,증권,12350,7.49,0.55,10.56,0.77,NH투자증권,11200.0,NH투자증권,12200.0,8.928571
58,028050,삼성엔지니어링,서비스업,17450,24.80,2.10,NaN,3.33,삼성엔지니어링,13500.0,삼성엔지니어링,22900.0,69.629630
59,001040,CJ,기타금융,116000,NaN,NaN,7.55,0.98,CJ,92100.0,CJ,84000.0,-8.794788
60,006360,GS건설,건설업,42150,12.79,0.84,NaN,0.95,GS건설,38050.0,GS건설,40050.0,5.256242
61,000210,대림산업,기타금융,96400,NaN,NaN,7.59,0.73,대림산업,83000.0,DL,61400.0,-26.024096
62,002380,KCC,화학,308500,9.91,1.15,72.61,0.56,KCC,199000.0,KCC,309000.0,55.276382
63,047810,한국항공우주,운수장비,32500,51.34,0.53,NaN,2.78,한국항공우주,26900.0,한국항공우주,32900.0,22.304833
64,071050,한국금융지주,기타금융,56900,NaN,NaN,6.52,0.91,한국금융지주,82300.0,한국금융지주,79800.0,-3.037667
65,009830,한화케미칼,화학,19800,9.91,1.15,3.94,0.55,한화솔루션,49200.0,한화솔루션,35550.0,-27.743902
66,003410,쌍용양회,비금속광물,6110,14.10,0.94,9.79,1.58,쌍용양회,6580.0,쌍용C&E,7690.0,16.869301
67,241560,두산밥캣,기계,30700,70.41,1.17,11.27,0.90,두산밥캣,29400.0,두산밥캣,40600.0,38.095238
68,003490,대한항공,운수창고업,32400,25.71,1.07,3.75,0.86,대한항공,27650.0,대한항공,29500.0,6.690778
69,017800,현대엘리베이,기계,103500,70.41,1.17,27.23,3.05,현대엘리베이,40900.0,현대엘리베이,41150.0,0.611247
70,008770,호텔신라,유통업,73100,9.30,0.84,109.60,4.38,호텔신라,82600.0,호텔신라,78200.0,-5.326877
71,016360,삼성증권,증권,31250,7.49,0.55,9.97,0.63,삼성증권,40800.0,삼성증권,44200.0,8.333333
72,007310,오뚜기,음식료품,716000,10.99,1.13,18.15,2.24,오뚜기,567000.0,오뚜기,451500.0,-20.370370
73,000100,유한양행,의약품,209000,89.40,4.62,22.40,1.70,유한양행,79200.0,유한양행,63400.0,-19.949495
74,008560,메리츠종금증권,증권,4075,7.49,0.55,6.43,0.91,메리츠증권,3615.0,메리츠증권,5180.0,43.291840
75,030000,제일기획,서비스업,22300,24.80,2.10,17.77,3.03,제일기획,20250.0,제일기획,22450.0,10.864198
76,011780,금호석유,화학,84400,9.91,1.15,11.04,1.53,금호석유,151000.0,금호석유,167000.0,10.596026
77,010060,OCI,화학,106500,9.91,1.15,10.81,0.76,OCI,98500.0,OCI,103500.0,5.076142
78,004170,신세계,유통업,248000,9.30,0.84,13.38,0.71,신세계,238500.0,신세계,253000.0,6.079665
79,000880,한화,화학,31000,9.91,1.15,5.52,0.67,한화,29350.0,한화,31450.0,7.155026
80,010620,현대미포조선,운수장비,58800,51.34,0.53,5.35,1.06,현대미포조선,48250.0,현대미포조선,70000.0,45.077720
81,138930,BNK금융지주,기타금융,7000,NaN,NaN,5.83,0.32,BNK금융지주,5560.0,BNK금융지주,8390.0,50.899281
82,064350,현대로템,운수장비,26750,51.34,0.53,NaN,1.69,현대로템,19650.0,현대로템,21250.0,8.142494
83,047040,대우건설,건설업,5440,12.79,0.84,8.63,1.01,대우건설,5150.0,대우건설,5870.0,13.980583
84,047050,포스코대우,유통업,17600,9.30,0.84,12.19,0.77,포스코인터내셔널,14550.0,포스코인터내셔널,22500.0,54.639175
85,069620,대웅제약,의약품,185500,89.40,4.62,60.62,4.14,대웅제약,172000.0,대웅제약,151500.0,-11.918605
86,069960,현대백화점,유통업,87700,9.30,0.84,7.80,0.52,현대백화점,72000.0,현대백화점,74700.0,3.750000
87,000150,두산,서비스업,104500,24.80,2.10,54.74,1.04,두산,52000.0,두산,123000.0,136.538462
88,020150,일진머티리얼즈,전기전자,39400,5.49,0.98,38.40,3.42,일진머티리얼즈,52500.0,일진머티리얼즈,131500.0,150.476190
89,009420,한올바이오파마,의약품,34950,89.40,4.62,306.58,16.42,한올바이오파마,37550.0,한올바이오파마,21550.0,-42.609854
90,026960,동서,유통업,17650,9.30,0.84,14.31,1.44,동서,33800.0,동서,30550.0,-9.615385
91,000240,한국타이어월드와이드,기타금융,16850,NaN,NaN,9.11,0.54,한국테크놀로지그룹,14400.0,한국앤컴퍼니,15550.0,7.986111
92,006260,LS,기타금융,48600,NaN,NaN,4.55,0.57,LS,72500.0,LS,54500.0,-24.827586
93,009240,한샘,유통업,67700,9.30,0.84,12.51,3.14,한샘,105500.0,한샘,93300.0,-11.563981
94,006280,녹십자,의약품,136500,89.40,4.62,29.26,1.53,녹십자,475000.0,녹십자,224000.0,-52.842105
95,003240,태광산업,화학,1334000,9.91,1.15,8.09,0.55,태광산업,802000.0,태광산업,1029000.0,28.304239
96,004370,농심,음식료품,251000,10.99,1.13,16.01,0.83,농심,296500.0,농심,316000.0,6.576728
97,042670,두산인프라코어,기계,7330,70.41,1.17,11.69,0.96,두산인프라코어,7910.0,현대두산인프라코어,6990.0,-11.630847
98,120110,코오롱인더,화학,56600,9.91,1.15,11.72,0.74,코오롱인더,41350.0,코오롱인더,71500.0,72.914148
99,073240,금호타이어,화학,5200,9.91,1.15,NaN,0.86,금호타이어,3710.0,금호타이어,4505.0,21.428571
100,114090,GKL,서비스업,23950,24.80,2.10,18.39,2.78,GKL,16450.0,GKL,13200.0,-19.756839
101,051600,한전KPS,건설업,32400,12.79,0.84,10.72,1.61,한전KPS,29200.0,한전KPS,38500.0,31.849315
102,000670,영풍,철강금속,736000,10.50,0.50,5.18,0.46,영풍,540000.0,영풍,653000.0,20.925926
103,005440,현대그린푸드,유통업,14300,9.30,0.84,11.01,0.83,현대그린푸드,8760.0,현대그린푸드,8520.0,-2.739726
104,204320,만도,운수장비,28850,51.34,0.53,282.84,1.00,만도,62700.0,만도,62900.0,0.318979
105,011790,SKC,화학,35450,9.91,1.15,11.42,0.92,SKC,101500.0,SKC,169500.0,66.995074
106,010120,LS산전,전기전자,47400,5.49,0.98,13.23,1.24,LS ELECTRIC,65000.0,LS ELECTRIC,55600.0,-14.461538
107,001740,SK네트웍스,유통업,5180,9.30,0.84,38.09,0.54,SK네트웍스,5040.0,SK네트웍스,4960.0,-1.587302
108,214320,이노션,서비스업,61900,24.80,2.10,20.14,1.84,이노션,60900.0,이노션,54400.0,-10.673235
109,003000,부광약품,의약품,24800,89.40,4.62,131.91,7.44,부광약품,28950.0,부광약품,12950.0,-55.267703
110,000080,하이트진로,음식료품,16300,10.99,1.13,89.56,0.95,하이트진로,32000.0,하이트진로,30250.0,-5.468750
111,005250,녹십자홀딩스,서비스업,24400,24.80,2.10,25.55,1.49,녹십자홀딩스,53600.0,녹십자홀딩스,27500.0,-48.694030
112,071840,롯데하이마트,유통업,46300,9.30,0.84,7.36,0.54,롯데하이마트,30700.0,롯데하이마트,25000.0,-18.566775
113,034020,두산중공업,기계,9450,70.41,1.17,NaN,0.33,두산중공업,13900.0,두산중공업,20950.0,50.719424
114,005300,롯데칠성,음식료품,1374000,10.99,1.13,12.66,0.92,롯데칠성,107000.0,롯데칠성,131000.0,22.429907
115,003520,영진약품,의약품,5940,89.40,4.62,594.00,9.08,영진약품,7910.0,영진약품,5390.0,-31.858407
116,004000,롯데정밀화학,화학,40450,9.91,1.15,11.55,0.87,롯데정밀화학,55100.0,롯데정밀화학,73000.0,32.486388
117,185750,종근당,의약품,100000,89.40,4.62,19.19,2.57,종근당,232500.0,종근당,109500.0,-52.903226
118,012630,HDC,기타금융,16550,NaN,NaN,2.87,0.42,HDC,11000.0,HDC,10450.0,-5.000000
119,049770,동원F&B,음식료품,279000,10.99,1.13,20.96,1.82,동원F&B,176500.0,동원F&B,194000.0,9.915014
120,115390,락앤락,화학,20050,9.91,1.15,31.13,1.73,락앤락,10100.0,락앤락,12150.0,20.297030
121,005610,SPC삼립,음식료품,125500,10.99,1.13,26.79,3.87,SPC삼립,70300.0,SPC삼립,71000.0,0.995733
122,002350,넥센타이어,화학,9000,9.91,1.15,7.34,0.70,넥센타이어,6100.0,넥센타이어,6950.0,13.934426
123,006650,대한유화,화학,147500,9.91,1.15,4.25,0.65,대한유화,234000.0,대한유화,180500.0,-22.863248
124,010780,아이에스동서,비금속광물,29800,14.10,0.94,4.69,0.86,아이에스동서,54600.0,아이에스동서,45350.0,-16.941392
126,020000,한섬,섬유의복,36300,6.41,0.65,14.81,0.97,한섬,30550.0,한섬,35950.0,17.675941
127,069260,휴켐스,화학,23400,9.91,1.15,7.84,1.65,휴켐스,26600.0,휴켐스,22800.0,-14.285714
128,011210,현대위아,운수장비,35600,51.34,0.53,NaN,0.31,현대위아,69500.0,현대위아,80500.0,15.827338
129,001060,JW중외제약,의약품,41000,89.40,4.62,NaN,3.33,JW중외제약,36200.0,JW중외제약,23100.0,-36.187845
132,285130,SK케미칼,화학,69700,9.91,1.15,NaN,1.30,SK케미칼,396000.0,SK케미칼,148500.0,-62.500000
133,079160,CJ CGV,서비스업,40300,24.80,2.10,NaN,2.77,CJ CGV,26200.0,CJ CGV,25150.0,-4.007634
134,079550,LIG넥스원,기계,38250,70.41,1.17,NaN,1.39,LIG넥스원,30700.0,LIG넥스원,69100.0,125.081433
135,105630,한세실업,섬유의복,19700,6.41,0.65,17.91,1.66,한세실업,16750.0,한세실업,21900.0,30.746269
136,052690,한전기술,서비스업,20750,24.80,2.10,37.19,1.74,한전기술,18100.0,한전기술,88200.0,387.292818
137,000070,삼양홀딩스,기타금융,78200,NaN,NaN,16.05,0.50,삼양홀딩스,73800.0,삼양홀딩스,97300.0,31.842818
139,004800,효성,기타금융,47950,NaN,NaN,4.14,0.39,효성,75400.0,효성,93000.0,23.342175
140,005180,빙그레,음식료품,71100,10.99,1.13,21.23,1.32,빙그레,57100.0,빙그레,53000.0,-7.180385
141,103140,풍산,철강금속,26550,10.50,0.50,4.94,0.57,풍산,28200.0,풍산,31700.0,12.411348
144,014820,동원시스템즈,화학,27250,9.91,1.15,9.88,1.82,동원시스템즈,37450.0,동원시스템즈,50300.0,34.312417
146,093370,후성,화학,7090,9.91,1.15,22.16,3.71,후성,12350.0,후성,22750.0,84.210526
147,001120,LG상사,유통업,15350,9.30,0.84,9.86,0.50,LG상사,26750.0,LX인터내셔널,26400.0,-1.308411
150,145990,삼양사,음식료품,54700,10.99,1.13,15.44,0.54,삼양사,60000.0,삼양사,62500.0,4.166667
153,007570,일양약품,의약품,27200,89.40,4.62,NaN,2.72,일양약품,63400.0,일양약품,28350.0,-55.283912
154,000990,DB하이텍,전기전자,10500,5.49,0.98,4.12,1.03,DB하이텍,51100.0,DB하이텍,76900.0,50.489237
159,108670,LG하우시스,화학,56100,9.91,1.15,8.26,0.57,LG하우시스,78700.0,LX하우시스,62500.0,-20.584498
160,006120,SK디스커버리,기타금융,25600,NaN,NaN,0.84,0.29,SK디스커버리,66100.0,SK디스커버리,46350.0,-29.878971
165,004490,세방전지,전기전자,35500,5.49,0.98,7.33,0.56,세방전지,75000.0,세방전지,76000.0,1.333333

## 16,17,18년치 영업이익 증가추세만 필터링

In [ ]:
join_t4[(join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익'])]

,종목코드,종목명,업종명,업종PER,업종PBR,업종배당수익률,종가,EPS,PER,BPS,...,2014당기순이익,2013매출액,2013영업이익,2013당기순이익,2012매출액,2012영업이익,2012당기순이익,2021매출액,2021영업이익,2021당기순이익
0,005930,삼성전자,전기전자,5.49,0.98,1.93,38750,5997.0,6.46,28126.0,...,23394358000000,2.286927e+14,3.678501e+13,30474764000000,NaN,NaN,NaN,2.796048e+14,5.163386e+13,3.990745e+13
1,000660,SK하이닉스,전기전자,5.49,0.98,1.93,60600,15073.0,4.02,46449.0,...,582424000000,1.416510e+13,8.864587e+12,505870000000,1.016221e+13,8.550989e+12,62910000000,NaN,NaN,NaN
8,005490,POSCO,철강금속,10.50,0.50,2.52,237000,34464.0,6.88,501600.0,...,556659145957,6.186465e+13,2.996134e+12,1355180337664,NaN,NaN,NaN,7.633235e+13,9.238089e+12,7.195890e+12
9,028260,삼성물산,유통업,9.30,0.84,1.47,104000,3879.0,26.81,117902.0,...,455072359783,3.226059e+12,1.110928e+11,45192147862,NaN,NaN,NaN,3.445518e+13,1.195983e+12,1.829084e+12
15,051900,LG생활건강,화학,9.91,1.15,2.09,1081000,36199.0,29.86,169155.0,...,354564706876,4.326255e+12,4.964117e+11,365652540664,3.896218e+12,4.455311e+11,311987779732,NaN,NaN,NaN
17,018260,삼성에스디에스,서비스업,24.80,2.10,1.25,206000,6856.0,30.05,71833.0,...,434272525474,7.046833e+12,5.056289e+11,325982504939,NaN,NaN,NaN,1.363000e+13,8.080978e+11,6.333814e+11
19,006400,삼성SDI,전기전자,5.49,0.98,1.93,210500,9824.0,21.43,159945.0,...,-80314437457,5.016465e+12,-2.739436e+10,147915701017,NaN,NaN,NaN,1.355322e+13,1.067576e+12,1.250402e+12
27,066570,LG전자,전기전자,5.49,0.98,1.93,62800,9579.0,6.56,73129.0,...,501357000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,036570,엔씨소프트,서비스업,24.80,2.10,1.25,467000,20756.0,22.50,124037.0,...,227519296162,7.566557e+11,2.052352e+11,158695768295,7.535200e+11,1.512520e+11,153666725549,NaN,NaN,NaN
38,009150,삼성전기,전기전자,5.49,0.98,1.93,100000,2139.0,46.75,54531.0,...,508911818142,7.126507e+12,5.409685e+11,345692360329,NaN,NaN,NaN,9.675036e+12,1.486873e+12,9.154325e+11
48,021240,코웨이,서비스업,24.80,2.10,1.25,74400,4484.0,16.59,13128.0,...,249668412108,2.118342e+12,3.390323e+11,245074651953,1.992838e+12,2.261465e+11,94042698014,NaN,NaN,NaN
49,128940,한미약품,의약품,89.40,4.62,0.19,450500,5276.0,85.39,61358.0,...,43295070634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,078930,GS,기타금융,NaN,NaN,NaN,48500,10416.0,4.66,81628.0,...,-320729000000,9.583193e+12,5.521300e+11,435199000000,9.715714e+12,6.842690e+11,572919000000,NaN,NaN,NaN
60,036460,한국가스공사,전기가스업,0.00,0.34,2.03,46350,NaN,NaN,84640.0,...,447222938586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,000120,CJ대한통운,운수창고업,25.71,1.07,1.03,166500,1786.0,93.23,103964.0,...,59451739573,3.795045e+12,6.417736e+10,-60061093537,2.627466e+12,1.430275e+11,69571921246,NaN,NaN,NaN
65,042660,대우조선해양,운수장비,51.34,0.53,1.77,33300,7141.0,4.66,31816.0,...,-852747122121,1.458483e+13,-1.010035e+12,-920418515185,NaN,NaN,NaN,4.486586e+12,-1.754651e+12,-1.699829e+12
70,001040,CJ,기타금융,NaN,NaN,NaN,116000,15357.0,7.55,117874.0,...,508633144000,1.885170e+13,7.860670e+11,322608337000,1.762839e+13,1.062972e+12,570256610000,NaN,NaN,NaN
71,006360,GS건설,건설업,12.79,0.84,1.05,42150,NaN,NaN,44190.0,...,-22452682512,9.565758e+12,-9.354505e+11,-827346708179,9.568632e+12,1.760633e+11,94960950724,NaN,NaN,NaN
84,007310,오뚜기,음식료품,10.99,1.13,1.21,716000,39458.0,18.15,319178.0,...,94111327807,1.728175e+12,1.050757e+11,92241259915,1.686638e+12,1.086878e+11,75786100328,NaN,NaN,NaN
87,030000,제일기획,서비스업,24.80,2.10,1.25,22300,1255.0,17.77,7354.0,...,102022308936,2.709281e+12,1.299866e+11,102269218895,NaN,NaN,NaN,3.325712e+12,2.481795e+11,1.675991e+11
88,011780,금호석유,화학,9.91,1.15,2.09,84400,7647.0,11.04,55019.0,...,88334747850,5.132132e+12,1.342290e+11,-42712970928,5.883690e+12,2.238028e+11,126109124946,NaN,NaN,NaN
90,028670,팬오션,운수창고업,25.71,1.07,1.03,4445,268.0,16.59,4469.0,...,786078000000,2.682024e+12,-2.220910e+11,-1909683000000,5.417846e+12,-2.116760e+11,-463951000000,NaN,NaN,NaN
91,004170,신세계,유통업,9.30,0.84,1.47,248000,18530.0,13.38,347557.0,...,186056565765,2.441637e+12,3.063899e+11,194652961119,NaN,NaN,NaN,6.316436e+12,5.174006e+11,3.888666e+11
96,047040,대우건설,건설업,12.79,0.84,1.05,5440,630.0,8.63,5396.0,...,102110186625,8.782196e+12,-2.446644e+11,-718036005284,8.223433e+12,3.456866e+11,173028929706,NaN,NaN,NaN
104,009420,한올바이오파마,의약품,89.40,4.62,0.19,34950,114.0,306.58,2129.0,...,-12658084909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,111770,영원무역,유통업,9.30,0.84,1.47,37850,2477.0,15.28,27747.0,...,143317702438,1.108227e+12,1.607880e+11,121929362507,1.059149e+12,1.863027e+11,131669465691,NaN,NaN,NaN
113,003240,태광산업,화학,9.91,1.15,2.09,1334000,164917.0,8.09,2430678.0,...,122820168364,3.513353e+12,1.686005e+11,113939553791,NaN,NaN,NaN,2.591846e+12,3.552726e+11,3.183681e+11
119,051600,한전KPS,건설업,12.79,0.84,1.05,32400,3021.0,10.72,20113.0,...,168295607804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,011790,SKC,화학,9.91,1.15,2.09,35450,3104.0,11.42,38631.0,...,43307997481,2.641403e+12,1.240027e+11,25737659251,2.629171e+12,1.447316e+11,31810661954,NaN,NaN,NaN
132,034020,두산중공업,기계,70.41,1.17,1.41,9450,NaN,NaN,28373.0,...,-85475347180,1.920817e+13,9.580717e+11,18662825932,2.127406e+13,5.861515e+11,97475586606,NaN,NaN,NaN
135,001800,오리온홀딩스,기타금융,NaN,NaN,NaN,16650,39092.0,0.43,29498.0,...,174297158567,2.485196e+12,2.594811e+11,160240858319,NaN,NaN,NaN,2.415059e+12,3.156974e+11,2.253283e+11
137,004000,롯데정밀화학,화학,9.91,1.15,2.09,40450,3503.0,11.55,46229.0,...,58682516778,1.314058e+12,-2.034363e+10,3340492457,NaN,NaN,NaN,1.780293e+12,2.445136e+11,5.854585e+11
145,010780,아이에스동서,비금속광물,14.10,0.94,2.46,29800,6355.0,4.69,34537.0,...,50427361737,6.847643e+11,5.583730e+10,22553869069,6.465883e+11,3.680397e+10,6013758533,NaN,NaN,NaN
159,192400,쿠쿠홀딩스,기타금융,NaN,NaN,NaN,118000,57026.0,2.07,67311.0,...,90732489650,5.087579e+11,6.846339e+10,57439759673,3.067094e+11,3.245852e+10,28870796908,NaN,NaN,NaN

## 14,15,16년치 영업이익 감소추세 종목과 그 나머지 종목간 수익률 비교

In [ ]:
prices_201701 = pd.read_csv('../gdrive/MyDrive/stock/kospi_200_prices_201701.csv',converters= {'종목코드':str},encoding='cp949')
prices_201701 = prices_201701[['종목코드', '종목명', '종가']]

In [ ]:
prices_201801 = pd.read_csv('../gdrive/MyDrive/stock/kospi_200_prices_201801.csv',converters= {'종목코드':str},encoding='cp949')
prices_201801 = prices_201801[['종목코드', '종목명', '종가']]

In [ ]:
year_3_going_join

      종목코드   종목명_x      종가_x    종가_y         증가율
0   000660  SK하이닉스   45800.0   76600   67.248908
1   005380     현대차  150000.0  149500   -0.333333
2   012330   현대모비스  271500.0  257000   -5.340700
3   017670   SK텔레콤  225500.0  265500   17.738359
4   004020    현대제철   58500.0   57200   -2.222222
5   006400   삼성SDI  106000.0  212000  100.000000
6   036460  한국가스공사   48300.0   44350   -8.178054
7   011780    금호석유   85400.0  103500   21.194379
8   047040    대우건설    5120.0    5890   15.039062
9   011070   LG이노텍   85600.0  145000   69.392523
10  011210    현대위아   74200.0   64000  -13.746631
11  001740  SK네트웍스    6930.0    6770   -2.308802
13  004170     신세계  172000.0  290000   68.604651
14  073240   금호타이어    8520.0    4470  -47.535211
15  003000    부광약품   26250.0   23800   -9.333333
16  052690    한전기술   23550.0   23350   -0.849257

In [ ]:
result = pd.read_csv('../gdrive/MyDrive/stock/final_result.csv',index_col=0)
result = result.reset_index()
result = result.rename(columns = {'index':'종목명'})
join_t1 = pd.merge(prices_201701, result,how='left',on='종목명')
year_3_going = join_t1[(join_t1['2014영업이익']>join_t1['2015영업이익']) & (join_t1['2015영업이익']>join_t1['2016영업이익'])][['종목코드','종목명','종가']]
year_3_going_join = pd.merge(year_3_going, prices_201801, how='left', on = '종목코드')[['종목코드', '종목명_x', '종가_x', '종가_y']]
year_3_going_join.loc[year_3_going_join['종목명_x']=='BGF리테일','종가_x'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='BGF리테일','종가_x'].values/5
year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='녹십자')]
year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='대웅제약')]
year_3_going_join['증가율'] = ((year_3_going_join['종가_y']- year_3_going_join['종가_x'])/year_3_going_join['종가_x'])*100
year_3_going_join = year_3_going_join.loc[~year_3_going_join['증가율'].isnull()]
print('15,16,17년도 매년 영업이익 감소추세 기업의 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('15,16,17년도 매년 영업이익 감소추세의 기업의 평균수익률 : {}'.format(average_returns))

15,16,17년도 매년 영업이익 감소추세 기업의 갯수 : 16
15,16,17년도 매년 영업이익 감소추세의 기업의 평균수익률 : 16.8356462611098

In [ ]:
year_3_going = join_t1[~((join_t1['2014영업이익']>join_t1['2015영업이익']) & (join_t1['2015영업이익']>join_t1['2016영업이익']))][['종목코드','종목명','종가']]
year_3_going_join = pd.merge(year_3_going, prices_201801, how='left', on = '종목코드')[['종목코드', '종목명_x', '종가_x', '종가_y']]
# year_3_going_join.loc[year_3_going_join['종목명_x']=='삼성전자','종가_x'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='삼성전자','종가_x'].values/50
# year_3_going_join.loc[year_3_going_join['종목명_x']=='NAVER','종가_x'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='NAVER','종가_x'].values/5
# year_3_going_join.loc[year_3_going_join['종목명_x']=='만도','종가_x'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='만도','종가_x'].values/5
year_3_going_join.loc[year_3_going_join['종목명_x']=='오리온','종가_x'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='오리온','종가_x'].values/10
year_3_going_join.loc[year_3_going_join['종목명_x']=='롯데제과','종가_x'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='롯데제과','종가_x'].values/10
year_3_going_join.loc[year_3_going_join['종목명_x']=='BGF리테일','종가_x'] = year_3_going_join.loc[year_3_going_join['종목명_x']=='BGF리테일','종가_x'].values/5
year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='녹십자')]
year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='대웅제약')]
year_3_going_join['증가율'] = ((year_3_going_join['종가_y']- year_3_going_join['종가_x'])/year_3_going_join['종가_x'])*100
year_3_going_join = year_3_going_join.loc[~year_3_going_join['증가율'].isnull()]
print('15,16,17년도 매년 영업이익 감소추세 기업의 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('15,16,17년도 매년 영업이익 감소추세의 기업의 평균수익률 : {}'.format(average_returns))

15,16,17년도 매년 영업이익 감소추세 기업의 갯수 : 167
15,16,17년도 매년 영업이익 감소추세의 기업의 평균수익률 : 16.2467013560429

In [ ]:
year_3_going = join_t4[(join_t4['2017영업이익']<join_t4['2018영업이익']) & (join_t4['2018영업이익']<join_t4['2019영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

,종목코드,종목명,업종명,업종PER,업종PBR,업종배당수익률,종가,EPS,PER,BPS,...,2014당기순이익,2013매출액,2013영업이익,2013당기순이익,2012매출액,2012영업이익,2012당기순이익,2021매출액,2021영업이익,2021당기순이익
13,012330,현대모비스,운수장비,51.34,0.53,1.77,185000,16558.0,11.17,300935.0,...,3392512000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,051900,LG생활건강,화학,9.91,1.15,2.09,1081000,36199.0,29.86,169155.0,...,354564706876,4.326255e+12,4.964117e+11,365652540664,3.896218e+12,4.455311e+11,311987779732,NaN,NaN,NaN
17,018260,삼성에스디에스,서비스업,24.80,2.10,1.25,206000,6856.0,30.05,71833.0,...,434272525474,7.046833e+12,5.056289e+11,325982504939,NaN,NaN,NaN,1.363000e+13,8.080978e+11,6.333814e+11
21,000270,기아차,운수장비,51.34,0.53,1.77,32800,2414.0,13.59,66264.0,...,2993593000000,4.759790e+13,3.177100e+12,3817059000000,4.724293e+13,3.522251e+12,3864704000000,NaN,NaN,NaN
42,004990,롯데지주,기타금융,NaN,NaN,NaN,49950,7625.0,6.55,81890.0,...,1667068545,1.976367e+12,9.153706e+10,55173479211,1.864493e+12,1.153953e+11,89776244193,NaN,NaN,NaN
49,128940,한미약품,의약품,89.40,4.62,0.19,450500,5276.0,85.39,61358.0,...,43295070634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,097950,CJ제일제당,음식료품,10.99,1.13,1.21,331000,26179.0,12.64,232686.0,...,137851320000,1.084772e+13,3.454790e+11,71061595000,9.877532e+12,6.155287e+11,310715670000,NaN,NaN,NaN
58,271560,오리온,음식료품,10.99,1.13,1.21,111000,1912.0,58.05,33092.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,036460,한국가스공사,전기가스업,0.00,0.34,2.03,46350,NaN,NaN,84640.0,...,447222938586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,000120,CJ대한통운,운수창고업,25.71,1.07,1.03,166500,1786.0,93.23,103964.0,...,59451739573,3.795045e+12,6.417736e+10,-60061093537,2.627466e+12,1.430275e+11,69571921246,NaN,NaN,NaN
69,028050,삼성엔지니어링,서비스업,24.80,2.10,1.25,17450,NaN,NaN,5236.0,...,56353493772,9.806323e+12,-1.028047e+12,-708658932989,NaN,NaN,NaN,7.486696e+12,5.032888e+11,3.510715e+11
70,001040,CJ,기타금융,NaN,NaN,NaN,116000,15357.0,7.55,117874.0,...,508633144000,1.885170e+13,7.860670e+11,322608337000,1.762839e+13,1.062972e+12,570256610000,NaN,NaN,NaN
74,047810,한국항공우주,운수장비,51.34,0.53,1.77,32500,NaN,NaN,11699.0,...,132380000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,007070,GS리테일,유통업,9.30,0.84,1.47,39250,1535.0,25.57,26369.0,...,111280931992,4.708562e+12,1.550498e+11,119046347632,4.377552e+12,1.404741e+11,123458660331,NaN,NaN,NaN
82,008770,호텔신라,유통업,9.30,0.84,1.47,73100,667.0,109.60,16687.0,...,73482881944,NaN,NaN,NaN,NaN,NaN,NaN,3.779129e+12,1.188115e+11,2.705937e+10
87,030000,제일기획,서비스업,24.80,2.10,1.25,22300,1255.0,17.77,7354.0,...,102022308936,2.709281e+12,1.299866e+11,102269218895,NaN,NaN,NaN,3.325712e+12,2.481795e+11,1.675991e+11
90,028670,팬오션,운수창고업,25.71,1.07,1.03,4445,268.0,16.59,4469.0,...,786078000000,2.682024e+12,-2.220910e+11,-1909683000000,5.417846e+12,-2.116760e+11,-463951000000,NaN,NaN,NaN
91,004170,신세계,유통업,9.30,0.84,1.47,248000,18530.0,13.38,347557.0,...,186056565765,2.441637e+12,3.063899e+11,194652961119,NaN,NaN,NaN,6.316436e+12,5.174006e+11,3.888666e+11
104,009420,한올바이오파마,의약품,89.40,4.62,0.19,34950,114.0,306.58,2129.0,...,-12658084909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,111770,영원무역,유통업,9.30,0.84,1.47,37850,2477.0,15.28,27747.0,...,143317702438,1.108227e+12,1.607880e+11,121929362507,1.059149e+12,1.863027e+11,131669465691,NaN,NaN,NaN
110,161890,한국콜마,화학,9.91,1.15,2.09,70000,2240.0,31.25,14458.0,...,32806096793,NaN,NaN,NaN,NaN,NaN,NaN,1.586333e+12,8.426755e+10,4.353483e+10
117,073240,금호타이어,화학,9.91,1.15,2.09,5200,NaN,NaN,6042.0,...,131608463703,3.698542e+12,3.459358e+11,100958039283,4.070644e+12,3.753463e+11,130586236572,NaN,NaN,NaN
119,051600,한전KPS,건설업,12.79,0.84,1.05,32400,3021.0,10.72,20113.0,...,168295607804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,204320,만도,운수장비,51.34,0.53,1.77,28850,102.0,282.84,28786.0,...,47893247651,NaN,NaN,NaN,NaN,NaN,NaN,6.147433e+12,2.323120e+11,1.786158e+11
127,192820,코스맥스,화학,9.91,1.15,2.09,125000,1877.0,66.60,21704.0,...,15756824739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,034020,두산중공업,기계,70.41,1.17,1.41,9450,NaN,NaN,28373.0,...,-85475347180,1.920817e+13,9.580717e+11,18662825932,2.127406e+13,5.861515e+11,97475586606,NaN,NaN,NaN
134,005300,롯데칠성,음식료품,10.99,1.13,1.21,1374000,108521.0,12.66,1497124.0,...,20553075432,2.138971e+12,1.608654e+11,103493317426,NaN,NaN,NaN,2.506093e+12,1.822184e+11,1.370769e+11
135,001800,오리온홀딩스,기타금융,NaN,NaN,NaN,16650,39092.0,0.43,29498.0,...,174297158567,2.485196e+12,2.594811e+11,160240858319,NaN,NaN,NaN,2.415059e+12,3.156974e+11,2.253283e+11
147,014680,한솔케미칼,화학,9.91,1.15,2.09,76300,4893.0,15.59,28396.0,...,21422845255,NaN,NaN,NaN,NaN,NaN,NaN,7.686882e+11,1.976846e+11,1.586709e+11
148,020000,한섬,섬유의복,6.41,0.65,1.32,36300,2451.0,14.81,37575.0,...,36375237191,NaN,NaN,NaN,NaN,NaN,NaN,1.387402e+12,1.521929e+11,1.115236e+11
152,001680,대상,음식료품,10.99,1.13,1.21,24600,1467.0,16.77,24181.0,...,90020443186,2.542303e+12,1.558228e+11,105760974827,NaN,NaN,NaN,3.469993e+12,1.532452e+11,1.449496e+11
159,192400,쿠쿠홀딩스,기타금융,NaN,NaN,NaN,118000,57026.0,2.07,67311.0,...,90732489650,5.087579e+11,6.846339e+10,57439759673,3.067094e+11,3.245852e+10,28870796908,NaN,NaN,NaN
164,004800,효성,기타금융,NaN,NaN,NaN,47950,11575.0,4.14,123059.0,...,291989964756,NaN,NaN,NaN,NaN,NaN,NaN,3.538943e+12,6.405627e+11,5.405865e+11
184,003850,보령제약,의약품,89.40,4.62,0.19,10050,1334.0,7.53,5662.0,...,21590563674,3.272787e+11,1.913676e+10,14126625318,NaN,NaN,NaN,6.272794e+11,4.144823e+10,4.311926e+10

In [ ]:
pd.merge(prices_2020_01, join_t4, how='left',on='종목코드')

,종목코드,종목명_x,종가_x,대비,등락률,상장시가총액,종목명_y,업종명,업종PER,업종PBR,...,2014당기순이익,2013매출액,2013영업이익,2013당기순이익,2012매출액,2012영업이익,2012당기순이익,2021매출액,2021영업이익,2021당기순이익
0,005930,삼성전자,55200.0,-600.0,-1.08,329531997.0,삼성전자,전기전자,5.49,0.98,...,23394358000000,2.286927e+14,3.678501e+13,30474764000000,NaN,NaN,NaN,2.796048e+14,5.163386e+13,3.990745e+13
1,000660,SK하이닉스,94700.0,600.0,0.64,68941824.0,SK하이닉스,전기전자,5.49,0.98,...,582424000000,1.416510e+13,8.864587e+12,505870000000,1.016221e+13,8.550989e+12,62910000000,NaN,NaN,NaN
2,035420,NAVER,182500.0,-4000.0,-2.14,30078445.0,NAVER,서비스업,24.80,2.10,...,451763104000,2.259139e+12,5.065388e+11,1895289315000,NaN,NaN,NaN,6.817600e+12,1.325478e+12,1.647763e+13
3,207940,삼성바이오로직스,428500.0,-4500.0,-1.04,28351703.0,삼성바이오로직스,의약품,89.40,4.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,005380,현대차,118000.0,-2500.0,-2.07,25212846.0,현대차,운수장비,51.34,0.53,...,7649468000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,012330,현대모비스,247500.0,-8500.0,-3.32,23588407.0,현대모비스,운수장비,51.34,0.53,...,3392512000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,068270,셀트리온,180000.0,-1000.0,-0.55,23100814.0,셀트리온,의약품,89.40,4.62,...,NaN,2.262079e+11,9.984543e+10,NaN,NaN,NaN,NaN,1.911601e+12,7.524858e+11,5.914081e+11
7,051910,LG화학,314000.0,-3500.0,-1.10,22165996.0,LG화학,화학,9.91,1.15,...,854025000000,2.314361e+13,1.743044e+12,1270613000000,NaN,NaN,NaN,4.265472e+13,5.025466e+12,3.953904e+12
8,005490,POSCO,236000.0,-500.0,-0.21,20576093.0,POSCO,철강금속,10.50,0.50,...,556659145957,6.186465e+13,2.996134e+12,1355180337664,NaN,NaN,NaN,7.633235e+13,9.238089e+12,7.195890e+12
9,028260,삼성물산,107500.0,-1000.0,-0.92,20391680.0,삼성물산,유통업,9.30,0.84,...,455072359783,3.226059e+12,1.110928e+11,45192147862,NaN,NaN,NaN,3.445518e+13,1.195983e+12,1.829084e+12
10,055550,신한지주,42600.0,-750.0,-1.73,20200902.0,신한지주,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,051900,LG생활건강,1266000.0,5000.0,0.40,19772637.0,LG생활건강,화학,9.91,1.15,...,354564706876,4.326255e+12,4.964117e+11,365652540664,3.896218e+12,4.455311e+11,311987779732,NaN,NaN,NaN
12,105560,KB금융,46550.0,-1100.0,-2.31,19355859.0,KB금융,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,017670,SK텔레콤,234000.0,-4000.0,-1.68,18894496.0,SK텔레콤,통신업,8.89,0.92,...,1799320000000,1.660205e+13,2.011109e+12,1609549000000,1.614141e+13,1.730049e+12,1115663000000,NaN,NaN,NaN
14,015760,한국전력,28500.0,700.0,2.52,18295976.0,한국전력,전기가스업,0.00,0.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,034730,SK,258000.0,-4000.0,-1.53,18152957.0,SK,기타금융,NaN,NaN,...,129898845716,2.301755e+12,2.251929e+11,202347149059,2.241803e+12,2.007273e+11,399619602223,NaN,NaN,NaN
16,000270,기아차,42500.0,-1800.0,-4.06,17227942.0,기아차,운수장비,51.34,0.53,...,2993593000000,4.759790e+13,3.177100e+12,3817059000000,4.724293e+13,3.522251e+12,3864704000000,NaN,NaN,NaN
17,006400,삼성SDI,232000.0,-4000.0,-1.69,15953371.0,삼성SDI,전기전자,5.49,0.98,...,-80314437457,5.016465e+12,-2.739436e+10,147915701017,NaN,NaN,NaN,1.355322e+13,1.067576e+12,1.250402e+12
18,018260,삼성에스디에스,192000.0,-2500.0,-1.29,14856538.0,삼성에스디에스,서비스업,24.80,2.10,...,434272525474,7.046833e+12,5.056289e+11,325982504939,NaN,NaN,NaN,1.363000e+13,8.080978e+11,6.333814e+11
19,032830,삼성생명,73100.0,-1400.0,-1.88,14620000.0,삼성생명,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,096770,SK이노베이션,146500.0,-3500.0,-2.33,13546205.0,SK이노베이션,화학,9.91,1.15,...,-537165529000,6.666952e+13,1.382891e+12,778733149000,7.333001e+13,1.699364e+12,1182351665000,NaN,NaN,NaN
21,035720,카카오,152500.0,-1000.0,-0.65,13147593.0,카카오,서비스업,24.80,2.10,...,149821510168,2.107759e+11,6.585234e+10,61406763238,4.618147e+10,6.979275e+09,5286923426,NaN,NaN,NaN
22,033780,KT&G,92500.0,-1300.0,-1.39,12699556.0,KT&G,기타제조업,NaN,NaN,...,800411845995,3.782630e+12,1.020072e+12,558194389161,3.911818e+12,1.030636e+12,718677658268,NaN,NaN,NaN
23,003550,LG,71100.0,-2700.0,-3.66,12268812.0,LG,기타금융,NaN,NaN,...,834264000000,9.799213e+12,1.153922e+12,830863000000,9.695204e+12,1.231546e+12,961702000000,NaN,NaN,NaN
24,090430,아모레퍼시픽,207500.0,7500.0,3.75,12130137.0,아모레퍼시픽,화학,9.91,1.15,...,385133728193,3.100413e+12,3.698382e+11,267359054309,2.849462e+12,3.653387e+11,269257537859,NaN,NaN,NaN
25,036570,엔씨소프트,541000.0,0.0,0.00,11877126.0,엔씨소프트,서비스업,24.80,2.10,...,227519296162,7.566557e+11,2.052352e+11,158695768295,7.535200e+11,1.512520e+11,153666725549,NaN,NaN,NaN
26,066570,LG전자,71000.0,-1100.0,-1.53,11618995.0,LG전자,전기전자,5.49,0.98,...,501357000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,000810,삼성화재,238500.0,-5000.0,-2.05,11298899.0,삼성화재,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,086790,하나금융지주,35950.0,-950.0,-2.57,10793702.0,하나금융지주,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,010950,S-Oil,91900.0,-3400.0,-3.57,10346359.0,S-Oil,화학,9.91,1.15,...,-287828000000,3.115853e+13,3.660440e+11,289639000000,NaN,NaN,NaN,2.746392e+13,2.140942e+12,1.378541e+12
30,009150,삼성전기,126500.0,1500.0,1.20,9448753.0,삼성전기,전기전자,5.49,0.98,...,508911818142,7.126507e+12,5.409685e+11,345692360329,NaN,NaN,NaN,9.675036e+12,1.486873e+12,9.154325e+11
31,009540,한국조선해양,125500.0,-1000.0,-0.79,8882026.0,현대중공업,운수장비,51.34,0.53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,316140,우리금융지주,11400.0,-200.0,-1.72,8233852.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,010130,고려아연,424000.0,-1000.0,-0.24,8000880.0,고려아연,철강금속,10.50,0.50,...,504874327655,4.817734e+12,5.986092e+11,452757831974,NaN,NaN,NaN,9.976776e+12,1.096146e+12,8.111060e+11
34,251270,넷마블,90300.0,-2100.0,-2.27,7742734.0,넷마블,서비스업,24.80,2.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,011170,롯데케미칼,218500.0,-5500.0,-2.46,7489179.0,롯데케미칼,화학,9.91,1.15,...,143653052352,1.643894e+13,4.874227e+11,285824983019,1.590280e+13,3.717315e+11,316144804534,NaN,NaN,NaN
36,030200,KT,26700.0,-300.0,-1.11,6971685.0,KT,통신업,8.89,0.92,...,-966176000000,2.381060e+13,8.393430e+11,-60251000000,2.385638e+13,1.209233e+12,1105439000000,NaN,NaN,NaN
37,002790,아모레G,83200.0,500.0,0.60,6860521.0,아모레G,화학,9.91,1.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,024110,기업은행,11550.0,-250.0,-2.12,6666163.0,기업은행,은행,5.51,0.42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,021240,웅진코웨이,90000.0,-3100.0,-3.33,6641966.0,코웨이,서비스업,24.80,2.10,...,249668412108,2.118342e+12,3.390323e+11,245074651953,1.992838e+12,2.261465e+11,94042698014,NaN,NaN,NaN
40,035250,강원랜드,29250.0,-350.0,-1.18,6257760.0,강원랜드,서비스업,24.80,2.10,...,359348568056,1.361287e+12,3.880413e+11,297596347466,NaN,NaN,NaN,NaN,NaN,NaN
41,032640,LG유플러스,13850.0,-350.0,-2.46,6047067.0,LG유플러스,통신업,8.89,0.92,...,227721000000,1.145030e+13,5.421290e+11,279461000000,NaN,NaN,NaN,1.385114e+13,9.790140e+11,7.242180e+11
42,034220,LG디스플레이,16350.0,100.0,0.62,5850287.0,LG디스플레이,전기전자,5.49,0.98,...,917404000000,2.703304e+13,1.163314e+12,418973000000,NaN,NaN,NaN,2.987804e+13,2.230608e+12,1.333544e+12
43,018880,한온시스템,10800.0,-350.0,-3.14,5765040.0,한온시스템,기계,70.41,1.17,...,290448934994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,267250,현대중공업지주,330000.0,-8000.0,-2.37,5374584.0,현대중공업지주,화학,9.91,1.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,086280,현대글로비스,138500.0,-4500.0,-3.15,5193750.0,현대글로비스,운수창고업,25.71,1.07,...,536239893955,NaN,NaN,NaN,NaN,NaN,NaN,2.177958e+13,1.126246e+12,7.831759e+11
46,006800,미래에셋대우,7450.0,-100.0,-1.32,4904457.0,미래에셋대우,증권,7.49,0.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,078930,GS,50000.0,-1600.0,-3.10,4645769.0,GS,기타금융,NaN,NaN,...,-320729000000,9.583193e+12,5.521300e+11,435199000000,9.715714e+12,6.842690e+11,572919000000,NaN,NaN,NaN
48,010140,삼성중공업,7220.0,-50.0,-0.69,4548600.0,삼성중공업,운수장비,51.34,0.53,...,147320208845,1.483450e+13,9.142143e+11,632205456990,NaN,NaN,NaN,6.622001e+12,-1.311956e+12,-1.452070e+12
49,000720,현대건설,41200.0,-1100.0,-2.60,4587858.0,현대건설,건설업,12.79,0.84,...,479340000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,029780,삼성카드,37450.0,-1150.0,-2.98,4338915.0,삼성카드,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,271560,오리온,105500.0,0.0,0.00,4171062.0,오리온,음식료품,10.99,1.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,004020,현대제철,31200.0,-250.0,-0.79,4163508.0,현대제철,철강금속,10.50,0.50,...,782295355715,NaN,NaN,NaN,NaN,NaN,NaN,2.284992e+13,2.447503e+12,1.505155e+12
53,161390,한국타이어앤테크놀로지,32450.0,-1100.0,-3.28,4019746.0,한국타이어,화학,9.91,1.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,071050,한국금융지주,70900.0,-1500.0,-2.07,3950973.0,한국금융지주,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,004990,롯데지주,37700.0,-1250.0,-3.21,3955078.0,롯데지주,기타금융,NaN,NaN,...,1667068545,1.976367e+12,9.153706e+10,55173479211,1.864493e+12,1.153953e+11,89776244193,NaN,NaN,NaN
56,028050,삼성엔지니어링,19300.0,100.0,0.52,3782800.0,삼성엔지니어링,서비스업,24.80,2.10,...,56353493772,9.806323e+12,-1.028047e+12,-708658932989,NaN,NaN,NaN,7.486696e+12,5.032888e+11,3.510715e+11
57,023530,롯데쇼핑,135500.0,0.0,0.00,3833126.0,롯데쇼핑,유통업,9.30,0.84,...,615724154364,2.821170e+13,1.485261e+12,880634147019,NaN,NaN,NaN,1.557355e+13,2.076027e+11,-2.729642e+11
58,097950,CJ제일제당,245000.0,-7500.0,-2.97,3688276.0,CJ제일제당,음식료품,10.99,1.13,...,137851320000,1.084772e+13,3.454790e+11,71061595000,9.877532e+12,6.155287e+11,310715670000,NaN,NaN,NaN
59,008770,호텔신라,94000.0,3200.0,3.52,3689323.0,호텔신라,유통업,9.30,0.84,...,73482881944,NaN,NaN,NaN,NaN,NaN,NaN,3.779129e+12,1.188115e+11,2.705937e+10
60,000120,CJ대한통운,152500.0,-2500.0,-1.61,3478882.0,CJ대한통운,운수창고업,25.71,1.07,...,59451739573,3.795045e+12,6.417736e+10,-60061093537,2.627466e+12,1.430275e+11,69571921246,NaN,NaN,NaN
61,005830,DB손해보험,50100.0,-2200.0,-4.21,3547080.0,DB손해보험,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,139480,이마트,125500.0,-2000.0,-1.57,3498415.0,이마트,유통업,9.30,0.84,...,291918307030,1.303526e+13,7.351040e+11,476244256237,1.268504e+13,7.349986e+11,435093478206,NaN,NaN,NaN
63,012750,에스원,92500.0,-1200.0,-1.28,3514924.0,에스원,서비스업,24.80,2.10,...,116318470200,1.177638e+12,1.118702e+11,87300036554,NaN,NaN,NaN,2.312489e+12,1.796649e+11,1.289909e+11
64,005940,NH투자증권,12500.0,-200.0,-1.57,3517611.0,NH투자증권,증권,7.49,0.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,016360,삼성증권,37850.0,-750.0,-1.94,3380005.0,삼성증권,증권,7.49,0.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,241560,두산밥캣,33750.0,-600.0,-1.75,3383409.0,두산밥캣,기계,70.41,1.17,...,55970308000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,128940,한미약품,293500.0,-3000.0,-1.01,3408176.0,한미약품,의약품,89.40,4.62,...,43295070634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,036460,한국가스공사,37350.0,-500.0,-1.32,3447891.0,한국가스공사,전기가스업,0.00,0.34,...,447222938586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,047810,한국항공우주,33800.0,-250.0,-0.73,3294659.0,한국항공우주,운수장비,51.34,0.53,...,132380000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,011070,LG이노텍,139000.0,-1000.0,-0.71,3289728.0,LG이노텍,전기전자,5.49,0.98,...,112676677108,6.211516e+12,1.361501e+11,15541926763,NaN,NaN,NaN,1.494561e+13,1.264223e+12,8.882824e+11
71,081660,휠라코리아,52300.0,-700.0,-1.32,3196318.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,000210,대림산업,87800.0,-2700.0,-2.98,3055440.0,대림산업,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,009830,한화케미칼,18500.0,-350.0,-1.86,2987367.0,한화케미칼,화학,9.91,1.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,007070,GS리테일,38900.0,-350.0,-0.89,2995300.0,GS리테일,유통업,9.30,0.84,...,111280931992,4.708562e+12,1.550498e+11,119046347632,4.377552e+12,1.404741e+11,123458660331,NaN,NaN,NaN
75,000100,유한양행,231500.0,-5000.0,-2.11,2957902.0,유한양행,의약품,89.40,4.62,...,90947777976,9.436091e+11,6.183979e+10,86461208090,NaN,NaN,NaN,1.687810e+12,4.859612e+10,9.912668e+10
76,282330,BGF리테일,168500.0,-1000.0,-0.59,2912338.0,BGF리테일,유통업,9.30,0.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,042660,대우조선해양,27350.0,-500.0,-1.80,2932077.0,대우조선해양,운수장비,51.34,0.53,...,-852747122121,1.458483e+13,-1.010035e+12,-920418515185,NaN,NaN,NaN,4.486586e+12,-1.754651e+12,-1.699829e+12
78,004170,신세계,292500.0,3500.0,1.21,2879715.0,신세계,유통업,9.30,0.84,...,186056565765,2.441637e+12,3.063899e+11,194652961119,NaN,NaN,NaN,6.316436e+12,5.174006e+11,3.888666e+11
79,003410,쌍용양회,5550.0,-120.0,-2.12,2796421.0,쌍용양회,비금속광물,14.10,0.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,001040,CJ,93800.0,-2800.0,-2.90,2736802.0,CJ,기타금융,NaN,NaN,...,508633144000,1.885170e+13,7.860670e+11,322608337000,1.762839e+13,1.062972e+12,570256610000,NaN,NaN,NaN
81,030000,제일기획,23300.0,-750.0,-3.12,2680461.0,제일기획,서비스업,24.80,2.10,...,102022308936,2.709281e+12,1.299866e+11,102269218895,NaN,NaN,NaN,3.325712e+12,2.481795e+11,1.675991e+11
82,003490,대한항공,27850.0,-650.0,-2.28,2641423.0,대한항공,운수창고업,25.71,1.07,...,-612921454979,1.184871e+13,-1.956209e+10,-383555365584,NaN,NaN,NaN,9.016825e+12,1.417969e+12,5.787820e+11
83,008930,한미사이언스,38150.0,-200.0,-0.52,2469940.0,한미사이언스,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,002380,KCC,233500.0,0.0,0.00,2464946.0,KCC,화학,9.91,1.15,...,326693597855,3.233043e+12,2.317429e+11,248992623676,3.246228e+12,1.989493e+11,446319780191,NaN,NaN,NaN
85,006360,GS건설,30500.0,-550.0,-1.77,2442983.0,GS건설,건설업,12.79,0.84,...,-22452682512,9.565758e+12,-9.354505e+11,-827346708179,9.568632e+12,1.760633e+11,94960950724,NaN,NaN,NaN
86,138930,BNK금융지주,7470.0,-190.0,-2.48,2434736.0,BNK금융지주,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,028670,팬오션,4460.0,-85.0,-1.87,2384179.0,팬오션,운수창고업,25.71,1.07,...,786078000000,2.682024e+12,-2.220910e+11,-1909683000000,5.417846e+12,-2.116760e+11,-463951000000,NaN,NaN,NaN
88,001450,현대해상,25900.0,-1050.0,-3.90,2315460.0,현대해상,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,047050,포스코인터내셔널,18350.0,-300.0,-1.61,2263934.0,포스코대우,유통업,9.30,0.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,011780,금호석유,76000.0,-1500.0,-1.94,2315545.0,금호석유,화학,9.91,1.15,...,88334747850,5.132132e+12,1.342290e+11,-42712970928,5.883690e+12,2.238028e+11,126109124946,NaN,NaN,NaN
91,008560,메리츠종금증권,3745.0,-45.0,-1.19,2311829.0,메리츠종금증권,증권,7.49,0.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,000080,하이트진로,28900.0,-100.0,-0.34,2026861.0,하이트진로,음식료품,10.99,1.13,...,21253791241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,007310,오뚜기,549000.0,-5000.0,-0.90,1979275.0,오뚜기,음식료품,10.99,1.13,...,94111327807,1.728175e+12,1.050757e+11,92241259915,1.686638e+12,1.086878e+11,75786100328,NaN,NaN,NaN
94,088350,한화생명,2290.0,-20.0,-0.87,1988934.0,한화생명,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,069960,현대백화점,85900.0,2800.0,3.37,2010270.0,현대백화점,유통업,9.30,0.84,...,291023905000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,020150,일진머티리얼즈,43000.0,250.0,0.58,1982766.0,일진머티리얼즈,전기전자,5.49,0.98,...,-1900000000,3.499910e+11,-1.484300e+10,-8991000000,3.932290e+11,-6.842000e+09,-57211000000,NaN,NaN,NaN
97,009420,한올바이오파마,36450.0,150.0,0.41,1904171.0,한올바이오파마,의약품,89.40,4.62,...,-12658084909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,047040,대우건설,4660.0,-80.0,-1.69,1936801.0,대우건설,건설업,12.79,0.84,...,102110186625,8.782196e+12,-2.446644e+11,-718036005284,8.223433e+12,3.456866e+11,173028929706,NaN,NaN,NaN
99,017800,현대엘리베이,67600.0,-700.0,-1.02,1838675.0,현대엘리베이,기계,70.41,1.17,...,50419452905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,011790,SKC,50600.0,-400.0,-0.78,1899248.0,SKC,화학,9.91,1.15,...,43307997481,2.641403e+12,1.240027e+11,25737659251,2.629171e+12,1.447316e+11,31810661954,NaN,NaN,NaN
101,000880,한화,24350.0,-650.0,-2.60,1825245.0,한화,화학,9.91,1.15,...,-163026000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,051600,한전KPS,38550.0,-600.0,-1.53,1734750.0,한전KPS,건설업,12.79,0.84,...,168295607804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,012450,한화에어로스페이스,34700.0,-350.0,-1.00,1789132.0,한화에어로스페이스,운수장비,51.34,0.53,...,-118181869522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,010620,현대미포조선,44900.0,-1150.0,-2.50,1793402.0,현대미포조선,운수장비,51.34,0.53,...,-679259389000,NaN,NaN,NaN,NaN,NaN,NaN,2.887212e+12,-2.173254e+11,-1.601085e+11
105,004800,효성,76300.0,-2800.0,-3.54,1607719.0,효성,기타금융,NaN,NaN,...,291989964756,NaN,NaN,NaN,NaN,NaN,NaN,3.538943e+12,6.405627e+11,5.405865e+11
106,010120,LS산전,52600.0,-2000.0,-3.66,1578000.0,LS산전,전기전자,5.49,0.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,204320,만도,34900.0,-300.0,-0.85,1638803.0,만도,운수장비,51.34,0.53,...,47893247651,NaN,NaN,NaN,NaN,NaN,NaN,6.147433e+12,2.323120e+11,1.786158e+11
108,069620,대웅제약,136500.0,-1000.0,-0.73,1581567.0,대웅제약,의약품,89.40,4.62,...,30469955819,6.825080e+11,7.137163e+10,57974401214,6.690138e+11,3.688282e+10,33512863577,NaN,NaN,NaN
109,026960,동서,16750.0,-650.0,-3.74,1669975.0,동서,유통업,9.30,0.84,...,131013543380,4.703688e+11,5.096035e+10,126490087864,4.596820e+11,5.133287e+10,125452016052,NaN,NaN,NaN
110,001740,SK네트웍스,5900.0,-40.0,-0.67,1464307.0,SK네트웍스,유통업,9.30,0.84,...,,2.597536e+13,2.408235e+11,,2.793550e+13,2.515600e+11,,NaN,NaN,NaN
111,006260,LS,46900.0,-900.0,-1.88,1510180.0,LS,기타금융,NaN,NaN,...,86705000000,1.139358e+13,4.653470e+11,165153000000,1.188120e+13,4.476390e+11,213736000000,NaN,NaN,NaN
112,006280,녹십자,131000.0,-1500.0,-1.13,1530936.0,녹십자,의약품,89.40,4.62,...,86789122722,8.881682e+11,7.880846e+10,72027708210,8.117743e+11,7.435568e+10,55611788487,NaN,NaN,NaN
113,111770,영원무역,33650.0,-600.0,-1.75,1491081.0,영원무역,유통업,9.30,0.84,...,143317702438,1.108227e+12,1.607880e+11,121929362507,1.059149e+12,1.863027e+11,131669465691,NaN,NaN,NaN
114,010060,OCI,62800.0,200.0,0.32,1497740.0,OCI,화학,9.91,1.15,...,42334700000,2.238126e+12,-1.867455e+11,-287777262000,NaN,NaN,NaN,3.243997e+12,6.259849e+11,6.520758e+11
115,031430,신세계인터내셔날,220000.0,500.0,0.23,1570800.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,009240,한샘,66700.0,4500.0,7.23,1569713.0,한샘,유통업,9.30,0.84,...,86692476942,NaN,NaN,NaN,NaN,NaN,NaN,2.231221e+12,6.926426e+10,5.721819e+10
117,004370,농심,237000.0,-3500.0,-1.46,1441586.0,농심,음식료품,10.99,1.13,...,64454972212,2.086651e+12,9.260272e+10,86896539044,2.175711e+12,9.689195e+10,-9166417222,NaN,NaN,NaN
118,214320,이노션,70000.0,-900.0,-1.27,1400000.0,이노션,서비스업,24.80,2.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,120110,코오롱인더,49450.0,-300.0,-0.60,1334104.0,코오롱인더,화학,9.91,1.15,...,39640555089,5.261463e+12,2.316387e+11,113672188089,5.312951e+12,2.939525e+11,171148613586,NaN,NaN,NaN
120,011210,현대위아,48950.0,-1250.0,-2.49,1331199.0,현대위아,운수장비,51.34,0.53,...,439188902750,NaN,NaN,NaN,NaN,NaN,NaN,7.527739e+12,1.027250e+11,5.607100e+10
121,000240,한국테크놀로지그룹,14000.0,-400.0,-2.78,1302282.0,한국타이어월드와이드,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,114090,GKL,19450.0,0.0,0.00,1203093.0,GKL,서비스업,24.80,2.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,064350,현대로템,15450.0,-150.0,-0.96,1313250.0,현대로템,운수장비,51.34,0.53,...,-15108710000,NaN,NaN,NaN,NaN,NaN,NaN,2.872512e+12,8.021796e+10,5.141160e+10
124,000990,DB하이텍,27900.0,300.0,1.09,1238721.0,DB하이텍,전기전자,5.49,0.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,000150,두산,68900.0,-1400.0,-1.99,1138492.0,두산,서비스업,24.80,2.10,...,33249466961,2.161606e+13,1.135179e+12,130167997406,2.385751e+13,7.873744e+11,201507512711,NaN,NaN,NaN
126,000670,영풍,646000.0,1000.0,0.16,1189958.0,영풍,철강금속,10.50,0.50,...,100584987718,3.273760e+12,1.575246e+11,234426916394,NaN,NaN,NaN,3.582075e+12,-2.678431e+10,1.700635e+11
127,001800,오리온홀딩스,17550.0,-250.0,-1.40,1099427.0,오리온홀딩스,기타금융,NaN,NaN,...,174297158567,2.485196e+12,2.594811e+11,160240858319,NaN,NaN,NaN,2.415059e+12,3.156974e+11,2.253283e+11
128,003240,태광산업,1065000.0,5000.0,0.47,1185771.0,태광산업,화학,9.91,1.15,...,122820168364,3.513353e+12,1.686005e+11,113939553791,NaN,NaN,NaN,2.591846e+12,3.552726e+11,3.183681e+11
129,003520,영진약품,6460.0,-170.0,-2.56,1181487.0,영진약품,의약품,89.40,4.62,...,909091950,1.566227e+11,6.916530e+09,11742329875,NaN,NaN,NaN,1.960672e+11,-1.387751e+10,-1.158246e+10
130,004000,롯데정밀화학,44100.0,-1050.0,-2.33,1137780.0,롯데정밀화학,화학,9.91,1.15,...,58682516778,1.314058e+12,-2.034363e+10,3340492457,NaN,NaN,NaN,1.780293e+12,2.445136e+11,5.854585e+11
131,294870,HDC현대산업개발,25400.0,-250.0,-0.97,1116031.0,HDC현대산업개발,건설업,12.79,0.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,005440,현대그린푸드,11650.0,-200.0,-1.69,1138257.0,현대그린푸드,유통업,9.30,0.84,...,97945207000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,014680,한솔케미칼,103500.0,-2500.0,-2.36,1169053.0,한솔케미칼,화학,9.91,1.15,...,21422845255,NaN,NaN,NaN,NaN,NaN,NaN,7.686882e+11,1.976846e+11,1.586709e+11
134,034020,두산중공업,5730.0,10.0,0.17,1158302.0,두산중공업,기계,70.41,1.17,...,-85475347180,1.920817e+13,9.580717e+11,18662825932,2.127406e+13,5.861515e+11,97475586606,NaN,NaN,NaN

In [ ]:
year_3_going = join_t4[(join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

,종목코드,종목명_x,업종명,종가,업종PER,업종PBR,PER,PBR,종가_2020,증가율
0,005930,삼성전자,전기전자,38750,5.49,0.98,6.46,1.38,55200.0,42.451613
1,000660,SK하이닉스,전기전자,60600,5.49,0.98,4.02,1.30,94700.0,56.270627
2,005490,POSCO,철강금속,237000,10.50,0.50,6.88,0.47,236000.0,-0.421941
3,028260,삼성물산,유통업,104000,9.30,0.84,26.81,0.88,107500.0,3.365385
4,051900,LG생활건강,화학,1081000,9.91,1.15,29.86,6.39,1266000.0,17.113784

In [ ]:
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

16,17,18년도 매년 영업이익 증가한 기업 갯수 : 34
16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : 1.67885385264962

In [ ]:
year_3_nogoing = join_t4[~((join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_nogoing_join = pd.merge(year_3_nogoing, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2020']- year_3_nogoing_join['종가'])/year_3_nogoing_join['종가'])*100
year_3_nogoing_join = year_3_nogoing_join[~year_3_nogoing_join['종가_2020'].isnull()]
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

16,17,18년도 매년 영업이익 증가한 기업 갯수 : 166
16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : -5.099764979339883

## 15,16,17년치 영업이익 감소추세 종목과 그 나머지 종목간 수익률 비교

In [ ]:
import pandas as pd

In [ ]:
prices_201801 = pd.read_csv('../gdrive/MyDrive/stock/kospi_200_prices_201801.csv',converters= {'종목코드':str},encoding='cp949')
prices_201801 = prices_201801[['종목코드', '종목명', '종가']]

In [ ]:
prices_201901 = pd.read_csv('../gdrive/MyDrive/stock/kospi_200_prices_201901.csv',converters= {'종목코드':str},encoding='cp949')
prices_201901 = prices_201901[['종목코드', '종목명', '종가']]

In [ ]:
result = pd.read_csv('../gdrive/MyDrive/stock/final_result.csv',index_col=0)
result = result.reset_index()
result = result.rename(columns = {'index':'종목명'})
join_t1 = pd.merge(prices_201801, result,how='left',on='종목명')
year_3_going = join_t1[(join_t1['2015영업이익']>join_t1['2016영업이익']) & (join_t1['2016영업이익']>join_t1['2017영업이익'])][['종목코드','종목명','종가']]
year_3_going_join = pd.merge(year_3_going, prices_201901, how='left', on = '종목코드')[['종목코드', '종목명_x', '종가_x', '종가_y']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_y']- year_3_going_join['종가_x'])/year_3_going_join['종가_x'])*100
year_3_going_join = year_3_going_join.loc[~year_3_going_join['증가율'].isnull()]
print('15,16,17년도 매년 영업이익 감소추세 기업의 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('15,16,17년도 매년 영업이익 감소추세의 기업의 평균수익률 : {}'.format(average_returns))

15,16,17년도 매년 영업이익 감소추세 기업의 갯수 : 16
15,16,17년도 매년 영업이익 감소추세의 기업의 평균수익률 : -27.203514630394224

In [ ]:
year_3_going = join_t1[~((join_t1['2015영업이익']>join_t1['2016영업이익']) & (join_t1['2016영업이익']>join_t1['2017영업이익']))][['종목코드','종목명','종가']]
year_3_going_join = pd.merge(year_3_going, prices_201901, how='left', on = '종목코드')[['종목코드', '종목명_x', '종가_x', '종가_y']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_y']- year_3_going_join['종가_x'])/year_3_going_join['종가_x'])*100
year_3_going_join = year_3_going_join.loc[~year_3_going_join['증가율'].isnull()]
print('15,16,17년도 매년 영업이익 감소추세의 기업을 제외한 기업의 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('15,16,17년도 매년 영업이익 감소추세의 기업을 제외한 기업들의 평균 수익률 : {}'.format(average_returns))

15,16,17년도 매년 영업이익 감소추세의 기업을 제외한 기업의 갯수 : 178
15,16,17년도 매년 영업이익 감소추세의 기업을 제외한 기업들의 평균 수익률 : -18.23960731702056

In [ ]:
year_3_going = join_t4[(join_t4['2017영업이익']<join_t4['2018영업이익']) & (join_t4['2018영업이익']<join_t4['2019영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

,종목코드,종목명,업종명,업종PER,업종PBR,업종배당수익률,종가,EPS,PER,BPS,...,2014당기순이익,2013매출액,2013영업이익,2013당기순이익,2012매출액,2012영업이익,2012당기순이익,2021매출액,2021영업이익,2021당기순이익
13,012330,현대모비스,운수장비,51.34,0.53,1.77,185000,16558.0,11.17,300935.0,...,3392512000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,051900,LG생활건강,화학,9.91,1.15,2.09,1081000,36199.0,29.86,169155.0,...,354564706876,4.326255e+12,4.964117e+11,365652540664,3.896218e+12,4.455311e+11,311987779732,NaN,NaN,NaN
17,018260,삼성에스디에스,서비스업,24.80,2.10,1.25,206000,6856.0,30.05,71833.0,...,434272525474,7.046833e+12,5.056289e+11,325982504939,NaN,NaN,NaN,1.363000e+13,8.080978e+11,6.333814e+11
21,000270,기아차,운수장비,51.34,0.53,1.77,32800,2414.0,13.59,66264.0,...,2993593000000,4.759790e+13,3.177100e+12,3817059000000,4.724293e+13,3.522251e+12,3864704000000,NaN,NaN,NaN
42,004990,롯데지주,기타금융,NaN,NaN,NaN,49950,7625.0,6.55,81890.0,...,1667068545,1.976367e+12,9.153706e+10,55173479211,1.864493e+12,1.153953e+11,89776244193,NaN,NaN,NaN
49,128940,한미약품,의약품,89.40,4.62,0.19,450500,5276.0,85.39,61358.0,...,43295070634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,097950,CJ제일제당,음식료품,10.99,1.13,1.21,331000,26179.0,12.64,232686.0,...,137851320000,1.084772e+13,3.454790e+11,71061595000,9.877532e+12,6.155287e+11,310715670000,NaN,NaN,NaN
58,271560,오리온,음식료품,10.99,1.13,1.21,111000,1912.0,58.05,33092.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,036460,한국가스공사,전기가스업,0.00,0.34,2.03,46350,NaN,NaN,84640.0,...,447222938586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,000120,CJ대한통운,운수창고업,25.71,1.07,1.03,166500,1786.0,93.23,103964.0,...,59451739573,3.795045e+12,6.417736e+10,-60061093537,2.627466e+12,1.430275e+11,69571921246,NaN,NaN,NaN
69,028050,삼성엔지니어링,서비스업,24.80,2.10,1.25,17450,NaN,NaN,5236.0,...,56353493772,9.806323e+12,-1.028047e+12,-708658932989,NaN,NaN,NaN,7.486696e+12,5.032888e+11,3.510715e+11
70,001040,CJ,기타금융,NaN,NaN,NaN,116000,15357.0,7.55,117874.0,...,508633144000,1.885170e+13,7.860670e+11,322608337000,1.762839e+13,1.062972e+12,570256610000,NaN,NaN,NaN
74,047810,한국항공우주,운수장비,51.34,0.53,1.77,32500,NaN,NaN,11699.0,...,132380000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,007070,GS리테일,유통업,9.30,0.84,1.47,39250,1535.0,25.57,26369.0,...,111280931992,4.708562e+12,1.550498e+11,119046347632,4.377552e+12,1.404741e+11,123458660331,NaN,NaN,NaN
82,008770,호텔신라,유통업,9.30,0.84,1.47,73100,667.0,109.60,16687.0,...,73482881944,NaN,NaN,NaN,NaN,NaN,NaN,3.779129e+12,1.188115e+11,2.705937e+10
87,030000,제일기획,서비스업,24.80,2.10,1.25,22300,1255.0,17.77,7354.0,...,102022308936,2.709281e+12,1.299866e+11,102269218895,NaN,NaN,NaN,3.325712e+12,2.481795e+11,1.675991e+11
90,028670,팬오션,운수창고업,25.71,1.07,1.03,4445,268.0,16.59,4469.0,...,786078000000,2.682024e+12,-2.220910e+11,-1909683000000,5.417846e+12,-2.116760e+11,-463951000000,NaN,NaN,NaN
91,004170,신세계,유통업,9.30,0.84,1.47,248000,18530.0,13.38,347557.0,...,186056565765,2.441637e+12,3.063899e+11,194652961119,NaN,NaN,NaN,6.316436e+12,5.174006e+11,3.888666e+11
104,009420,한올바이오파마,의약품,89.40,4.62,0.19,34950,114.0,306.58,2129.0,...,-12658084909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,111770,영원무역,유통업,9.30,0.84,1.47,37850,2477.0,15.28,27747.0,...,143317702438,1.108227e+12,1.607880e+11,121929362507,1.059149e+12,1.863027e+11,131669465691,NaN,NaN,NaN
110,161890,한국콜마,화학,9.91,1.15,2.09,70000,2240.0,31.25,14458.0,...,32806096793,NaN,NaN,NaN,NaN,NaN,NaN,1.586333e+12,8.426755e+10,4.353483e+10
117,073240,금호타이어,화학,9.91,1.15,2.09,5200,NaN,NaN,6042.0,...,131608463703,3.698542e+12,3.459358e+11,100958039283,4.070644e+12,3.753463e+11,130586236572,NaN,NaN,NaN
119,051600,한전KPS,건설업,12.79,0.84,1.05,32400,3021.0,10.72,20113.0,...,168295607804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,204320,만도,운수장비,51.34,0.53,1.77,28850,102.0,282.84,28786.0,...,47893247651,NaN,NaN,NaN,NaN,NaN,NaN,6.147433e+12,2.323120e+11,1.786158e+11
127,192820,코스맥스,화학,9.91,1.15,2.09,125000,1877.0,66.60,21704.0,...,15756824739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,034020,두산중공업,기계,70.41,1.17,1.41,9450,NaN,NaN,28373.0,...,-85475347180,1.920817e+13,9.580717e+11,18662825932,2.127406e+13,5.861515e+11,97475586606,NaN,NaN,NaN
134,005300,롯데칠성,음식료품,10.99,1.13,1.21,1374000,108521.0,12.66,1497124.0,...,20553075432,2.138971e+12,1.608654e+11,103493317426,NaN,NaN,NaN,2.506093e+12,1.822184e+11,1.370769e+11
135,001800,오리온홀딩스,기타금융,NaN,NaN,NaN,16650,39092.0,0.43,29498.0,...,174297158567,2.485196e+12,2.594811e+11,160240858319,NaN,NaN,NaN,2.415059e+12,3.156974e+11,2.253283e+11
147,014680,한솔케미칼,화학,9.91,1.15,2.09,76300,4893.0,15.59,28396.0,...,21422845255,NaN,NaN,NaN,NaN,NaN,NaN,7.686882e+11,1.976846e+11,1.586709e+11
148,020000,한섬,섬유의복,6.41,0.65,1.32,36300,2451.0,14.81,37575.0,...,36375237191,NaN,NaN,NaN,NaN,NaN,NaN,1.387402e+12,1.521929e+11,1.115236e+11
152,001680,대상,음식료품,10.99,1.13,1.21,24600,1467.0,16.77,24181.0,...,90020443186,2.542303e+12,1.558228e+11,105760974827,NaN,NaN,NaN,3.469993e+12,1.532452e+11,1.449496e+11
159,192400,쿠쿠홀딩스,기타금융,NaN,NaN,NaN,118000,57026.0,2.07,67311.0,...,90732489650,5.087579e+11,6.846339e+10,57439759673,3.067094e+11,3.245852e+10,28870796908,NaN,NaN,NaN
164,004800,효성,기타금융,NaN,NaN,NaN,47950,11575.0,4.14,123059.0,...,291989964756,NaN,NaN,NaN,NaN,NaN,NaN,3.538943e+12,6.405627e+11,5.405865e+11
184,003850,보령제약,의약품,89.40,4.62,0.19,10050,1334.0,7.53,5662.0,...,21590563674,3.272787e+11,1.913676e+10,14126625318,NaN,NaN,NaN,6.272794e+11,4.144823e+10,4.311926e+10

In [ ]:
pd.merge(prices_2020_01, join_t4, how='left',on='종목코드')

,종목코드,종목명_x,종가_x,대비,등락률,상장시가총액,종목명_y,업종명,업종PER,업종PBR,...,2014당기순이익,2013매출액,2013영업이익,2013당기순이익,2012매출액,2012영업이익,2012당기순이익,2021매출액,2021영업이익,2021당기순이익
0,005930,삼성전자,55200.0,-600.0,-1.08,329531997.0,삼성전자,전기전자,5.49,0.98,...,23394358000000,2.286927e+14,3.678501e+13,30474764000000,NaN,NaN,NaN,2.796048e+14,5.163386e+13,3.990745e+13
1,000660,SK하이닉스,94700.0,600.0,0.64,68941824.0,SK하이닉스,전기전자,5.49,0.98,...,582424000000,1.416510e+13,8.864587e+12,505870000000,1.016221e+13,8.550989e+12,62910000000,NaN,NaN,NaN
2,035420,NAVER,182500.0,-4000.0,-2.14,30078445.0,NAVER,서비스업,24.80,2.10,...,451763104000,2.259139e+12,5.065388e+11,1895289315000,NaN,NaN,NaN,6.817600e+12,1.325478e+12,1.647763e+13
3,207940,삼성바이오로직스,428500.0,-4500.0,-1.04,28351703.0,삼성바이오로직스,의약품,89.40,4.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,005380,현대차,118000.0,-2500.0,-2.07,25212846.0,현대차,운수장비,51.34,0.53,...,7649468000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,012330,현대모비스,247500.0,-8500.0,-3.32,23588407.0,현대모비스,운수장비,51.34,0.53,...,3392512000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,068270,셀트리온,180000.0,-1000.0,-0.55,23100814.0,셀트리온,의약품,89.40,4.62,...,NaN,2.262079e+11,9.984543e+10,NaN,NaN,NaN,NaN,1.911601e+12,7.524858e+11,5.914081e+11
7,051910,LG화학,314000.0,-3500.0,-1.10,22165996.0,LG화학,화학,9.91,1.15,...,854025000000,2.314361e+13,1.743044e+12,1270613000000,NaN,NaN,NaN,4.265472e+13,5.025466e+12,3.953904e+12
8,005490,POSCO,236000.0,-500.0,-0.21,20576093.0,POSCO,철강금속,10.50,0.50,...,556659145957,6.186465e+13,2.996134e+12,1355180337664,NaN,NaN,NaN,7.633235e+13,9.238089e+12,7.195890e+12
9,028260,삼성물산,107500.0,-1000.0,-0.92,20391680.0,삼성물산,유통업,9.30,0.84,...,455072359783,3.226059e+12,1.110928e+11,45192147862,NaN,NaN,NaN,3.445518e+13,1.195983e+12,1.829084e+12
10,055550,신한지주,42600.0,-750.0,-1.73,20200902.0,신한지주,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,051900,LG생활건강,1266000.0,5000.0,0.40,19772637.0,LG생활건강,화학,9.91,1.15,...,354564706876,4.326255e+12,4.964117e+11,365652540664,3.896218e+12,4.455311e+11,311987779732,NaN,NaN,NaN
12,105560,KB금융,46550.0,-1100.0,-2.31,19355859.0,KB금융,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,017670,SK텔레콤,234000.0,-4000.0,-1.68,18894496.0,SK텔레콤,통신업,8.89,0.92,...,1799320000000,1.660205e+13,2.011109e+12,1609549000000,1.614141e+13,1.730049e+12,1115663000000,NaN,NaN,NaN
14,015760,한국전력,28500.0,700.0,2.52,18295976.0,한국전력,전기가스업,0.00,0.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,034730,SK,258000.0,-4000.0,-1.53,18152957.0,SK,기타금융,NaN,NaN,...,129898845716,2.301755e+12,2.251929e+11,202347149059,2.241803e+12,2.007273e+11,399619602223,NaN,NaN,NaN
16,000270,기아차,42500.0,-1800.0,-4.06,17227942.0,기아차,운수장비,51.34,0.53,...,2993593000000,4.759790e+13,3.177100e+12,3817059000000,4.724293e+13,3.522251e+12,3864704000000,NaN,NaN,NaN
17,006400,삼성SDI,232000.0,-4000.0,-1.69,15953371.0,삼성SDI,전기전자,5.49,0.98,...,-80314437457,5.016465e+12,-2.739436e+10,147915701017,NaN,NaN,NaN,1.355322e+13,1.067576e+12,1.250402e+12
18,018260,삼성에스디에스,192000.0,-2500.0,-1.29,14856538.0,삼성에스디에스,서비스업,24.80,2.10,...,434272525474,7.046833e+12,5.056289e+11,325982504939,NaN,NaN,NaN,1.363000e+13,8.080978e+11,6.333814e+11
19,032830,삼성생명,73100.0,-1400.0,-1.88,14620000.0,삼성생명,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,096770,SK이노베이션,146500.0,-3500.0,-2.33,13546205.0,SK이노베이션,화학,9.91,1.15,...,-537165529000,6.666952e+13,1.382891e+12,778733149000,7.333001e+13,1.699364e+12,1182351665000,NaN,NaN,NaN
21,035720,카카오,152500.0,-1000.0,-0.65,13147593.0,카카오,서비스업,24.80,2.10,...,149821510168,2.107759e+11,6.585234e+10,61406763238,4.618147e+10,6.979275e+09,5286923426,NaN,NaN,NaN
22,033780,KT&G,92500.0,-1300.0,-1.39,12699556.0,KT&G,기타제조업,NaN,NaN,...,800411845995,3.782630e+12,1.020072e+12,558194389161,3.911818e+12,1.030636e+12,718677658268,NaN,NaN,NaN
23,003550,LG,71100.0,-2700.0,-3.66,12268812.0,LG,기타금융,NaN,NaN,...,834264000000,9.799213e+12,1.153922e+12,830863000000,9.695204e+12,1.231546e+12,961702000000,NaN,NaN,NaN
24,090430,아모레퍼시픽,207500.0,7500.0,3.75,12130137.0,아모레퍼시픽,화학,9.91,1.15,...,385133728193,3.100413e+12,3.698382e+11,267359054309,2.849462e+12,3.653387e+11,269257537859,NaN,NaN,NaN
25,036570,엔씨소프트,541000.0,0.0,0.00,11877126.0,엔씨소프트,서비스업,24.80,2.10,...,227519296162,7.566557e+11,2.052352e+11,158695768295,7.535200e+11,1.512520e+11,153666725549,NaN,NaN,NaN
26,066570,LG전자,71000.0,-1100.0,-1.53,11618995.0,LG전자,전기전자,5.49,0.98,...,501357000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,000810,삼성화재,238500.0,-5000.0,-2.05,11298899.0,삼성화재,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,086790,하나금융지주,35950.0,-950.0,-2.57,10793702.0,하나금융지주,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,010950,S-Oil,91900.0,-3400.0,-3.57,10346359.0,S-Oil,화학,9.91,1.15,...,-287828000000,3.115853e+13,3.660440e+11,289639000000,NaN,NaN,NaN,2.746392e+13,2.140942e+12,1.378541e+12
30,009150,삼성전기,126500.0,1500.0,1.20,9448753.0,삼성전기,전기전자,5.49,0.98,...,508911818142,7.126507e+12,5.409685e+11,345692360329,NaN,NaN,NaN,9.675036e+12,1.486873e+12,9.154325e+11
31,009540,한국조선해양,125500.0,-1000.0,-0.79,8882026.0,현대중공업,운수장비,51.34,0.53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,316140,우리금융지주,11400.0,-200.0,-1.72,8233852.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,010130,고려아연,424000.0,-1000.0,-0.24,8000880.0,고려아연,철강금속,10.50,0.50,...,504874327655,4.817734e+12,5.986092e+11,452757831974,NaN,NaN,NaN,9.976776e+12,1.096146e+12,8.111060e+11
34,251270,넷마블,90300.0,-2100.0,-2.27,7742734.0,넷마블,서비스업,24.80,2.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,011170,롯데케미칼,218500.0,-5500.0,-2.46,7489179.0,롯데케미칼,화학,9.91,1.15,...,143653052352,1.643894e+13,4.874227e+11,285824983019,1.590280e+13,3.717315e+11,316144804534,NaN,NaN,NaN
36,030200,KT,26700.0,-300.0,-1.11,6971685.0,KT,통신업,8.89,0.92,...,-966176000000,2.381060e+13,8.393430e+11,-60251000000,2.385638e+13,1.209233e+12,1105439000000,NaN,NaN,NaN
37,002790,아모레G,83200.0,500.0,0.60,6860521.0,아모레G,화학,9.91,1.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,024110,기업은행,11550.0,-250.0,-2.12,6666163.0,기업은행,은행,5.51,0.42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,021240,웅진코웨이,90000.0,-3100.0,-3.33,6641966.0,코웨이,서비스업,24.80,2.10,...,249668412108,2.118342e+12,3.390323e+11,245074651953,1.992838e+12,2.261465e+11,94042698014,NaN,NaN,NaN
40,035250,강원랜드,29250.0,-350.0,-1.18,6257760.0,강원랜드,서비스업,24.80,2.10,...,359348568056,1.361287e+12,3.880413e+11,297596347466,NaN,NaN,NaN,NaN,NaN,NaN
41,032640,LG유플러스,13850.0,-350.0,-2.46,6047067.0,LG유플러스,통신업,8.89,0.92,...,227721000000,1.145030e+13,5.421290e+11,279461000000,NaN,NaN,NaN,1.385114e+13,9.790140e+11,7.242180e+11
42,034220,LG디스플레이,16350.0,100.0,0.62,5850287.0,LG디스플레이,전기전자,5.49,0.98,...,917404000000,2.703304e+13,1.163314e+12,418973000000,NaN,NaN,NaN,2.987804e+13,2.230608e+12,1.333544e+12
43,018880,한온시스템,10800.0,-350.0,-3.14,5765040.0,한온시스템,기계,70.41,1.17,...,290448934994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,267250,현대중공업지주,330000.0,-8000.0,-2.37,5374584.0,현대중공업지주,화학,9.91,1.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,086280,현대글로비스,138500.0,-4500.0,-3.15,5193750.0,현대글로비스,운수창고업,25.71,1.07,...,536239893955,NaN,NaN,NaN,NaN,NaN,NaN,2.177958e+13,1.126246e+12,7.831759e+11
46,006800,미래에셋대우,7450.0,-100.0,-1.32,4904457.0,미래에셋대우,증권,7.49,0.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,078930,GS,50000.0,-1600.0,-3.10,4645769.0,GS,기타금융,NaN,NaN,...,-320729000000,9.583193e+12,5.521300e+11,435199000000,9.715714e+12,6.842690e+11,572919000000,NaN,NaN,NaN
48,010140,삼성중공업,7220.0,-50.0,-0.69,4548600.0,삼성중공업,운수장비,51.34,0.53,...,147320208845,1.483450e+13,9.142143e+11,632205456990,NaN,NaN,NaN,6.622001e+12,-1.311956e+12,-1.452070e+12
49,000720,현대건설,41200.0,-1100.0,-2.60,4587858.0,현대건설,건설업,12.79,0.84,...,479340000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,029780,삼성카드,37450.0,-1150.0,-2.98,4338915.0,삼성카드,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,271560,오리온,105500.0,0.0,0.00,4171062.0,오리온,음식료품,10.99,1.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,004020,현대제철,31200.0,-250.0,-0.79,4163508.0,현대제철,철강금속,10.50,0.50,...,782295355715,NaN,NaN,NaN,NaN,NaN,NaN,2.284992e+13,2.447503e+12,1.505155e+12
53,161390,한국타이어앤테크놀로지,32450.0,-1100.0,-3.28,4019746.0,한국타이어,화학,9.91,1.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,071050,한국금융지주,70900.0,-1500.0,-2.07,3950973.0,한국금융지주,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,004990,롯데지주,37700.0,-1250.0,-3.21,3955078.0,롯데지주,기타금융,NaN,NaN,...,1667068545,1.976367e+12,9.153706e+10,55173479211,1.864493e+12,1.153953e+11,89776244193,NaN,NaN,NaN
56,028050,삼성엔지니어링,19300.0,100.0,0.52,3782800.0,삼성엔지니어링,서비스업,24.80,2.10,...,56353493772,9.806323e+12,-1.028047e+12,-708658932989,NaN,NaN,NaN,7.486696e+12,5.032888e+11,3.510715e+11
57,023530,롯데쇼핑,135500.0,0.0,0.00,3833126.0,롯데쇼핑,유통업,9.30,0.84,...,615724154364,2.821170e+13,1.485261e+12,880634147019,NaN,NaN,NaN,1.557355e+13,2.076027e+11,-2.729642e+11
58,097950,CJ제일제당,245000.0,-7500.0,-2.97,3688276.0,CJ제일제당,음식료품,10.99,1.13,...,137851320000,1.084772e+13,3.454790e+11,71061595000,9.877532e+12,6.155287e+11,310715670000,NaN,NaN,NaN
59,008770,호텔신라,94000.0,3200.0,3.52,3689323.0,호텔신라,유통업,9.30,0.84,...,73482881944,NaN,NaN,NaN,NaN,NaN,NaN,3.779129e+12,1.188115e+11,2.705937e+10
60,000120,CJ대한통운,152500.0,-2500.0,-1.61,3478882.0,CJ대한통운,운수창고업,25.71,1.07,...,59451739573,3.795045e+12,6.417736e+10,-60061093537,2.627466e+12,1.430275e+11,69571921246,NaN,NaN,NaN
61,005830,DB손해보험,50100.0,-2200.0,-4.21,3547080.0,DB손해보험,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,139480,이마트,125500.0,-2000.0,-1.57,3498415.0,이마트,유통업,9.30,0.84,...,291918307030,1.303526e+13,7.351040e+11,476244256237,1.268504e+13,7.349986e+11,435093478206,NaN,NaN,NaN
63,012750,에스원,92500.0,-1200.0,-1.28,3514924.0,에스원,서비스업,24.80,2.10,...,116318470200,1.177638e+12,1.118702e+11,87300036554,NaN,NaN,NaN,2.312489e+12,1.796649e+11,1.289909e+11
64,005940,NH투자증권,12500.0,-200.0,-1.57,3517611.0,NH투자증권,증권,7.49,0.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,016360,삼성증권,37850.0,-750.0,-1.94,3380005.0,삼성증권,증권,7.49,0.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,241560,두산밥캣,33750.0,-600.0,-1.75,3383409.0,두산밥캣,기계,70.41,1.17,...,55970308000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,128940,한미약품,293500.0,-3000.0,-1.01,3408176.0,한미약품,의약품,89.40,4.62,...,43295070634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,036460,한국가스공사,37350.0,-500.0,-1.32,3447891.0,한국가스공사,전기가스업,0.00,0.34,...,447222938586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,047810,한국항공우주,33800.0,-250.0,-0.73,3294659.0,한국항공우주,운수장비,51.34,0.53,...,132380000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,011070,LG이노텍,139000.0,-1000.0,-0.71,3289728.0,LG이노텍,전기전자,5.49,0.98,...,112676677108,6.211516e+12,1.361501e+11,15541926763,NaN,NaN,NaN,1.494561e+13,1.264223e+12,8.882824e+11
71,081660,휠라코리아,52300.0,-700.0,-1.32,3196318.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,000210,대림산업,87800.0,-2700.0,-2.98,3055440.0,대림산업,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,009830,한화케미칼,18500.0,-350.0,-1.86,2987367.0,한화케미칼,화학,9.91,1.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,007070,GS리테일,38900.0,-350.0,-0.89,2995300.0,GS리테일,유통업,9.30,0.84,...,111280931992,4.708562e+12,1.550498e+11,119046347632,4.377552e+12,1.404741e+11,123458660331,NaN,NaN,NaN
75,000100,유한양행,231500.0,-5000.0,-2.11,2957902.0,유한양행,의약품,89.40,4.62,...,90947777976,9.436091e+11,6.183979e+10,86461208090,NaN,NaN,NaN,1.687810e+12,4.859612e+10,9.912668e+10
76,282330,BGF리테일,168500.0,-1000.0,-0.59,2912338.0,BGF리테일,유통업,9.30,0.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,042660,대우조선해양,27350.0,-500.0,-1.80,2932077.0,대우조선해양,운수장비,51.34,0.53,...,-852747122121,1.458483e+13,-1.010035e+12,-920418515185,NaN,NaN,NaN,4.486586e+12,-1.754651e+12,-1.699829e+12
78,004170,신세계,292500.0,3500.0,1.21,2879715.0,신세계,유통업,9.30,0.84,...,186056565765,2.441637e+12,3.063899e+11,194652961119,NaN,NaN,NaN,6.316436e+12,5.174006e+11,3.888666e+11
79,003410,쌍용양회,5550.0,-120.0,-2.12,2796421.0,쌍용양회,비금속광물,14.10,0.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,001040,CJ,93800.0,-2800.0,-2.90,2736802.0,CJ,기타금융,NaN,NaN,...,508633144000,1.885170e+13,7.860670e+11,322608337000,1.762839e+13,1.062972e+12,570256610000,NaN,NaN,NaN
81,030000,제일기획,23300.0,-750.0,-3.12,2680461.0,제일기획,서비스업,24.80,2.10,...,102022308936,2.709281e+12,1.299866e+11,102269218895,NaN,NaN,NaN,3.325712e+12,2.481795e+11,1.675991e+11
82,003490,대한항공,27850.0,-650.0,-2.28,2641423.0,대한항공,운수창고업,25.71,1.07,...,-612921454979,1.184871e+13,-1.956209e+10,-383555365584,NaN,NaN,NaN,9.016825e+12,1.417969e+12,5.787820e+11
83,008930,한미사이언스,38150.0,-200.0,-0.52,2469940.0,한미사이언스,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,002380,KCC,233500.0,0.0,0.00,2464946.0,KCC,화학,9.91,1.15,...,326693597855,3.233043e+12,2.317429e+11,248992623676,3.246228e+12,1.989493e+11,446319780191,NaN,NaN,NaN
85,006360,GS건설,30500.0,-550.0,-1.77,2442983.0,GS건설,건설업,12.79,0.84,...,-22452682512,9.565758e+12,-9.354505e+11,-827346708179,9.568632e+12,1.760633e+11,94960950724,NaN,NaN,NaN
86,138930,BNK금융지주,7470.0,-190.0,-2.48,2434736.0,BNK금융지주,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,028670,팬오션,4460.0,-85.0,-1.87,2384179.0,팬오션,운수창고업,25.71,1.07,...,786078000000,2.682024e+12,-2.220910e+11,-1909683000000,5.417846e+12,-2.116760e+11,-463951000000,NaN,NaN,NaN
88,001450,현대해상,25900.0,-1050.0,-3.90,2315460.0,현대해상,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,047050,포스코인터내셔널,18350.0,-300.0,-1.61,2263934.0,포스코대우,유통업,9.30,0.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,011780,금호석유,76000.0,-1500.0,-1.94,2315545.0,금호석유,화학,9.91,1.15,...,88334747850,5.132132e+12,1.342290e+11,-42712970928,5.883690e+12,2.238028e+11,126109124946,NaN,NaN,NaN
91,008560,메리츠종금증권,3745.0,-45.0,-1.19,2311829.0,메리츠종금증권,증권,7.49,0.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,000080,하이트진로,28900.0,-100.0,-0.34,2026861.0,하이트진로,음식료품,10.99,1.13,...,21253791241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,007310,오뚜기,549000.0,-5000.0,-0.90,1979275.0,오뚜기,음식료품,10.99,1.13,...,94111327807,1.728175e+12,1.050757e+11,92241259915,1.686638e+12,1.086878e+11,75786100328,NaN,NaN,NaN
94,088350,한화생명,2290.0,-20.0,-0.87,1988934.0,한화생명,보험,10.41,0.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,069960,현대백화점,85900.0,2800.0,3.37,2010270.0,현대백화점,유통업,9.30,0.84,...,291023905000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,020150,일진머티리얼즈,43000.0,250.0,0.58,1982766.0,일진머티리얼즈,전기전자,5.49,0.98,...,-1900000000,3.499910e+11,-1.484300e+10,-8991000000,3.932290e+11,-6.842000e+09,-57211000000,NaN,NaN,NaN
97,009420,한올바이오파마,36450.0,150.0,0.41,1904171.0,한올바이오파마,의약품,89.40,4.62,...,-12658084909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,047040,대우건설,4660.0,-80.0,-1.69,1936801.0,대우건설,건설업,12.79,0.84,...,102110186625,8.782196e+12,-2.446644e+11,-718036005284,8.223433e+12,3.456866e+11,173028929706,NaN,NaN,NaN
99,017800,현대엘리베이,67600.0,-700.0,-1.02,1838675.0,현대엘리베이,기계,70.41,1.17,...,50419452905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,011790,SKC,50600.0,-400.0,-0.78,1899248.0,SKC,화학,9.91,1.15,...,43307997481,2.641403e+12,1.240027e+11,25737659251,2.629171e+12,1.447316e+11,31810661954,NaN,NaN,NaN
101,000880,한화,24350.0,-650.0,-2.60,1825245.0,한화,화학,9.91,1.15,...,-163026000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,051600,한전KPS,38550.0,-600.0,-1.53,1734750.0,한전KPS,건설업,12.79,0.84,...,168295607804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,012450,한화에어로스페이스,34700.0,-350.0,-1.00,1789132.0,한화에어로스페이스,운수장비,51.34,0.53,...,-118181869522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,010620,현대미포조선,44900.0,-1150.0,-2.50,1793402.0,현대미포조선,운수장비,51.34,0.53,...,-679259389000,NaN,NaN,NaN,NaN,NaN,NaN,2.887212e+12,-2.173254e+11,-1.601085e+11
105,004800,효성,76300.0,-2800.0,-3.54,1607719.0,효성,기타금융,NaN,NaN,...,291989964756,NaN,NaN,NaN,NaN,NaN,NaN,3.538943e+12,6.405627e+11,5.405865e+11
106,010120,LS산전,52600.0,-2000.0,-3.66,1578000.0,LS산전,전기전자,5.49,0.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,204320,만도,34900.0,-300.0,-0.85,1638803.0,만도,운수장비,51.34,0.53,...,47893247651,NaN,NaN,NaN,NaN,NaN,NaN,6.147433e+12,2.323120e+11,1.786158e+11
108,069620,대웅제약,136500.0,-1000.0,-0.73,1581567.0,대웅제약,의약품,89.40,4.62,...,30469955819,6.825080e+11,7.137163e+10,57974401214,6.690138e+11,3.688282e+10,33512863577,NaN,NaN,NaN
109,026960,동서,16750.0,-650.0,-3.74,1669975.0,동서,유통업,9.30,0.84,...,131013543380,4.703688e+11,5.096035e+10,126490087864,4.596820e+11,5.133287e+10,125452016052,NaN,NaN,NaN
110,001740,SK네트웍스,5900.0,-40.0,-0.67,1464307.0,SK네트웍스,유통업,9.30,0.84,...,,2.597536e+13,2.408235e+11,,2.793550e+13,2.515600e+11,,NaN,NaN,NaN
111,006260,LS,46900.0,-900.0,-1.88,1510180.0,LS,기타금융,NaN,NaN,...,86705000000,1.139358e+13,4.653470e+11,165153000000,1.188120e+13,4.476390e+11,213736000000,NaN,NaN,NaN
112,006280,녹십자,131000.0,-1500.0,-1.13,1530936.0,녹십자,의약품,89.40,4.62,...,86789122722,8.881682e+11,7.880846e+10,72027708210,8.117743e+11,7.435568e+10,55611788487,NaN,NaN,NaN
113,111770,영원무역,33650.0,-600.0,-1.75,1491081.0,영원무역,유통업,9.30,0.84,...,143317702438,1.108227e+12,1.607880e+11,121929362507,1.059149e+12,1.863027e+11,131669465691,NaN,NaN,NaN
114,010060,OCI,62800.0,200.0,0.32,1497740.0,OCI,화학,9.91,1.15,...,42334700000,2.238126e+12,-1.867455e+11,-287777262000,NaN,NaN,NaN,3.243997e+12,6.259849e+11,6.520758e+11
115,031430,신세계인터내셔날,220000.0,500.0,0.23,1570800.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,009240,한샘,66700.0,4500.0,7.23,1569713.0,한샘,유통업,9.30,0.84,...,86692476942,NaN,NaN,NaN,NaN,NaN,NaN,2.231221e+12,6.926426e+10,5.721819e+10
117,004370,농심,237000.0,-3500.0,-1.46,1441586.0,농심,음식료품,10.99,1.13,...,64454972212,2.086651e+12,9.260272e+10,86896539044,2.175711e+12,9.689195e+10,-9166417222,NaN,NaN,NaN
118,214320,이노션,70000.0,-900.0,-1.27,1400000.0,이노션,서비스업,24.80,2.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,120110,코오롱인더,49450.0,-300.0,-0.60,1334104.0,코오롱인더,화학,9.91,1.15,...,39640555089,5.261463e+12,2.316387e+11,113672188089,5.312951e+12,2.939525e+11,171148613586,NaN,NaN,NaN
120,011210,현대위아,48950.0,-1250.0,-2.49,1331199.0,현대위아,운수장비,51.34,0.53,...,439188902750,NaN,NaN,NaN,NaN,NaN,NaN,7.527739e+12,1.027250e+11,5.607100e+10
121,000240,한국테크놀로지그룹,14000.0,-400.0,-2.78,1302282.0,한국타이어월드와이드,기타금융,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,114090,GKL,19450.0,0.0,0.00,1203093.0,GKL,서비스업,24.80,2.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,064350,현대로템,15450.0,-150.0,-0.96,1313250.0,현대로템,운수장비,51.34,0.53,...,-15108710000,NaN,NaN,NaN,NaN,NaN,NaN,2.872512e+12,8.021796e+10,5.141160e+10
124,000990,DB하이텍,27900.0,300.0,1.09,1238721.0,DB하이텍,전기전자,5.49,0.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,000150,두산,68900.0,-1400.0,-1.99,1138492.0,두산,서비스업,24.80,2.10,...,33249466961,2.161606e+13,1.135179e+12,130167997406,2.385751e+13,7.873744e+11,201507512711,NaN,NaN,NaN
126,000670,영풍,646000.0,1000.0,0.16,1189958.0,영풍,철강금속,10.50,0.50,...,100584987718,3.273760e+12,1.575246e+11,234426916394,NaN,NaN,NaN,3.582075e+12,-2.678431e+10,1.700635e+11
127,001800,오리온홀딩스,17550.0,-250.0,-1.40,1099427.0,오리온홀딩스,기타금융,NaN,NaN,...,174297158567,2.485196e+12,2.594811e+11,160240858319,NaN,NaN,NaN,2.415059e+12,3.156974e+11,2.253283e+11
128,003240,태광산업,1065000.0,5000.0,0.47,1185771.0,태광산업,화학,9.91,1.15,...,122820168364,3.513353e+12,1.686005e+11,113939553791,NaN,NaN,NaN,2.591846e+12,3.552726e+11,3.183681e+11
129,003520,영진약품,6460.0,-170.0,-2.56,1181487.0,영진약품,의약품,89.40,4.62,...,909091950,1.566227e+11,6.916530e+09,11742329875,NaN,NaN,NaN,1.960672e+11,-1.387751e+10,-1.158246e+10
130,004000,롯데정밀화학,44100.0,-1050.0,-2.33,1137780.0,롯데정밀화학,화학,9.91,1.15,...,58682516778,1.314058e+12,-2.034363e+10,3340492457,NaN,NaN,NaN,1.780293e+12,2.445136e+11,5.854585e+11
131,294870,HDC현대산업개발,25400.0,-250.0,-0.97,1116031.0,HDC현대산업개발,건설업,12.79,0.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,005440,현대그린푸드,11650.0,-200.0,-1.69,1138257.0,현대그린푸드,유통업,9.30,0.84,...,97945207000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,014680,한솔케미칼,103500.0,-2500.0,-2.36,1169053.0,한솔케미칼,화학,9.91,1.15,...,21422845255,NaN,NaN,NaN,NaN,NaN,NaN,7.686882e+11,1.976846e+11,1.586709e+11
134,034020,두산중공업,5730.0,10.0,0.17,1158302.0,두산중공업,기계,70.41,1.17,...,-85475347180,1.920817e+13,9.580717e+11,18662825932,2.127406e+13,5.861515e+11,97475586606,NaN,NaN,NaN

In [ ]:
year_3_going = join_t4[(join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

,종목코드,종목명_x,업종명,종가,업종PER,업종PBR,PER,PBR,종가_2020,증가율
0,005930,삼성전자,전기전자,38750,5.49,0.98,6.46,1.38,55200.0,42.451613
1,000660,SK하이닉스,전기전자,60600,5.49,0.98,4.02,1.30,94700.0,56.270627
2,005490,POSCO,철강금속,237000,10.50,0.50,6.88,0.47,236000.0,-0.421941
3,028260,삼성물산,유통업,104000,9.30,0.84,26.81,0.88,107500.0,3.365385
4,051900,LG생활건강,화학,1081000,9.91,1.15,29.86,6.39,1266000.0,17.113784

In [ ]:
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

16,17,18년도 매년 영업이익 증가한 기업 갯수 : 34
16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : 1.67885385264962

In [ ]:
year_3_nogoing = join_t4[~((join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_nogoing_join = pd.merge(year_3_nogoing, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2020']- year_3_nogoing_join['종가'])/year_3_nogoing_join['종가'])*100
year_3_nogoing_join = year_3_nogoing_join[~year_3_nogoing_join['종가_2020'].isnull()]
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

16,17,18년도 매년 영업이익 증가한 기업 갯수 : 166
16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : -5.099764979339883

## 16,17,18년치 영업이익 감소 추세의 종목과 그 나머지 종목간 수익률 비교

In [ ]:
join_t4 = pd.merge(join_t3,result,how='left',on = '종목명')

In [ ]:
prices_2019_01 = pd.read_excel('../gdrive/MyDrive/stock/prices_2019_01.xlsx')[['종목코드','종목명','종가']]
prices_2019_01 = prices_2019_01.rename(columns = {'종가':'종가_2019'})

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
prices_2020_01 = pd.read_excel('../gdrive/MyDrive/stock/prices_2020_01.xlsx')[['종목코드','종목명','종가']]
prices_2020_01 = prices_2020_01.rename(columns = {'종가':'종가_2020'})
# prices_2020_01

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
year_3_going = join_t4[(join_t4['2016영업이익']>join_t4['2017영업이익']) & (join_t4['2017영업이익']>join_t4['2018영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2019_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2019']]
year_3_going_join = pd.merge(year_3_going_join, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2019','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가_2019'])/year_3_going_join['종가_2019'])*100
print('16,17,18년도 매년 영업이익이 감소한 기업의 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익이 감소한 기업의 평균 수익률 : {}'.format(average_returns))

16,17,18년도 매년 영업이익이 감소한 기업의 갯수 : 28
16,17,18년도 매년 영업이익이 감소한 기업의 평균 수익률 : -7.692157389201825

In [ ]:
year_3_going = join_t4[~((join_t4['2016영업이익']>join_t4['2017영업이익']) & (join_t4['2017영업이익']>join_t4['2018영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2019_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2019']]
year_3_going_join = pd.merge(year_3_going_join, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2019','종가_2020']]
year_3_going_join = year_3_going_join.loc[~((year_3_going_join['종가_2019'].isnull()) | (year_3_going_join['종가_2020'].isnull())) ]
# year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='한미사이언스')]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가_2019'])/year_3_going_join['종가_2019'])*100
print('16,17,18년도 매년 영업이익이 감소한 기업의 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익이 감소한 기업의 평균 수익률 : {}'.format(average_returns))

16,17,18년도 매년 영업이익이 감소한 기업의 갯수 : 171
16,17,18년도 매년 영업이익이 감소한 기업의 평균 수익률 : -3.0581706428343853

## 17,18,19년치 영업이익 감세 추세의 종목과 그 나머지 종목간 수익률 비교

In [ ]:
#17년도 주가와 18년도 주가를 비교
price_2020 = pd.read_excel('../gdrive/MyDrive/stock/prices_2020_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2020.columns = ['종목코드','종목명','종가_2020']
price_2021 = pd.read_excel('../gdrive/MyDrive/stock/prices_2021_01.xlsx',converters={'종목코드':str})[['종목코드','종목명','종가']]
price_2021.columns = ['종목코드','종목명','종가_2021']

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
year_3_going_join

,종목코드,종목명_x,업종명,종가,업종PER,업종PBR,PER,PBR,종목명_y,종가_2020,종목명,종가_2021,증가율
0,051910,LG화학,화학,337000,9.91,1.15,13.28,1.63,LG화학,314000.0,LG화학,889000.0,183.121019
1,017670,SK텔레콤,통신업,272500,8.89,0.92,7.45,1.23,SK텔레콤,234000.0,SK텔레콤,237000.0,1.282051
2,034730,SK,기타금융,252000,NaN,NaN,8.40,1.31,SK,258000.0,SK,249500.0,-3.294574
3,096770,SK이노베이션,화학,169000,9.91,1.15,7.49,0.88,SK이노베이션,146500.0,SK이노베이션,231000.0,57.679181
4,003550,LG,기타금융,68100,NaN,NaN,5.00,0.75,LG,71100.0,LG,96900.0,36.286920
5,090430,아모레퍼시픽,화학,193500,9.91,1.15,33.88,3.22,아모레퍼시픽,207500.0,아모레퍼시픽,203000.0,-2.168675
6,010950,S-Oil,화학,91300,9.91,1.15,8.53,1.56,S-Oil,91900.0,S-Oil,70300.0,-23.503808
7,011170,롯데케미칼,화학,275000,9.91,1.15,4.19,0.82,롯데케미칼,218500.0,롯데케미칼,279500.0,27.917620
8,030200,KT,통신업,30400,8.89,0.92,15.62,0.68,KT,26700.0,KT,23800.0,-10.861423
9,032640,LG유플러스,통신업,17950,8.89,0.92,14.33,1.50,LG유플러스,13850.0,LG유플러스,11850.0,-14.440433
10,034220,LG디스플레이,전기전자,17800,5.49,0.98,3.53,0.44,LG디스플레이,16350.0,LG디스플레이,19050.0,16.513761
11,004020,현대제철,철강금속,44000,10.50,0.50,8.07,0.35,현대제철,31200.0,현대제철,41200.0,32.051282
12,023530,롯데쇼핑,유통업,202500,9.30,0.84,NaN,0.45,롯데쇼핑,135500.0,롯데쇼핑,101500.0,-25.092251
13,139480,이마트,유통업,180000,9.30,0.84,8.33,0.61,이마트,125500.0,이마트,151500.0,20.717131
14,012750,에스원,서비스업,103000,24.80,2.10,24.30,3.24,에스원,92500.0,에스원,85100.0,-8.000000
15,002380,KCC,화학,308500,9.91,1.15,72.61,0.56,KCC,233500.0,KCC,199000.0,-14.775161
16,003490,대한항공,운수창고업,32400,25.71,1.07,3.75,0.86,대한항공,27850.0,대한항공,27650.0,-0.718133
17,000100,유한양행,의약품,209000,89.40,4.62,22.40,1.70,유한양행,231500.0,유한양행,79200.0,-65.788337
18,010060,OCI,화학,106500,9.91,1.15,10.81,0.76,OCI,62800.0,OCI,98500.0,56.847134
19,000880,한화,화학,31000,9.91,1.15,5.52,0.67,한화,24350.0,한화,29350.0,20.533881
20,064350,현대로템,운수장비,26750,51.34,0.53,NaN,1.69,현대로템,15450.0,현대로템,19650.0,27.184466
21,069960,현대백화점,유통업,87700,9.30,0.84,7.80,0.52,현대백화점,85900.0,현대백화점,72000.0,-16.181607
22,020150,일진머티리얼즈,전기전자,39400,5.49,0.98,38.40,3.42,일진머티리얼즈,43000.0,일진머티리얼즈,52500.0,22.093023
23,026960,동서,유통업,17650,9.30,0.84,14.31,1.44,동서,16750.0,동서,33800.0,101.791045
24,006260,LS,기타금융,48600,NaN,NaN,4.55,0.57,LS,46900.0,LS,72500.0,54.584222
25,009240,한샘,유통업,67700,9.30,0.84,12.51,3.14,한샘,66700.0,한샘,105500.0,58.170915
26,006280,녹십자,의약품,136500,89.40,4.62,29.26,1.53,녹십자,131000.0,녹십자,475000.0,262.595420
27,004370,농심,음식료품,251000,10.99,1.13,16.01,0.83,농심,237000.0,농심,296500.0,25.105485
28,005250,녹십자홀딩스,서비스업,24400,24.80,2.10,25.55,1.49,녹십자홀딩스,21800.0,녹십자홀딩스,53600.0,145.871560
29,185750,종근당,의약품,100000,89.40,4.62,19.19,2.57,종근당,95200.0,종근당,232500.0,144.222689
30,069260,휴켐스,화학,23400,9.91,1.15,7.84,1.65,휴켐스,20600.0,휴켐스,26600.0,29.126214
31,103140,풍산,철강금속,26550,10.50,0.50,4.94,0.57,풍산,23300.0,풍산,28200.0,21.030043
32,014820,동원시스템즈,화학,27250,9.91,1.15,9.88,1.82,동원시스템즈,28650.0,동원시스템즈,37450.0,30.715532

In [ ]:
year_3_going = join_t4[(join_t4['2017영업이익']>join_t4['2018영업이익']) & (join_t4['2018영업이익']>join_t4['2019영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, price_2020, how='left', on = '종목코드')#[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join = pd.merge(year_3_going_join, price_2021, how='left', on = '종목코드')
year_3_going_join = year_3_going_join[~((year_3_going_join['종가_2021'].isnull()) | (year_3_going_join['종가_2020'].isnull()))]
year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='녹십자')]
year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='녹십자홀딩스')]
year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='종근당')]
year_3_going_join = year_3_going_join.loc[~(year_3_going_join['종목명_x']=='LG화학')]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2021']- year_3_going_join['종가_2020'])/year_3_going_join['종가_2020'])*100
print('17,18,19년도 매년 영업이익 감소한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('17,18,19년도 매년 영업이익 감소한 기업의 평균 수익률 : {}'.format(average_returns))

17,18,19년도 매년 영업이익 감소한 기업 갯수 : 29
17,18,19년도 매년 영업이익 감소한 기업의 평균 수익률 : 15.682948450743034

In [ ]:
year_3_going = join_t4[~((join_t4['2017영업이익']>join_t4['2018영업이익']) & (join_t4['2018영업이익']>join_t4['2019영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, price_2020, how='left', on = '종목코드')#[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join = pd.merge(year_3_going_join, price_2021, how='left', on = '종목코드')
year_3_going_join = year_3_going_join[~((year_3_going_join['종가_2021'].isnull()) | (year_3_going_join['종가_2020'].isnull()))]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2021']- year_3_going_join['종가_2020'])/year_3_going_join['종가_2020'])*100
print('17,18,19년도 매년 영업이익 감소한 기업을 제외한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('17,18,19년도 매년 영업이익 감소한 기업을 제외한 기업의 평균 수익률 : {}'.format(average_returns))

17,18,19년도 매년 영업이익 감소한 기업을 제외한 기업 갯수 : 140
17,18,19년도 매년 영업이익 감소한 기업을 제외한 기업의 평균 수익률 : 22.932767309372068

In [ ]:
prices_2021_01 = pd.read_csv('../gdrive/MyDrive/stock/prices_2021_01.csv',encoding='cp949',converters = {'종목코드':str})[['종목코드','종목명','종가']]
prices_2021_01 = prices_2021_01.rename(columns = {'종가':"종가_2021"})
prices_2021_01.head()

     종목코드       종목명  종가_2021
0  005930      삼성전자    83000
1  000660    SK하이닉스   126000
2  051910      LG화학   889000
3  207940  삼성바이오로직스   829000
4  035420     NAVER   293000

In [ ]:
result = pd.read_csv('../gdrive/MyDrive/stock/final_result.csv',index_col=0)
result = result.reset_index()
result = result.rename(columns = {'index':'종목명'})
join_t1 = pd.merge(prices_2020_01, result,how='left',on='종목명')
year_3_going = join_t1[(join_t1['2017영업이익']<join_t1['2018영업이익']) & (join_t1['2018영업이익']<join_t1['2019영업이익'])][['종목코드','종목명','종가']]
year_3_going_join = pd.merge(year_3_going, prices_2021_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '종가', '종가_2021']]
year_3_going_join
year_3_going_join['증가율'] = ((year_3_going_join['종가_2021']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('17,18,19년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('17,18,19년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

17,18,19년도 매년 영업이익 증가한 기업 갯수 : 32
17,18,19년도 매년 영업이익 증가한 기업의 평균 수익률 : 9.545505909713494

In [ ]:
year_3_nogoing = join_t1[~((join_t1['2017영업이익']<join_t1['2018영업이익']) & (join_t1['2018영업이익']<join_t1['2019영업이익']))][['종목코드','종목명','종가']]
year_3_nogoing_join = pd.merge(year_3_nogoing, prices_2021_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '종가', '종가_2021']]
year_3_going_join
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2021']- year_3_nogoing_join['종가'])/year_3_nogoing_join['종가'])*100
year_3_nogoing_join = year_3_nogoing_join.loc[~year_3_nogoing_join['증가율'].isnull()] #종가2021이 없는 주식은 제외
print('17,18,19년도 매년 영업이익 증가한 기업을 제외한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('17,18,19년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : {}'.format(average_returns))

17,18,19년도 매년 영업이익 증가한 기업을 제외한 기업 갯수 : 146
17,18,19년도 매년 영업이익 증가한 기업을 제외한 기업의 평균 수익률 : 27.505365946166467

In [ ]:
year_3_nogoing_join

       종목코드        종목명_x         종가   종가_2021         증가율
0    005930         삼성전자    55200.0   83000.0   50.362319
1    000660       SK하이닉스    94700.0  126000.0   33.051742
2    035420        NAVER   182500.0  293000.0   60.547945
3    207940     삼성바이오로직스   428500.0  829000.0   93.465578
4    005380          현대차   118000.0  207500.0   75.847458
5    068270         셀트리온   180000.0  347500.0   93.055556
6    051910         LG화학   314000.0  889000.0  183.121019
7    005490        POSCO   236000.0  273000.0   15.677966
8    028260         삼성물산   107500.0  144000.0   33.953488
9    055550         신한지주    42600.0   31550.0  -25.938967
10   105560         KB금융    46550.0   42450.0   -8.807734
11   017670        SK텔레콤   234000.0  237000.0    1.282051
12   015760         한국전력    28500.0   26900.0   -5.614035
13   034730           SK   258000.0  249500.0   -3.294574
14   000270          기아차    42500.0   64000.0   50.588235
15   006400        삼성SDI   232000.0  671000.0  189.224138
16   018260      삼성에스디에스   192000.0  186000.0   -3.125000
17   032830         삼성생명    73100.0   78000.0    6.703146
18   096770      SK이노베이션   146500.0  231000.0   57.679181
19   035720          카카오   152500.0  396000.0  159.672131
20   033780         KT&G    92500.0   82100.0  -11.243243
21   003550           LG    71100.0   96900.0   36.286920
22   090430       아모레퍼시픽   207500.0  203000.0   -2.168675
23   036570        엔씨소프트   541000.0  978000.0   80.776340
24   066570         LG전자    71000.0  142000.0  100.000000
25   000810         삼성화재   238500.0  183000.0  -23.270440
26   086790       하나금융지주    35950.0   33450.0   -6.954103
27   010950        S-Oil    91900.0   70300.0  -23.503808
28   009150         삼성전기   126500.0  180000.0   42.292490
29   009540       한국조선해양   125500.0  110000.0  -12.350598
30   316140       우리금융지주    11400.0    9510.0  -16.578947
31   010130         고려아연   424000.0  401000.0   -5.424528
32   251270          넷마블    90300.0  131000.0   45.071982
33   011170        롯데케미칼   218500.0  279500.0   27.917620
34   030200           KT    26700.0   23800.0  -10.861423
35   002790         아모레G    83200.0   54000.0  -35.096154
36   024110         기업은행    11550.0    8620.0  -25.367965
37   021240        웅진코웨이    90000.0   73200.0  -18.666667
38   035250         강원랜드    29250.0   23350.0  -20.170940
39   032640       LG유플러스    13850.0   11850.0  -14.440433
40   034220      LG디스플레이    16350.0   19050.0   16.513761
41   018880        한온시스템    10800.0   16500.0   52.777778
42   267250      현대중공업지주   330000.0  276500.0  -16.212121
43   086280       현대글로비스   138500.0  190000.0   37.184116
44   006800       미래에셋대우     7450.0    9500.0   27.516779
45   078930           GS    50000.0   37800.0  -24.400000
46   010140        삼성중공업     7220.0    7300.0    1.108033
47   000720         현대건설    41200.0   38250.0   -7.160194
48   029780         삼성카드    37450.0   31250.0  -16.555407
49   004020         현대제철    31200.0   41200.0   32.051282
50   161390  한국타이어앤테크놀로지    32450.0   37400.0   15.254237
51   071050       한국금융지주    70900.0   82300.0   16.078984
52   023530         롯데쇼핑   135500.0  101500.0  -25.092251
53   005830       DB손해보험    50100.0   42750.0  -14.670659
54   139480          이마트   125500.0  151500.0   20.717131
55   012750          에스원    92500.0   85100.0   -8.000000
56   005940       NH투자증권    12500.0   11200.0  -10.400000
57   016360         삼성증권    37850.0   40800.0    7.793923
58   241560         두산밥캣    33750.0   29400.0  -12.888889
59   011070        LG이노텍   139000.0  192500.0   38.489209
60   081660        휠라코리아    52300.0   42850.0  -18.068834
61   000210         대림산업    87800.0   83000.0   -5.466970
62   009830        한화케미칼    18500.0   49200.0  165.945946
63   000100         유한양행   231500.0   79200.0  -65.788337
64   282330       BGF리테일   168500.0  132000.0  -21.661721
65   042660       대우조선해양    27350.0   27850.0    1.828154
66   003410         쌍용양회     5550.0    6580.0   18.558559
67   003490         대한항공    27850.0   27650.0   -0.718133
68   008930       한미사이언스    38150.0   76000.0   99.213630
69   002380          KCC   233500.0  199000.0  -14.775161
70   006360         GS건설    30500.0   38050.0   24.754098
71   138930      BNK금융지주     7470.0    5560.0  -25.568942
72   001450         현대해상    25900.0   22400.0  -13.513514
73   011780         금호석유    76000.0  151000.0   98.684211
74   008560      메리츠종금증권     3745.0    3615.0   -3.471295
75   000080        하이트진로    28900.0   32000.0   10.726644
76   007310          오뚜기   549000.0  567000.0    3.278689
77   088350         한화생명     2290.0    2340.0    2.183406
78   069960        현대백화점    85900.0   72000.0  -16.181607
79   020150      일진머티리얼즈    43000.0   52500.0   22.093023
80   047040         대우건설     4660.0    5150.0   10.515021
81   017800       현대엘리베이    67600.0   40900.0  -39.497041
82   011790          SKC    50600.0  101500.0  100.592885
83   000880           한화    24350.0   29350.0   20.533881
84   051600        한전KPS    38550.0   29200.0  -24.254215
85   012450    한화에어로스페이스    34700.0   29800.0  -14.121037
86   010620       현대미포조선    44900.0   48250.0    7.461024
87   010120         LS산전    52600.0   65000.0   23.574144
88   069620         대웅제약   136500.0  172000.0   26.007326
89   026960           동서    16750.0   33800.0  101.791045
90   001740       SK네트웍스     5900.0    5040.0  -14.576271
91   006260           LS    46900.0   72500.0   54.584222
92   006280          녹십자   131000.0  475000.0  262.595420
93   010060          OCI    62800.0   98500.0   56.847134
94   031430     신세계인터내셔날   220000.0  161000.0  -26.818182
95   009240           한샘    66700.0  105500.0   58.170915
96   004370           농심   237000.0  296500.0   25.105485
97   214320          이노션    70000.0   60900.0  -13.000000
98   120110        코오롱인더    49450.0   41350.0  -16.380182
99   011210         현대위아    48950.0   69500.0   41.981614
100  000240    한국테크놀로지그룹    14000.0   14400.0    2.857143
101  114090          GKL    19450.0   16450.0  -15.424165
102  064350         현대로템    15450.0   19650.0   27.184466
103  000990        DB하이텍    27900.0   51100.0   83.154122
104  000150           두산    68900.0   52000.0  -24.528302
105  000670           영풍   646000.0  540000.0  -16.408669
106  003240         태광산업  1065000.0  802000.0  -24.694836
107  003520         영진약품     6460.0    7910.0   22.445820
108  004000       롯데정밀화학    44100.0   55100.0   24.943311
109  294870    HDC현대산업개발    25400.0   26300.0    3.543307
110  005440       현대그린푸드    11650.0    8760.0  -24.806867
111  042670      두산인프라코어     5500.0    7910.0   43.818182
112  005250       녹십자홀딩스    21800.0   53600.0  145.871560
113  010780       아이에스동서    32800.0   54600.0   66.463415
114  185750          종근당    95200.0  232500.0  144.222689
116  057050        현대홈쇼핑    79800.0   79500.0   -0.375940
117  002350        넥센타이어     8900.0    6100.0  -31.460674
118  003000         부광약품    14050.0   28950.0  106.049822
119  049770        동원F&B   223500.0  176500.0  -21.029083
120  069260          휴켐스    20600.0   26600.0   29.126214
122  285130        SK케미칼    66700.0  396000.0  493.703148
123  005610        SPC삼립    86200.0   70300.0  -18.445476
124  006650         대한유화   116000.0  234000.0  101.724138
126  014820       동원시스템즈    28650.0   37450.0   30.715532
127  018250         애경산업    29350.0   24600.0  -16.183986
128  052690         한전기술    20000.0   18100.0   -9.500000
129  071840       롯데하이마트    30600.0   30700.0    0.326797
130  079160       CJ CGV    34400.0   26200.0  -23.837209
131  079550       LIG넥스원    31750.0   30700.0   -3.307087
132  093370           후성     8130.0   12350.0   51.906519
133  105630         한세실업    17350.0   16750.0   -3.458213
134  115390          락앤락    14000.0   10100.0  -27.857143
135  000070        삼양홀딩스    67300.0   73800.0    9.658247
137  001060       JW중외제약    29900.0   36200.0   21.070234
138  103140           풍산    23300.0   28200.0   21.030043
139  012630          HDC    10900.0   11000.0    0.917431
140  064960       S&T모티브    43600.0   55700.0   27.752294
141  001120         LG상사    15000.0   26750.0   78.333333
142  001230         동국제강     5850.0    8680.0   48.376068
145  004490         세방전지    36650.0   75000.0  104.638472
146  005180          빙그레    56300.0   57100.0    1.420959
147  006120      SK디스커버리    26400.0   66100.0  150.378788
148  145990          삼양사    50000.0   60000.0   20.000000
154  108670       LG하우시스    54900.0   78700.0   43.351548
155  006390      한일현대시멘트    30250.0   29550.0   -2.314050
163  007570         일양약품    22850.0   63400.0  177.461707

In [ ]:
year_3_going = join_t4[(join_t4['2017영업이익']<join_t4['2018영업이익']) & (join_t4['2018영업이익']<join_t4['2019영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

KeyError: ignored

In [ ]:
pd.merge(prices_2020_01, join_t4, how='left',on='종목코드')

In [ ]:
year_3_going = join_t4[(join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익'])][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_going_join = pd.merge(year_3_going, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_going_join['증가율'] = ((year_3_going_join['종가_2020']- year_3_going_join['종가'])/year_3_going_join['종가'])*100
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

KeyError: ignored

In [ ]:
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_going_join)))
average_returns = year_3_going_join['증가율'].values.sum()/len(year_3_going_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

In [ ]:
year_3_nogoing = join_t4[~((join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익']))][['종목코드','종목명','업종명','종가','업종PER','업종PBR','PER','PBR']]
year_3_nogoing_join = pd.merge(year_3_nogoing, prices_2020_01, how='left', on = '종목코드')[['종목코드', '종목명_x', '업종명', '종가', '업종PER', '업종PBR', 'PER', 'PBR','종가_2020']]
year_3_nogoing_join['증가율'] = ((year_3_nogoing_join['종가_2020']- year_3_nogoing_join['종가'])/year_3_nogoing_join['종가'])*100
year_3_nogoing_join = year_3_nogoing_join[~year_3_nogoing_join['종가_2020'].isnull()]
print('16,17,18년도 매년 영업이익 증가한 기업 갯수 : {}'.format(len(year_3_nogoing_join)))
average_returns = year_3_nogoing_join['증가율'].values.sum()/len(year_3_nogoing_join)
print('16,17,18년도 매년 영업이익 증가한 기업의 평균 수익률 : {}'.format(average_returns))

## 업종 PER + 16,17,18년도 영업이익 증가추세 종목 필터링

In [ ]:
ls -al ../gdrive/MyDrive/PER_Provement/price_per

total 730
-rw------- 1 root root 74132 Mar 26 10:43 20110103.xlsx
-rw------- 1 root root 75303 Mar 26 10:19 20120102.xlsx
-rw------- 1 root root 74244 Mar 26 10:22 20130102.xlsx
-rw------- 1 root root 73539 Mar 26 10:23 20140102.xlsx
-rw------- 1 root root 72700 Mar 26 10:23 20150102.xlsx
-rw------- 1 root root 73468 Mar 26 10:23 20160104.xlsx
-rw------- 1 root root 73723 Mar 26 10:24 20170102.xlsx
-rw------- 1 root root 74665 Mar 26 10:24 20180102.xlsx
-rw------- 1 root root 76074 Mar 26 10:24 20190102.xlsx
-rw------- 1 root root 76822 Mar 26 10:24 20200102.xlsx

In [ ]:
df = pd.read_excel('../gdrive/MyDrive/PER_Provement/price_per/20200102.xlsx')[['종목코드','종목명','종가','PER']]

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
sales_per = join_t4[(join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익']) & (join_t3['업종PER']>join_t3['PER'])]

In [ ]:
sales_per

,종목코드,종목명,업종명,업종PER,업종PBR,업종배당수익률,종가,EPS,PER,BPS,...,2014당기순이익,2013매출액,2013영업이익,2013당기순이익,2012매출액,2012영업이익,2012당기순이익,2021매출액,2021영업이익,2021당기순이익
1,000660,SK하이닉스,전기전자,5.49,0.98,1.93,60600,15073.0,4.02,46449.0,...,582424000000,1.416510e+13,8.864587e+12,505870000000,1.016221e+13,8.550989e+12,62910000000,NaN,NaN,NaN
8,005490,POSCO,철강금속,10.50,0.50,2.52,237000,34464.0,6.88,501600.0,...,556659145957,6.186465e+13,2.996134e+12,1355180337664,NaN,NaN,NaN,7.633235e+13,9.238089e+12,7.195890e+12
29,036570,엔씨소프트,서비스업,24.80,2.10,1.25,467000,20756.0,22.50,124037.0,...,227519296162,7.566557e+11,2.052352e+11,158695768295,7.535200e+11,1.512520e+11,153666725549,NaN,NaN,NaN
48,021240,코웨이,서비스업,24.80,2.10,1.25,74400,4484.0,16.59,13128.0,...,249668412108,2.118342e+12,3.390323e+11,245074651953,1.992838e+12,2.261465e+11,94042698014,NaN,NaN,NaN
49,128940,한미약품,의약품,89.40,4.62,0.19,450500,5276.0,85.39,61358.0,...,43295070634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,042660,대우조선해양,운수장비,51.34,0.53,1.77,33300,7141.0,4.66,31816.0,...,-852747122121,1.458483e+13,-1.010035e+12,-920418515185,NaN,NaN,NaN,4.486586e+12,-1.754651e+12,-1.699829e+12
87,030000,제일기획,서비스업,24.80,2.10,1.25,22300,1255.0,17.77,7354.0,...,102022308936,2.709281e+12,1.299866e+11,102269218895,NaN,NaN,NaN,3.325712e+12,2.481795e+11,1.675991e+11
90,028670,팬오션,운수창고업,25.71,1.07,1.03,4445,268.0,16.59,4469.0,...,786078000000,2.682024e+12,-2.220910e+11,-1909683000000,5.417846e+12,-2.116760e+11,-463951000000,NaN,NaN,NaN
96,047040,대우건설,건설업,12.79,0.84,1.05,5440,630.0,8.63,5396.0,...,102110186625,8.782196e+12,-2.446644e+11,-718036005284,8.223433e+12,3.456866e+11,173028929706,NaN,NaN,NaN
113,003240,태광산업,화학,9.91,1.15,2.09,1334000,164917.0,8.09,2430678.0,...,122820168364,3.513353e+12,1.686005e+11,113939553791,NaN,NaN,NaN,2.591846e+12,3.552726e+11,3.183681e+11
119,051600,한전KPS,건설업,12.79,0.84,1.05,32400,3021.0,10.72,20113.0,...,168295607804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,010780,아이에스동서,비금속광물,14.10,0.94,2.46,29800,6355.0,4.69,34537.0,...,50427361737,6.847643e+11,5.583730e+10,22553869069,6.465883e+11,3.680397e+10,6013758533,NaN,NaN,NaN

In [ ]:
prices_2021 = pd.read_excel('../gdrive/MyDrive/stock/2021_12_30_prices.xlsx')[['종목코드','종목명','종가']]

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
# per이 업종평균 per보다 낮고 & 3년간 영업이익 증가(16,17,18)
merge1 = pd.merge(sales_per, df, how='left', on = '종목코드')[['종목명_x','업종명','PER_x','업종PER','종가_x','종가_y']]
merge1.columns = ['종목명','업종명','PER','업종PER','종가_2019','종가_2020']
merge1['증가율'] = ((merge1['종가_2020']-merge1['종가_2019'])/merge1['종가_2020'])*100
merge2 = pd.merge(merge1,prices_2021,how='left',on='종목명')[['종목명','업종명','PER','업종PER','종가_2019','종가_2020','종가']]
merge2.columns = ['종목명','업종명','PER','업종PER','종가_2019','종가_2020','종가_2021_12']
merge2['3년간증가율'] = ((merge2['종가_2021_12']-merge2['종가_2019'])/merge2['종가_2019'])*100
merge2

       종목명    업종명    PER  업종PER  종가_2019    종가_2020  종가_2021_12      3년간증가율
0   SK하이닉스   전기전자   4.02   5.49    60600    94700.0    131000.0  116.171617
1    POSCO   철강금속   6.88  10.50   237000   236000.0    274500.0   15.822785
2    엔씨소프트   서비스업  22.50  24.80   467000   541000.0    643000.0   37.687366
3      코웨이   서비스업  16.59  24.80    74400    90000.0     74400.0    0.000000
4     한미약품    의약품  85.39  89.40   450500   293500.0    276000.0  -38.734739
5   대우조선해양   운수장비   4.66  51.34    33300    27350.0     23050.0  -30.780781
6     제일기획   서비스업  17.77  24.80    22300    23300.0     22850.0    2.466368
7      팬오션  운수창고업  16.59  25.71     4445     4460.0      5410.0   21.709786
8     대우건설    건설업   8.63  12.79     5440     4660.0      5770.0    6.066176
9     태광산업     화학   8.09   9.91  1334000  1065000.0   1043000.0  -21.814093
10   한전KPS    건설업  10.72  12.79    32400    38550.0     38550.0   18.981481
11  아이에스동서  비금속광물   4.69  14.10    29800    32800.0     44250.0   48.489933

In [ ]:
merge2['3년간증가율'].sum()/len(merge2)

14.6721583377973

In [ ]:
# per이 업종대비 낮고 & 3년간 영업이익 감소(16,17,18)
per_sales1 = join_t4[(join_t4['2016영업이익']>join_t4['2017영업이익']) & (join_t4['2017영업이익']>join_t4['2018영업이익']) & (join_t3['업종PER']>join_t3['PER'])]
merge3 = pd.merge(per_sales1, df, how='left', on = '종목코드')[['종목명_x','업종명','PER_x','업종PER','종가_x','종가_y']]
merge3.columns = ['종목명','업종명','PER','업종PER','종가_2019','종가_2020']
merge3['증가율'] = ((merge3['종가_2020']-merge3['종가_2019'])/merge3['종가_2020'])*100
merge4 = pd.merge(merge3,prices_2021,how='left',on='종목명')[['종목명','업종명','PER','업종PER','종가_2019','종가_2020','종가']]
merge4.columns = ['종목명','업종명','PER','업종PER','종가_2019','종가_2020','종가_2021_12']
merge4['3년간증가율'] = ((merge4['종가_2021_12']-merge4['종가_2019'])/merge4['종가_2019'])*100
merge4

        종목명    업종명    PER  업종PER  종가_2019   종가_2020  종가_2021_12     3년간증가율
0       현대차   운수장비   7.60  51.34   114000  118000.0    209000.0  83.333333
1   SK이노베이션     화학   7.49   9.91   169000  146500.0    238500.0  41.124260
2     S-Oil     화학   8.53   9.91    91300   91900.0     85700.0  -6.133625
3      강원랜드   서비스업  14.31  24.80    30900   29250.0     24050.0 -22.168285
4   LG디스플레이   전기전자   3.53   5.49    17800   16350.0     24600.0  38.202247
5      현대제철   철강금속   8.07  10.50    44000   31200.0     41000.0  -6.818182
6       이마트    유통업   8.33   9.30   180000  125500.0    151000.0 -16.111111
7    현대글로비스  운수창고업   6.92  25.71   125500  138500.0    168000.0  33.864542
8       에스원   서비스업  24.30  24.80   103000   92500.0     73900.0 -28.252427
9      대한항공  운수창고업   3.75  25.71    32400   27850.0     29350.0  -9.413580
10     유한양행    의약품  22.40  89.40   209000  231500.0     62100.0 -70.287081
11   현대미포조선   운수장비   5.35  51.34    58800   44900.0     70000.0  19.047619
12    넥센타이어     화학   7.34   9.91     9000    8900.0      6820.0 -24.222222
13   동원시스템즈     화학   9.88   9.91    27250   28650.0     51200.0  87.889908
14      에스엘   운수장비   7.19  51.34    20200   17950.0     31200.0  54.455446

In [ ]:
merge4['3년간증가율'].sum()/len(merge4)

11.634056095874145

In [ ]:
# per이 업종대비 낮고 & 3년간 영업이익 연속해서 증가한 기업 제외
per_sales1 = join_t4[~((join_t4['2016영업이익']<join_t4['2017영업이익']) & (join_t4['2017영업이익']<join_t4['2018영업이익'])) & (join_t3['업종PER']>join_t3['PER'])]
merge3 = pd.merge(per_sales1, df, how='left', on = '종목코드')[['종목명_x','업종명','PER_x','업종PER','종가_x','종가_y']]
merge3.columns = ['종목명','업종명','PER','업종PER','종가_2019','종가_2020']
merge3['증가율'] = ((merge3['종가_2020']-merge3['종가_2019'])/merge3['종가_2020'])*100
merge4 = pd.merge(merge3,prices_2021,how='left',on='종목명')[['종목명','업종명','PER','업종PER','종가_2019','종가_2020','종가']]
merge4.columns = ['종목명','업종명','PER','업종PER','종가_2019','종가_2020','종가_2021_12']
merge4['3년간증가율'] = ((merge4['종가_2021_12']-merge4['종가_2019'])/merge4['종가_2019'])*100
merge4.head()
print(len(merge4))

58

In [ ]:
merge4['3년간증가율'].sum()/len(merge4)

11.2899740567988

### 배당수익률이 좋은 기업들 SORT 해보기

In [ ]:
ls -al ../gdrive/MyDrive/stock/

total 533
drwx------ 2 root root   4096 Mar 25 06:16 재무제표/
-rw------- 1 root root  86539 Mar 26 03:02 2021_12_30_prices.xlsx
-rw------- 1 root root  56731 Mar 24 04:30 final_result.csv
-rw------- 1 root root  11139 Mar 15 07:22 kospi_200_20190102.csv
-rw------- 1 root root  14025 Mar 30 06:27 kospi_200_prices_2020_01.xlsx
-rw------- 1 root root   2831 Mar 15 01:08 kospi_avg_upjong_20190102.csv
-rw------- 1 root root 175683 Mar 15 01:05 kospi_data_20190102.csv
-rw------- 1 root root  13931 Mar 30 06:15 prices_2018_01.xlsx
-rw------- 1 root root  82845 Mar 30 06:04 prices_2019_01.xlsx
-rw------- 1 root root  84053 Mar 30 05:23 prices_2020_01.xlsx
-rw------- 1 root root  11069 Mar 30 06:50 prices_2021_01.csv

## PER,PBR,배당수익률과 주가상승 수익률간

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201012.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201112.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a = a[~(a['배당수익률_x']==0)]
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2010_dividend_returns_corr.csv',encoding='cp949')

In [ ]:
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).corr()

              PER       PBR   배당수익률_x       수익률
PER      1.000000  0.056165 -0.084961  0.018120
PBR      0.056165  1.000000 -0.314253 -0.064223
배당수익률_x -0.084961 -0.314253  1.000000  0.067918
수익률      0.018120 -0.064223  0.067918  1.000000

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201012.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201112.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a = a[~(a['배당수익률_x']==0)]
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2011_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201112.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201212.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a = a[~(a['배당수익률_x']==0)]
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2011_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201212.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201312.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2012_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201312.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201412.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2013_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201412.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201512.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2014_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201512.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201612.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2015_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201612.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201712.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2016_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201712.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201812.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2017_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201812.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201912.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2018_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_201912.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_202012.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2019_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_202012.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_202112.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2020_returns_corr.csv',encoding='cp949')

In [ ]:
dividend_2010 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_202012.csv',encoding='cp949')[['종목코드', '종목명', '종가', 'PER','PBR','배당수익률']].sort_values('배당수익률')
dividend_2011 = pd.read_csv('../gdrive/MyDrive/stock/dividend/dividend_202112.csv',encoding='cp949')[['종목코드', '종목명', '종가', '배당수익률']].sort_values('배당수익률')
a = pd.merge(dividend_2010,dividend_2011, how='left', on ='종목코드')[['종목코드','종목명_x','종가_x','PER','PBR','배당수익률_x','종가_y']]
a['수익률'] = (a['종가_y']-a['종가_x'])/a['종가_x']*100
a = a.loc[~a['수익률'].isnull()] #종가 없는 것들은 삭제
a[['PER','PBR','배당수익률_x','수익률']].dropna(axis=0).to_csv('2020_returns_corr.csv',encoding='cp949')

# 업종 PER보다 낮은 종목들의 주가가 실제로 3년간 어느정도로 상승하였는지 확인

In [ ]:
ls -al ../gdrive/MyDrive/stock/

total 331
drwx------ 2 root root   4096 Mar 25 06:16 재무제표/
-rw------- 1 root root  86539 Mar 26 03:00 2019_12_30_prices.xlsx
-rw------- 1 root root  56731 Mar 24 04:30 final_result.csv
-rw------- 1 root root  11139 Mar 15 07:22 kospi_200_20190102.csv
-rw------- 1 root root   2831 Mar 15 01:08 kospi_avg_upjong_20190102.csv
-rw------- 1 root root 175683 Mar 15 01:05 kospi_data_20190102.csv

In [ ]:
prices_2021 = pd.read_excel('../gdrive/MyDrive/stock/2021_12_30_prices.xlsx')[['종목코드','종목명','종가']]
prices_2021.columns = ['종목코드','종목명','종가_2021']

/usr/local/lib/python3.7/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
per_lower = join_t3.loc[join_t3['업종PER']>join_t3['PER']]
per_lower = pd.merge(per_lower,prices_2021,how='left',on='종목코드')[['종목명_x','업종PER','PER','종가','종가_2021']]
per_lower['증가율'] = np.round(((per_lower['종가_2021']-per_lower['종가'])/per_lower['종가'])*100,2)
per_lower = per_lower.sort_values('PER')

70

In [ ]:
def x10(x):
  if x>0:
    return 1
  else:
    return 0

In [ ]:
per_lower['상승여부'] = per_lower['증가율'].apply(x10)

In [ ]:
per_lower['증가율'].sum()/len(per_lower) #  업종 PER 보다 낮았던 종목들의 3년 평균 주식증가율

17.48642857142857

In [ ]:
per_higher = join_t3.loc[join_t3['업종PER']<join_t3['PER']]
per_higher = pd.merge(per_higher,prices_2021,how='left',on='종목코드')[['종목명_x','업종PER','PER','종가','종가_2021']]
per_higher['증가율'] = np.round(((per_higher['종가_2021']-per_higher['종가'])/per_higher['종가'])*100,2)
per_higher = per_higher.sort_values('PER')
per_higher['상승여부'] = per_higher['증가율'].apply(x10)

In [ ]:
# 3년간 주가 평균 증가율
per_higher['증가율'].sum()/len(per_higher) #  업종 PER 보다 높았던 종목들의 3년 평균 주식증가율

35.25101265822785

In [ ]:
under_per5 = join_t3.loc[join_t3['PER']<5]
under_per5 = pd.merge(under_per5,prices_2021,how='left',on='종목코드')[['종목명_x','업종PER','PER','종가','종가_2021']]
under_per5['증가율'] = np.round(((under_per5['종가_2021']-under_per5['종가'])/under_per5['종가'])*100,2)
under_per5 = under_per5.sort_values('PER')

In [ ]:
under_per5

      종목명_x  업종PER   PER      종가   종가_2021     증가율
14      BGF    NaN  0.11    7960    5290.0  -33.54
10   오리온홀딩스    NaN  0.43   16650   15950.0   -4.20
20  SK디스커버리    NaN  0.84   25600   46400.0   81.25
15    쿠쿠홀딩스    NaN  2.07  118000   19150.0  -83.77
11      HDC    NaN  2.87   16550   10450.0  -36.86
2     현대중공업  51.34  2.93  125500   94600.0  -24.62
3   LG디스플레이   5.49  3.53   17800   24600.0   38.20
8      대한항공  25.71  3.75   32400   29350.0   -9.41
7     한화케미칼   9.91  3.94   19800   35500.0   79.29
0    SK하이닉스   5.49  4.02   60600  131000.0  116.17
19    DB하이텍   5.49  4.12   10500   72700.0  592.38
16       효성    NaN  4.14   47950   94700.0   97.50
1     롯데케미칼   9.91  4.19  275000  217000.0  -21.09
12     대한유화   9.91  4.25  147500  183000.0   24.07
4   현대중공업지주   9.91  4.54  337500   53700.0  -84.09
9        LS    NaN  4.55   48600   54100.0   11.32
5        GS    NaN  4.66   48500   39100.0  -19.38
6    대우조선해양  51.34  4.66   33300   23050.0  -30.78
13   아이에스동서  14.10  4.69   29800   44250.0   48.49
18    세아베스틸  10.50  4.93   17550   19900.0   13.39
17       풍산  10.50  4.94   26550   31150.0   17.33

In [ ]:
under_per5['증가율'].sum()/len(under_per5)

36.7452380952381

In [ ]:
over_per5 = join_t3.loc[join_t3['PER']>5]
over_per5 = pd.merge(over_per5,prices_2021,how='left',on='종목코드')[['종목명_x','업종PER','PER','종가','종가_2021']]
over_per5['증가율'] = np.round(((over_per5['종가_2021']-over_per5['종가'])/over_per5['종가'])*100,2)
over_per5 = over_per5.sort_values('PER')

In [ ]:
over_per5['증가율'].sum()/len(over_per5)

19.47229299363057

In [ ]:
df_2019_jongmok

        종목코드              종목명       종가       EPS      PER        BPS     PBR  \
0     060310              3S      2190       NaN      NaN      704.0    3.11
1     095570          AJ네트웍스      4530     320.0    14.16     6168.0    0.73
2     068400           AJ렌터카     12350     572.0    21.59    11091.0    1.11
3     006840           AK홀딩스     51900    7727.0     6.72    52954.0    0.98
4     054620          APS홀딩스      4205   46508.0     0.09    13639.0    0.31
5     265520           AP시스템     21500    1395.0    15.41     5856.0    3.67
6     211270            AP위성      6600       5.0  1320.00     5465.0    1.21
7     027410             BGF      7960   74964.0     0.11    21952.0    0.36
8     282330          BGF리테일    205500    1619.0   126.93    22486.0    9.14
9     138930         BNK금융지주      7000    1200.0     5.83    21653.0    0.32
10    001460             BYC    256000    7414.0    34.53   475434.0    0.54
11    001465            BYC우    115000       NaN      NaN        NaN     NaN
12    001040              CJ    116000   15357.0     7.55   117874.0    0.98
13    079160          CJ CGV     40300       NaN      NaN    14554.0    2.77
14    035760          CJ ENM    196500   21705.0     9.05   165443.0    1.19
15    000120          CJ대한통운    166500    1786.0    93.23   103964.0    1.60
16    011150           CJ씨푸드      2315     127.0    18.23     1662.0    1.39
17    011155         CJ씨푸드1우     27650       NaN      NaN        NaN     NaN
18    001045             CJ우     49950       NaN      NaN        NaN     NaN
19    097950          CJ제일제당    331000   26179.0    12.64   232686.0    1.42
20    097955        CJ제일제당 우    123000       NaN      NaN        NaN     NaN
21    051500         CJ프레시웨이     25550       NaN      NaN    15181.0    1.68
22    037560            CJ헬로      9060     373.0    24.29    12746.0    0.71
23    058820           CMG제약      4165       NaN      NaN      929.0    4.48
24    023460             CNH      1390      81.0    17.16     2752.0    0.51
25    065770              CS      1930      53.0    36.42     1003.0    1.92
26    083660         CSA 코스믹      3865       NaN      NaN     1199.0    3.22
27    000590           CS홀딩스     63600    5138.0    12.38   187283.0    0.34
28    012030              DB       830       NaN      NaN      735.0    1.13
29    306620        DB금융스팩6호      2005       NaN      NaN        NaN     NaN
30    016610          DB금융투자      4320     107.0    40.37    14360.0    0.30
31    005830          DB손해보험     69500   10445.0     6.65    65368.0    1.06
32    000990           DB하이텍     10500    2546.0     4.12    10240.0    1.03
33    000995         DB하이텍1우     36750       NaN      NaN        NaN     NaN
34    139130         DGB금융지주      8050    1787.0     4.50    23088.0    0.35
35    068790             DMS      4560     171.0    26.67     5892.0    0.77
36    004840           DRB동일      6480     934.0     6.94    16974.0    0.38
37    241520       DSC인베스트먼트      4030     125.0    32.24     1382.0    2.92
38    155660             DSR      3920     692.0     5.66     8721.0    0.45
39    069730           DSR제강      4210     348.0    12.10     9032.0    0.47
40    017940              E1     55100   14600.0     3.77   171187.0    0.32
41    245620            EDGC      5230       NaN      NaN      384.0   13.62
42    037370              EG     11900       NaN      NaN     6764.0    1.76
43    079190             EMW      2780       NaN      NaN     1728.0    1.61
44    007700             F&F     40100    4863.0     8.25    19218.0    2.09
45    130500           GH신소재      2435     233.0    10.45     4255.0    0.57
46    114090             GKL     23950    1302.0    18.39     8602.0    2.78
47    032860       GMR 머티리얼즈       650       4.0   162.50      404.0    1.61
48    078930              GS     48500   10416.0     4.66    81628.0    0.59
49    083450             GST      4405    1719.0     2.56     7937.0    0.55
50    006360            GS건설     42150       NaN      NaN    44190.0    0.95
51    001250           GS글로벌      2400     257.0     9.34     4452.0    0.54
52    007070           GS리테일     39250    1535.0    25.57    26369.0    1.49
53    078935             GS우     34450       NaN      NaN        NaN     NaN
54    028150           GS홈쇼핑    173100   16677.0    10.38   162004.0    1.07
55    045890              GV      1745       NaN      NaN     1702.0    1.03
56    078150         HB테크놀러지      3195     490.0     6.52     1976.0    1.62
57    012630             HDC     16550    5763.0     2.87    38991.0    0.42
58    039570       HDC아이콘트롤스      9420    1443.0     6.53    11953.0    0.79
59    089470         HDC현대EP      4345    1002.0     4.34     8772.0    0.50
60    294870       HDC현대산업개발     48450       NaN      NaN        NaN     NaN
61    036640             HRS      2840     384.0     7.40     4918.0    0.58
62    082740           HSD엔진      5100       NaN      NaN     7389.0    0.69
63    299170      IBKS제10호스팩      2055       NaN      NaN        NaN     NaN
64    254120       IBKS제5호스팩      2065      11.0   187.73     1878.0    1.10
65    264850       IBKS제6호스팩      2070       2.0  1035.00     1935.0    1.07
66    276920       IBKS제7호스팩      2265       NaN      NaN     1959.0    1.16
67    297570       IBKS제9호스팩      2375       NaN      NaN        NaN     NaN
68    003560             IHQ      1870      18.0   103.89     1558.0    1.20
69    095340             ISC      8590    1238.0     6.94    11360.0    0.76
70    099520          ITX엠투엠      1525       NaN      NaN     1043.0    1.46
71    175330          JB금융지주      5540    1207.0     4.59    15630.0    0.35
72    234080          JW생명과학     22150    1060.0    20.90     6448.0    3.44
73    067290            JW신약      6570       NaN      NaN     1009.0    6.51
74    001060          JW중외제약     41000       NaN      NaN    12302.0    3.33
75    001067       JW중외제약2우B     40200       NaN      NaN        NaN     NaN
76    001065         JW중외제약우     25300       NaN      NaN        NaN     NaN
77    096760           JW홀딩스      7190     844.0     8.52     2601.0    2.76
78    035900        JYP Ent.     29050     512.0    56.74     2452.0   11.85
79    105560            KB금융     45950    8305.0     5.53    81411.0    0.56
80    024120          KB오토시스      5400    1068.0     5.06     7398.0    0.73
81    002380             KCC    308500    4249.0    72.61   554654.0    0.56
82    021320           KCC건설      7000    1051.0     6.66    15806.0    0.44
83    036670             KCI      7780     370.0    21.03     4346.0    1.79
84    009070            KCTC      2905     298.0     9.75     6092.0    0.48
85    009440         KC그린홀딩스      3660     232.0    15.78     7226.0    0.51
86    119650           KC코트렐      4275     517.0     8.27     5861.0    0.73
87    044180            KD건설       107       NaN      NaN      111.0    0.96
88    092220             KEC      1045      10.0   104.50     1961.0    0.53
89    151860          KG ETS      3085     327.0     9.43     4087.0    0.75
90    046440         KG모빌리언스      7260     511.0    14.21     6920.0    1.05
91    035600          KG이니시스     15900       NaN      NaN     6705.0    2.37
92    001390           KG케미칼     16500     377.0    43.77    19661.0    0.84
93    060720            KH바텍      7970       NaN      NaN    10464.0    0.76
94    001940        KISCO홀딩스     13000     843.0    15.42    41227.0    0.32
95    083470           KJ프리텍       473       NaN      NaN     1875.0    0.25
96    122450             KMH      7440    1359.0     5.47     6999.0    1.06
97    052900          KMH하이텍       892       NaN      NaN     1108.0    0.81
98    058400             KNN       841      72.0    11.68     1397.0    0.60
99    114450         KPX생명과학      4215     148.0    28.48     4139.0    1.02
100   025000          KPX케미칼     52000    5543.0     9.38    89789.0    0.58
101   092230          KPX홀딩스     61400    9872.0     6.22   145038.0    0.42
102   000040           KR모터스       500       NaN      NaN      350.0    1.43
103   044450           KSS해운      6400    1120.0     5.71     9806.0    0.65
104   030200              KT     30400    1946.0    15.62    44749.0    0.68
105   033780            KT&G     97600    9217.0    10.59    56609.0    1.72
106   030210         KTB투자증권      2955     447.0     6.61     6862.0    0.43
107   036030             KTH      4660      90.0    51.78     5748.0    0.81
108   058850            KTcs      2455     170.0    14.44     3611.0    0.68
109   060370          KT서브마린      3135     401.0     7.82     4965.0    0.63
110   093050              LF     25050    2519.0     9.94    37363.0    0.67
111   003550              LG     68100   13630.0     5.00    90990.0    0.75
112   034220         LG디스플레이     17800    5038.0     3.53    40170.0    0.44
113   001120            LG상사     15350    1557.0     9.86    30815.0    0.50
114   051900          LG생활건강   1081000   36199.0    29.86   169155.0    6.39
115   051905         LG생활건강우    646000       NaN      NaN        NaN     NaN
116   003555             LG우     40300       NaN      NaN        NaN     NaN
117   032640          LG유플러스     17950    1253.0    14.33    11985.0    1.50
118   011070           LG이노텍     83700    7386.0    11.33    82426.0    1.02
119   066570            LG전자     62800    9579.0     6.56    73129.0    0.86
120   066575           LG전자우     25850       NaN      NaN        NaN     NaN
121   108670          LG하우시스     56100    6794.0     8.26    98558.0    0.57
122   108675         LG하우시스우     31000       NaN      NaN        NaN     NaN
123   051910            LG화학    337000   25367.0    13.28   206544.0    1.63
124   051915           LG화학우    191500       NaN      NaN        NaN     NaN
125   079550          LIG넥스원     38250       NaN      NaN    27454.0    1.39
126   006260              LS     48600   10691.0     4.55    84524.0    0.57
127   000680          LS네트웍스      2500     280.0     8.93     7902.0    0.32
128   010120            LS산전     47400    3583.0    13.23    38191.0    1.24
129   229640         LS전선아시아      5550     419.0    13.25     3825.0    1.45
130   023150           MH에탄올      5790     942.0     6.15     8930.0    0.65
131   065150            MP그룹      1315       NaN      NaN      412.0    3.19
132   219550            MP한강      1495     126.0    11.87      701.0    2.13
133   035420           NAVER    118000    5320.0    22.18    28936.0    4.08
134   160550             NEW      4295       NaN      NaN     4659.0    0.92
135   053290            NE능률      2920      66.0    44.24     4115.0    0.71
136   104200           NHN벅스      5780       NaN      NaN     4246.0    1.36
137   181710       NHN엔터테인먼트     57300     864.0    66.32    77006.0    0.74
138   060250      NHN한국사이버결제     11600     493.0    23.53     4653.0    2.49
139   005940          NH투자증권     12350    1170.0    10.56    16087.0    0.77
140   005945         NH투자증권우      8550       NaN      NaN        NaN     NaN
141   034310            NICE     17900    1388.0    12.90    14726.0    1.22
142   030190        NICE평가정보     10500     512.0    20.51     2825.0    3.72
143   008260            NI스틸      2270     386.0     5.88     3452.0    0.66
144   004250             NPC      3730     280.0    13.32     5966.0    0.63
145   004255            NPC우      2260       NaN      NaN        NaN     NaN
146   010060             OCI    106500    9849.0    10.81   140563.0    0.76
147   024940            PN풍년      2210     153.0    14.44     3215.0    0.69
148   005490           POSCO    237000   34464.0     6.88   501600.0    0.47
149   218410           RFHIC     25750     293.0    87.88     5587.0    4.61
150   091340          S&K폴리텍      3580     374.0     9.57     5872.0    0.61
151   100840            S&TC     10750     612.0    17.57    31228.0    0.34
152   064960          S&T모티브     27400    3888.0     7.05    49272.0    0.56
153   003570          S&T중공업      7100       NaN      NaN    18194.0    0.39
154   036530          S&T홀딩스     13200     418.0    31.58    36826.0    0.36
155   010950           S-Oil     91300   10706.0     8.53    58682.0    1.56
156   010955          S-Oil우     65000       NaN      NaN        NaN     NaN
157   019550       SBI인베스트먼트       683      17.0    40.18      526.0    1.30
158   034120             SBS     21100     850.0    24.82    30428.0    0.69
159   101060       SBS미디어홀딩스      2050      34.0    60.29     4955.0    0.41
160   046140        SBS콘텐츠허브      5030       NaN      NaN     6913.0    0.73
161   036120         SCI평가정보      1975       NaN      NaN      383.0    5.16
162   099220             SDN      1580      78.0    20.26     1525.0    1.04
163   036540          SFA반도체      1370      68.0    20.15     1773.0    0.77
164   255220              SG     10650    1203.0     8.85     3697.0    2.88
165   040610            SG&G      2330       NaN      NaN     7371.0    0.32
166   049470             SGA       543       NaN      NaN      500.0    1.09
167   184230         SGA솔루션즈      1280      67.0    19.10     1440.0    0.89
168   004060          SG세계물산       727       NaN      NaN      953.0    0.76
169   001380            SG충방      2900       8.0   362.50     2760.0    1.05
170   002360         SH에너지화학      1085      86.0    12.62      950.0    1.14
171   009160          SIMPAC      2440     509.0     4.79     8280.0    0.29
172   123700             SJM      3000     363.0     8.26    10282.0    0.29
173   025530          SJM홀딩스      3420    1130.0     3.03     9716.0    0.35
174   034730              SK    252000   30007.0     8.40   192595.0    1.31
175   232330          SK3호스팩      2050       8.0   256.25     1900.0    1.08
176   307070          SK4호스팩      2010       NaN      NaN        NaN     NaN
177   011790             SKC     35450    3104.0    11.42    38631.0    0.92
178   057500         SKC 솔믹스      2660     641.0     4.15     1165.0    2.28
179   178920        SKC코오롱PI     32200    1116.0    28.85     8453.0    3.81
180   018670            SK가스     70000   11566.0     6.05   164161.0    0.43
181   001740          SK네트웍스      5180     136.0    38.09     9546.0    0.54
182   001745         SK네트웍스우     51000       NaN      NaN        NaN     NaN
183   006120         SK디스커버리     25600   30647.0     0.84    88491.0    0.29
184   006125        SK디스커버리우     15100       NaN      NaN        NaN     NaN
185   210980           SK디앤디     27200    3362.0     8.09    16007.0    1.70
186   036490         SK머티리얼즈    146000   10124.0    14.42    36567.0    3.99
187   052260         SK바이오랜드     15600     799.0    19.52     9188.0    1.70
188   03473K             SK우    126500       NaN      NaN        NaN     NaN
189   096770         SK이노베이션    169000   22574.0     7.49   192989.0    0.88
190   096775        SK이노베이션우    111500       NaN      NaN        NaN     NaN
191   001510            SK증권       661      56.0    11.80     1265.0    0.52
192   001515           SK증권우      3965       NaN      NaN        NaN     NaN
193   285130           SK케미칼     69700       NaN      NaN    53425.0    1.30
194   28513K          SK케미칼우     24350       NaN      NaN        NaN     NaN
195   017670           SK텔레콤    272500   36582.0     7.45   220967.0    1.23
196   000660          SK하이닉스     60600   15073.0     4.02    46449.0    1.30
197   048550          SM C&C      1995       NaN      NaN     1222.0    1.63
198   063440  SM Life Design      1495      20.0    74.75     1084.0    1.38
199   005610           SPC삼립    125500    4685.0    26.79    32469.0    3.87
200   123260             STC      1675       NaN      NaN     1763.0    0.95
201   011810             STX     11400   20985.0     0.54     2224.0    5.13
202   077970           STX엔진      6700       NaN      NaN     3617.0    1.85
203   071970          STX중공업      5600  264128.0     0.02    47208.0    0.12
204   289080        SV인베스트먼트      3535     272.0    13.00     1031.0    3.43
205   084870          TBH글로벌      2990       NaN      NaN     7082.0    0.42
206   002710           TCC동양      1990      72.0    27.64     4502.0    0.44
207   089230         THE E&M       819       NaN      NaN      391.0    2.09
208   161570      THE MIDONG      3460       NaN      NaN     3221.0    1.07
209   032540           TJ미디어      3435     120.0    28.63     5814.0    0.59
210   048770             TPC      3775     307.0    12.30     2086.0    1.81
211   038340             UCI      3600       NaN      NaN      330.0   10.91
212   024070          WISCOM      2755       4.0   688.75     7604.0    0.36
213   052300          W홀딩컴퍼니       547      34.0    16.09      703.0    0.78
214   037270         YG PLUS      1985       NaN      NaN     1623.0    1.22
215   040300             YTN      2050     108.0    18.98     4536.0    0.45
216   051390              YW      3975     297.0    13.38     6164.0    0.64
217   052220            iMBC      2280       NaN      NaN     2233.0    1.02
218   079940             가비아      6540     370.0    17.68     4119.0    1.59
219   078890           가온미디어      7720     475.0    16.25     9317.0    0.83
220   000500            가온전선     16950     356.0    47.61    62234.0    0.27
221   192410             감마누       408       NaN      NaN     1266.0    0.32
222   024840            갑을메탈      2070     204.0    10.15     2459.0    0.84
223   000860          강남제비스코     24550    3568.0     6.88    74589.0    0.33
224   217730         강스템바이오텍     23600       NaN      NaN     1428.0   16.53
225   035250            강원랜드     30900    2159.0    14.31    16365.0    1.89
226   011420         갤럭시아에스엠      1660       NaN      NaN     1470.0    1.13
227   094480          갤럭시아컴즈      2795     131.0    21.34     1815.0    1.54
228   063080             게임빌     50900    1240.0    41.05    36613.0    1.39
229   039240            경남스틸      1960     170.0    11.53     3242.0    0.60
230   053950            경남제약     17200       NaN      NaN     1356.0   12.68
231   002100              경농     10350     568.0    18.22     8157.0    1.27
232   009450           경동나비엔     40000    2093.0    19.11    20135.0    1.99
233   267290          경동도시가스     33200    3771.0     8.80    62295.0    0.53
234   012320          경동인베스트     37000   20799.0     1.78   149216.0    0.25
235   011040            경동제약     11150     872.0    12.79     8339.0    1.34
236   000050              경방     10950     923.0    11.86    25502.0    0.43
237   214390            경보제약     10000     751.0    13.32     5919.0    1.69
238   012610            경인양행      5800      90.0    64.44     4812.0    1.21
239   009140            경인전자     21800       NaN      NaN    35687.0    0.61
240   024910            경창산업      1370       NaN      NaN     5879.0    0.23
241   013580            계룡건설     21100    6112.0     3.45    37841.0    0.56
242   012200            계양전기      3335     255.0    13.08     5364.0    0.62
243   012205           계양전기우      7740       NaN      NaN        NaN     NaN
244   004200            고려개발      4635     220.0    21.07     2886.0    1.61
245   002140            고려산업      2150     208.0    10.34     3559.0    0.60
246   198440           고려시멘트      2500      37.0    67.57     2539.0    0.98
247   049720          고려신용정보      3815     258.0    14.79     1210.0    3.15
248   010130            고려아연    424000   35591.0    11.91   315862.0    1.34
249   002240            고려제강     23450    1185.0    19.79    68324.0    0.34
250   014570            고려제약      7030     429.0    16.39     5179.0    1.36
251   098460              고영     83500    2013.0    41.48    11787.0    7.08
252   038530           골드퍼시픽      1465       NaN      NaN      659.0    2.22
253   307870       골든브릿지이안5호      1985       NaN      NaN        NaN     NaN
254   001290         골든브릿지증권      1850       NaN      NaN     2736.0    0.68
255   215000             골프존     33300   12645.0     2.63    30160.0    1.10
256   121440        골프존뉴딘홀딩스      3585       NaN      NaN    11694.0    0.31
257   009290            광동제약      6710     572.0    11.73     7476.0    0.90